/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s2[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {0, 1, 2, 6, 7, 8, 9};
static const casadi_int casadi_s6[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s7[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s9[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s10[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s11[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s12[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s13[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s14[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s15[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s17[41] = {13, 13, 0, 3, 6, 9, 9, 9, 9, 13, 17, 21, 25, 25, 25, 25, 0, 1, 2, 0, 1, 2, 0, 1, 2, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9};
static const casadi_int casadi_s18[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s19[3] = {0, 0, 0};
static const casadi_int casadi_s20[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s21[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s22[16] = {0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[],i2[],i3[20])->(o0,o1[13],o2[13x13,25nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+7, *w3=w+10, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, *w25=w+40, *w26=w+60, *w27=w+63, *w28=w+66, *w29=w+75, *w30=w+88, *w31=w+91, *w32=w+94, *w33=w+103, *w34=w+107, *w35=w+111, *w36=w+115, *w37=w+119, *w38=w+122, *w39=w+125, *w40=w+128, *w41=w+131, *w42=w+140, *w43=w+144, *w44=w+147, *w45=w+156, *w46=w+159, *w47=w+162, *w48=w+165, w49, w50, w51, *w52=w+172, *w53=w+181, *w54=w+190, w55, w56, w57, w58, w59, w60, *w61=w+205, *w62=w+230, *w63=w+234, *w67=w+242, *w68=w+246, *w69=w+250, *w70=w+254, w71, w72, w73, w74, w75, w76, w77, w78, w79, w80, w81, *w82=w+268, *w83=w+275, *w84=w+277;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = input[3][12] */
  w17 = arg[3] ? arg[3][12] : 0;
  /* #18: @18 = input[3][13] */
  w18 = arg[3] ? arg[3][13] : 0;
  /* #19: @19 = input[3][14] */
  w19 = arg[3] ? arg[3][14] : 0;
  /* #20: @20 = input[3][15] */
  w20 = arg[3] ? arg[3][15] : 0;
  /* #21: @21 = input[3][16] */
  w21 = arg[3] ? arg[3][16] : 0;
  /* #22: @22 = input[3][17] */
  w22 = arg[3] ? arg[3][17] : 0;
  /* #23: @23 = input[3][18] */
  w23 = arg[3] ? arg[3][18] : 0;
  /* #24: @24 = input[3][19] */
  w24 = arg[3] ? arg[3][19] : 0;
  /* #25: @25 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24) */
  rr=w25;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  /* #26: @26 = @25[3:6] */
  for (rr=w26, ss=w25+3; ss!=w25+6; ss+=1) *rr++ = *ss;
  /* #27: @27 = @26' */
  casadi_copy(w26, 3, w27);
  /* #28: @4 = mac(@27,@26,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #29: @28 = @4[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w28, ss=(&w4); cii!=casadi_s0+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #30: @3 = (@3-@28) */
  for (i=0, rr=w3, cs=w28; i<9; ++i) (*rr++) -= (*cs++);
  /* #31: @27 = @25[:3] */
  for (rr=w27, ss=w25+0; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #32: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #33: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #34: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #35: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #36: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #37: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #38: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #39: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #40: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #41: @13 = input[0][9] */
  w13 = arg[0] ? arg[0][9] : 0;
  /* #42: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #43: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #44: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #45: @29 = vertcat(@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w29;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #46: @30 = @29[:3] */
  for (rr=w30, ss=w29+0; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #47: @27 = (@27-@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #48: @2 = mac(@3,@27,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #49: @30 = @2' */
  casadi_copy(w2, 3, w30);
  /* #50: @28 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w28);
  /* #51: @1 = mac(@30,@28,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #52: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #53: @4 = 0 */
  w4 = 0.;
  /* #54: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #55: @5 = dot(@26, @27) */
  w5 = casadi_dot(3, w26, w27);
  /* #56: @27 = (@5*@26) */
  for (i=0, rr=w27, cs=w26; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #57: @31 = @27' */
  casadi_copy(w27, 3, w31);
  /* #58: @32 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w32);
  /* #59: @30 = mac(@31,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #60: @4 = mac(@30,@27,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #61: @0 = (@0+@4) */
  w0 += w4;
  /* #62: @4 = 0 */
  w4 = 0.;
  /* #63: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #64: @11 = (-@11) */
  w11 = (- w11 );
  /* #65: @12 = (-@12) */
  w12 = (- w12 );
  /* #66: @13 = (-@13) */
  w13 = (- w13 );
  /* #67: @33 = vertcat(@10, @11, @12, @13) */
  rr=w33;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #68: @34 = @29[6:10] */
  for (rr=w34, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #69: @10 = ||@34||_F */
  w10 = sqrt(casadi_dot(4, w34, w34));
  /* #70: @33 = (@33/@10) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w10;
  /* #71: {@11, @12, @13, @5} = vertsplit(@33) */
  w11 = w33[0];
  w12 = w33[1];
  w13 = w33[2];
  w5 = w33[3];
  /* #72: @35 = @25[6:10] */
  for (rr=w35, ss=w25+6; ss!=w25+10; ss+=1) *rr++ = *ss;
  /* #73: {@6, @7, @8, @9} = vertsplit(@35) */
  w6 = w35[0];
  w7 = w35[1];
  w8 = w35[2];
  w9 = w35[3];
  /* #74: @14 = (@11*@6) */
  w14  = (w11*w6);
  /* #75: @15 = (@12*@7) */
  w15  = (w12*w7);
  /* #76: @14 = (@14-@15) */
  w14 -= w15;
  /* #77: @15 = (@13*@8) */
  w15  = (w13*w8);
  /* #78: @14 = (@14-@15) */
  w14 -= w15;
  /* #79: @15 = (@5*@9) */
  w15  = (w5*w9);
  /* #80: @14 = (@14-@15) */
  w14 -= w15;
  /* #81: @15 = 0 */
  w15 = 0.;
  /* #82: @15 = (@14<@15) */
  w15  = (w14<w15);
  /* #83: @16 = (@11*@7) */
  w16  = (w11*w7);
  /* #84: @17 = (@12*@6) */
  w17  = (w12*w6);
  /* #85: @16 = (@16+@17) */
  w16 += w17;
  /* #86: @17 = (@13*@9) */
  w17  = (w13*w9);
  /* #87: @16 = (@16+@17) */
  w16 += w17;
  /* #88: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #89: @16 = (@16-@17) */
  w16 -= w17;
  /* #90: @17 = (@11*@8) */
  w17  = (w11*w8);
  /* #91: @18 = (@12*@9) */
  w18  = (w12*w9);
  /* #92: @17 = (@17-@18) */
  w17 -= w18;
  /* #93: @18 = (@13*@6) */
  w18  = (w13*w6);
  /* #94: @17 = (@17+@18) */
  w17 += w18;
  /* #95: @18 = (@5*@7) */
  w18  = (w5*w7);
  /* #96: @17 = (@17+@18) */
  w17 += w18;
  /* #97: @11 = (@11*@9) */
  w11 *= w9;
  /* #98: @12 = (@12*@8) */
  w12 *= w8;
  /* #99: @11 = (@11+@12) */
  w11 += w12;
  /* #100: @13 = (@13*@7) */
  w13 *= w7;
  /* #101: @11 = (@11-@13) */
  w11 -= w13;
  /* #102: @5 = (@5*@6) */
  w5 *= w6;
  /* #103: @11 = (@11+@5) */
  w11 += w5;
  /* #104: @35 = vertcat(@14, @16, @17, @11) */
  rr=w35;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w11;
  /* #105: @36 = (-@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) *rr++ = (- *cs++ );
  /* #106: @36 = (@15?@36:0) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) (*rr++)  = (w15?(*cs++):0);
  /* #107: @14 = (!@15) */
  w14 = (! w15 );
  /* #108: @35 = (@14?@35:0) */
  for (i=0, rr=w35, cs=w35; i<4; ++i) (*rr++)  = (w14?(*cs++):0);
  /* #109: @36 = (@36+@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) (*rr++) += (*cs++);
  /* #110: @37 = @36[1:4] */
  for (rr=w37, ss=w36+1; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #111: @38 = (2.*@37) */
  for (i=0, rr=w38, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #112: @16 = ||@37||_F */
  w16 = sqrt(casadi_dot(3, w37, w37));
  /* #113: @17 = @36[0] */
  for (rr=(&w17), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  /* #114: @11 = atan2(@16,@17) */
  w11  = atan2(w16,w17);
  /* #115: @39 = (@38*@11) */
  for (i=0, rr=w39, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w11);
  /* #116: @39 = (@39/@16) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) /= w16;
  /* #117: @40 = @39' */
  casadi_copy(w39, 3, w40);
  /* #118: @41 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w41);
  /* #119: @31 = mac(@40,@41,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #120: @4 = mac(@31,@39,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #121: @0 = (@0+@4) */
  w0 += w4;
  /* #122: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #123: @40 = @29[3:6] */
  for (rr=w40, ss=w29+3; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #124: @5 = dot(@26, @40) */
  w5 = casadi_dot(3, w26, w40);
  /* #125: @4 = (@4*@5) */
  w4 *= w5;
  /* #126: @0 = (@0-@4) */
  w0 -= w4;
  /* #127: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #128: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #129: @0 = -0.05 */
  w0 = -5.0000000000000003e-02;
  /* #130: @40 = (@0*@26) */
  for (i=0, rr=w40, cs=w26; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #131: (@29[3:6] += @40) */
  for (rr=w29+3, ss=w40; rr!=w29+6; rr+=1) *rr += *ss++;
  /* #132: @36 = (@33/@10) */
  for (i=0, rr=w36, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #133: @35 = (-@36) */
  for (i=0, rr=w35, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #134: @0 = 1 */
  w0 = 1.;
  /* #135: @0 = (@14?@0:0) */
  w0  = (w14?w0:0);
  /* #136: @42 = zeros(4x1) */
  casadi_clear(w42, 4);
  /* #137: @4 = sq(@16) */
  w4 = casadi_sq( w16 );
  /* #138: @5 = sq(@17) */
  w5 = casadi_sq( w17 );
  /* #139: @4 = (@4+@5) */
  w4 += w5;
  /* #140: @5 = (@16/@4) */
  w5  = (w16/w4);
  /* #141: @31 = @31' */
  /* #142: @40 = zeros(1x3) */
  casadi_clear(w40, 3);
  /* #143: @43 = @39' */
  casadi_copy(w39, 3, w43);
  /* #144: @44 = @41' */
  for (i=0, rr=w44, cs=w41; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #145: @40 = mac(@43,@44,@40) */
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w44+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #146: @40 = @40' */
  /* #147: @31 = (@31+@40) */
  for (i=0, rr=w31, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #148: @40 = (@31/@16) */
  for (i=0, rr=w40, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #149: @13 = dot(@38, @40) */
  w13 = casadi_dot(3, w38, w40);
  /* #150: @12 = (@5*@13) */
  w12  = (w5*w13);
  /* #151: @12 = (-@12) */
  w12 = (- w12 );
  /* #152: (@42[0] += @12) */
  for (rr=w42+0, ss=(&w12); rr!=w42+1; rr+=1) *rr += *ss++;
  /* #153: @43 = (@39/@16) */
  for (i=0, rr=w43, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #154: @45 = (-@43) */
  for (i=0, rr=w45, cs=w43; i<3; ++i) *rr++ = (- *cs++ );
  /* #155: @12 = dot(@45, @31) */
  w12 = casadi_dot(3, w45, w31);
  /* #156: @18 = (@17/@4) */
  w18  = (w17/w4);
  /* #157: @19 = (@18*@13) */
  w19  = (w18*w13);
  /* #158: @12 = (@12+@19) */
  w12 += w19;
  /* #159: @12 = (@12/@16) */
  w12 /= w16;
  /* #160: @46 = (@12*@37) */
  for (i=0, rr=w46, cs=w37; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #161: @47 = (@11*@40) */
  for (i=0, rr=w47, cs=w40; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #162: @47 = (2.*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #163: @46 = (@46+@47) */
  for (i=0, rr=w46, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #164: (@42[1:4] += @46) */
  for (rr=w42+1, ss=w46; rr!=w42+4; rr+=1) *rr += *ss++;
  /* #165: @48 = (@0*@42) */
  for (i=0, rr=w48, cs=w42; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #166: @19 = 1 */
  w19 = 1.;
  /* #167: @19 = (@15?@19:0) */
  w19  = (w15?w19:0);
  /* #168: @42 = (@19*@42) */
  for (i=0, rr=w42, cs=w42; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #169: @48 = (@48-@42) */
  for (i=0, rr=w48, cs=w42; i<4; ++i) (*rr++) -= (*cs++);
  /* #170: {@20, @21, @22, @23} = vertsplit(@48) */
  w20 = w48[0];
  w21 = w48[1];
  w22 = w48[2];
  w23 = w48[3];
  /* #171: @24 = (@9*@23) */
  w24  = (w9*w23);
  /* #172: @49 = (@8*@22) */
  w49  = (w8*w22);
  /* #173: @24 = (@24+@49) */
  w24 += w49;
  /* #174: @49 = (@7*@21) */
  w49  = (w7*w21);
  /* #175: @24 = (@24+@49) */
  w24 += w49;
  /* #176: @49 = (@6*@20) */
  w49  = (w6*w20);
  /* #177: @24 = (@24+@49) */
  w24 += w49;
  /* #178: @49 = (@8*@23) */
  w49  = (w8*w23);
  /* #179: @50 = (@9*@22) */
  w50  = (w9*w22);
  /* #180: @49 = (@49-@50) */
  w49 -= w50;
  /* #181: @50 = (@6*@21) */
  w50  = (w6*w21);
  /* #182: @49 = (@49+@50) */
  w49 += w50;
  /* #183: @50 = (@7*@20) */
  w50  = (w7*w20);
  /* #184: @49 = (@49-@50) */
  w49 -= w50;
  /* #185: @50 = (@6*@22) */
  w50  = (w6*w22);
  /* #186: @51 = (@7*@23) */
  w51  = (w7*w23);
  /* #187: @50 = (@50-@51) */
  w50 -= w51;
  /* #188: @51 = (@9*@21) */
  w51  = (w9*w21);
  /* #189: @50 = (@50+@51) */
  w50 += w51;
  /* #190: @51 = (@8*@20) */
  w51  = (w8*w20);
  /* #191: @50 = (@50-@51) */
  w50 -= w51;
  /* #192: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #193: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #194: @23 = (@23+@22) */
  w23 += w22;
  /* #195: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #196: @23 = (@23-@21) */
  w23 -= w21;
  /* #197: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #198: @23 = (@23-@20) */
  w23 -= w20;
  /* #199: @48 = vertcat(@24, @49, @50, @23) */
  rr=w48;
  *rr++ = w24;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w23;
  /* #200: @24 = dot(@35, @48) */
  w24 = casadi_dot(4, w35, w48);
  /* #201: @24 = (@24/@10) */
  w24 /= w10;
  /* #202: @42 = (@24*@34) */
  for (i=0, rr=w42, cs=w34; i<4; ++i) (*rr++)  = (w24*(*cs++));
  /* #203: (@29[6:10] += @42) */
  for (rr=w29+6, ss=w42; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #204: @30 = @30' */
  /* #205: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #206: @27 = @27' */
  /* #207: @52 = @32' */
  for (i=0, rr=w52, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #208: @46 = mac(@27,@52,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #209: @46 = @46' */
  /* #210: @30 = (@30+@46) */
  for (i=0, rr=w30, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #211: @49 = dot(@26, @30) */
  w49 = casadi_dot(3, w26, w30);
  /* #212: @30 = (@49*@26) */
  for (i=0, rr=w30, cs=w26; i<3; ++i) (*rr++)  = (w49*(*cs++));
  /* #213: @46 = zeros(3x1) */
  casadi_clear(w46, 3);
  /* #214: @53 = @3' */
  for (i=0, rr=w53, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #215: @1 = @1' */
  /* #216: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #217: @2 = @2' */
  /* #218: @54 = @28' */
  for (i=0, rr=w54, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #219: @27 = mac(@2,@54,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #220: @27 = @27' */
  /* #221: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #222: @46 = mac(@53,@1,@46) */
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w53+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #223: @30 = (@30+@46) */
  for (i=0, rr=w30, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #224: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #225: (@29[:3] += @30) */
  for (rr=w29+0, ss=w30; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #226: {@49, @50, @23, @20, @21, @22, @51, @55, @56, @57, @58, @59, @60} = vertsplit(@29) */
  w49 = w29[0];
  w50 = w29[1];
  w23 = w29[2];
  w20 = w29[3];
  w21 = w29[4];
  w22 = w29[5];
  w51 = w29[6];
  w55 = w29[7];
  w56 = w29[8];
  w57 = w29[9];
  w58 = w29[10];
  w59 = w29[11];
  w60 = w29[12];
  /* #227: output[1][0] = @49 */
  if (res[1]) res[1][0] = w49;
  /* #228: output[1][1] = @50 */
  if (res[1]) res[1][1] = w50;
  /* #229: output[1][2] = @23 */
  if (res[1]) res[1][2] = w23;
  /* #230: output[1][3] = @20 */
  if (res[1]) res[1][3] = w20;
  /* #231: output[1][4] = @21 */
  if (res[1]) res[1][4] = w21;
  /* #232: output[1][5] = @22 */
  if (res[1]) res[1][5] = w22;
  /* #233: @42 = (@48/@10) */
  for (i=0, rr=w42, cr=w48; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #234: {@22, @21, @20, @23} = vertsplit(@42) */
  w22 = w42[0];
  w21 = w42[1];
  w20 = w42[2];
  w23 = w42[3];
  /* #235: @22 = (@22+@51) */
  w22 += w51;
  /* #236: output[1][6] = @22 */
  if (res[1]) res[1][6] = w22;
  /* #237: @55 = (@55-@21) */
  w55 -= w21;
  /* #238: output[1][7] = @55 */
  if (res[1]) res[1][7] = w55;
  /* #239: @56 = (@56-@20) */
  w56 -= w20;
  /* #240: output[1][8] = @56 */
  if (res[1]) res[1][8] = w56;
  /* #241: @57 = (@57-@23) */
  w57 -= w23;
  /* #242: output[1][9] = @57 */
  if (res[1]) res[1][9] = w57;
  /* #243: output[1][10] = @58 */
  if (res[1]) res[1][10] = w58;
  /* #244: output[1][11] = @59 */
  if (res[1]) res[1][11] = w59;
  /* #245: output[1][12] = @60 */
  if (res[1]) res[1][12] = w60;
  /* #246: @61 = zeros(13x13,25nz) */
  casadi_clear(w61, 25);
  /* #247: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #248: @62 = zeros(4x1) */
  casadi_clear(w62, 4);
  /* #249: @60 = 1 */
  w60 = 1.;
  /* #250: @14 = (@14?@60:0) */
  w14  = (w14?w60:0);
  /* #251: @63 = ones(13x1,8nz) */
  casadi_fill(w63, 8, 1.);
  /* #252: {@60, NULL, NULL, NULL, NULL, NULL, @59, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@63) */
  w60 = w63[0];
  w59 = w63[4];
  /* #253: @64 = 00 */
  /* #254: @65 = 00 */
  /* #255: @66 = 00 */
  /* #256: @58 = vertcat(@59, @64, @65, @66) */
  rr=(&w58);
  *rr++ = w59;
  /* #257: @58 = (@58/@10) */
  w58 /= w10;
  /* #258: @67 = dense(@58) */
  casadi_densify((&w58), casadi_s1, w67, 0);
  /* #259: @33 = (@33/@10) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w10;
  /* #260: @58 = project(@34) */
  casadi_sparsify(w34, (&w58), casadi_s1, 0);
  /* #261: @57 = @59[0] */
  for (rr=(&w57), ss=(&w59)+0; ss!=(&w59)+1; ss+=1) *rr++ = *ss;
  /* #262: @59 = dot(@58, @57) */
  w59 = casadi_dot(1, (&w58), (&w57));
  /* #263: @59 = (@59/@10) */
  w59 /= w10;
  /* #264: @68 = (@33*@59) */
  for (i=0, rr=w68, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w59);
  /* #265: @67 = (@67-@68) */
  for (i=0, rr=w67, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #266: {@58, @23, @56, @20} = vertsplit(@67) */
  w58 = w67[0];
  w23 = w67[1];
  w56 = w67[2];
  w20 = w67[3];
  /* #267: @55 = (@6*@58) */
  w55  = (w6*w58);
  /* #268: @21 = (@7*@23) */
  w21  = (w7*w23);
  /* #269: @55 = (@55-@21) */
  w55 -= w21;
  /* #270: @21 = (@8*@56) */
  w21  = (w8*w56);
  /* #271: @55 = (@55-@21) */
  w55 -= w21;
  /* #272: @21 = (@9*@20) */
  w21  = (w9*w20);
  /* #273: @55 = (@55-@21) */
  w55 -= w21;
  /* #274: @21 = (@7*@58) */
  w21  = (w7*w58);
  /* #275: @22 = (@6*@23) */
  w22  = (w6*w23);
  /* #276: @21 = (@21+@22) */
  w21 += w22;
  /* #277: @22 = (@9*@56) */
  w22  = (w9*w56);
  /* #278: @21 = (@21+@22) */
  w21 += w22;
  /* #279: @22 = (@8*@20) */
  w22  = (w8*w20);
  /* #280: @21 = (@21-@22) */
  w21 -= w22;
  /* #281: @22 = (@8*@58) */
  w22  = (w8*w58);
  /* #282: @51 = (@9*@23) */
  w51  = (w9*w23);
  /* #283: @22 = (@22-@51) */
  w22 -= w51;
  /* #284: @51 = (@6*@56) */
  w51  = (w6*w56);
  /* #285: @22 = (@22+@51) */
  w22 += w51;
  /* #286: @51 = (@7*@20) */
  w51  = (w7*w20);
  /* #287: @22 = (@22+@51) */
  w22 += w51;
  /* #288: @58 = (@9*@58) */
  w58  = (w9*w58);
  /* #289: @23 = (@8*@23) */
  w23  = (w8*w23);
  /* #290: @58 = (@58+@23) */
  w58 += w23;
  /* #291: @56 = (@7*@56) */
  w56  = (w7*w56);
  /* #292: @58 = (@58-@56) */
  w58 -= w56;
  /* #293: @20 = (@6*@20) */
  w20  = (w6*w20);
  /* #294: @58 = (@58+@20) */
  w58 += w20;
  /* #295: @68 = vertcat(@55, @21, @22, @58) */
  rr=w68;
  *rr++ = w55;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w58;
  /* #296: @69 = (@14*@68) */
  for (i=0, rr=w69, cs=w68; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #297: @55 = 1 */
  w55 = 1.;
  /* #298: @15 = (@15?@55:0) */
  w15  = (w15?w55:0);
  /* #299: @68 = (@15*@68) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #300: @69 = (@69-@68) */
  for (i=0, rr=w69, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #301: @30 = @69[1:4] */
  for (rr=w30, ss=w69+1; ss!=w69+4; ss+=1) *rr++ = *ss;
  /* #302: @55 = dot(@37, @30) */
  w55 = casadi_dot(3, w37, w30);
  /* #303: @55 = (@55/@16) */
  w55 /= w16;
  /* #304: @21 = (@55/@4) */
  w21  = (w55/w4);
  /* #305: @22 = (@5/@4) */
  w22  = (w5/w4);
  /* #306: @58 = (2.*@16) */
  w58 = (2.* w16 );
  /* #307: @20 = (@58*@55) */
  w20  = (w58*w55);
  /* #308: @56 = (2.*@17) */
  w56 = (2.* w17 );
  /* #309: @23 = @69[0] */
  for (rr=(&w23), ss=w69+0; ss!=w69+1; ss+=1) *rr++ = *ss;
  /* #310: @51 = (@56*@23) */
  w51  = (w56*w23);
  /* #311: @20 = (@20+@51) */
  w20 += w51;
  /* #312: @51 = (@22*@20) */
  w51  = (w22*w20);
  /* #313: @21 = (@21-@51) */
  w21 -= w51;
  /* #314: @21 = (@13*@21) */
  w21  = (w13*w21);
  /* #315: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #316: @1 = (2.*@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #317: @27 = (@11*@1) */
  for (i=0, rr=w27, cs=w1; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #318: @51 = sq(@16) */
  w51 = casadi_sq( w16 );
  /* #319: @50 = sq(@17) */
  w50 = casadi_sq( w17 );
  /* #320: @51 = (@51+@50) */
  w51 += w50;
  /* #321: @17 = (@17/@51) */
  w17 /= w51;
  /* #322: @50 = (@17*@55) */
  w50  = (w17*w55);
  /* #323: @51 = (@16/@51) */
  w51  = (w16/w51);
  /* #324: @49 = (@51*@23) */
  w49  = (w51*w23);
  /* #325: @50 = (@50-@49) */
  w50 -= w49;
  /* #326: @2 = (@38*@50) */
  for (i=0, rr=w2, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #327: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #328: @27 = (@27/@16) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w16;
  /* #329: @39 = (@39/@16) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) /= w16;
  /* #330: @2 = (@39*@55) */
  for (i=0, rr=w2, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #331: @27 = (@27-@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #332: @2 = @27' */
  casadi_copy(w27, 3, w2);
  /* #333: @46 = mac(@2,@41,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #334: @46 = @46' */
  /* #335: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #336: @47 = @27' */
  casadi_copy(w27, 3, w47);
  /* #337: @2 = mac(@47,@44,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w44+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #338: @2 = @2' */
  /* #339: @46 = (@46+@2) */
  for (i=0, rr=w46, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #340: @2 = (@46/@16) */
  for (i=0, rr=w2, cr=w46; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #341: @47 = (@40/@16) */
  for (i=0, rr=w47, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #342: @70 = (@47*@55) */
  for (i=0, rr=w70, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #343: @2 = (@2-@70) */
  for (i=0, rr=w2, cs=w70; i<3; ++i) (*rr++) -= (*cs++);
  /* #344: @49 = dot(@38, @2) */
  w49 = casadi_dot(3, w38, w2);
  /* #345: @71 = dot(@1, @40) */
  w71 = casadi_dot(3, w1, w40);
  /* #346: @49 = (@49+@71) */
  w49 += w71;
  /* #347: @71 = (@5*@49) */
  w71  = (w5*w49);
  /* #348: @21 = (@21+@71) */
  w21 += w71;
  /* #349: @21 = (-@21) */
  w21 = (- w21 );
  /* #350: (@62[0] += @21) */
  for (rr=w62+0, ss=(&w21); rr!=w62+1; rr+=1) *rr += *ss++;
  /* #351: @21 = dot(@45, @46) */
  w21 = casadi_dot(3, w45, w46);
  /* #352: @27 = (@27/@16) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w16;
  /* #353: @43 = (@43/@16) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) /= w16;
  /* #354: @46 = (@43*@55) */
  for (i=0, rr=w46, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #355: @27 = (@27-@46) */
  for (i=0, rr=w27, cs=w46; i<3; ++i) (*rr++) -= (*cs++);
  /* #356: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #357: @71 = dot(@27, @31) */
  w71 = casadi_dot(3, w27, w31);
  /* #358: @21 = (@21+@71) */
  w21 += w71;
  /* #359: @23 = (@23/@4) */
  w23 /= w4;
  /* #360: @71 = (@18/@4) */
  w71  = (w18/w4);
  /* #361: @20 = (@71*@20) */
  w20  = (w71*w20);
  /* #362: @23 = (@23-@20) */
  w23 -= w20;
  /* #363: @23 = (@13*@23) */
  w23  = (w13*w23);
  /* #364: @49 = (@18*@49) */
  w49  = (w18*w49);
  /* #365: @23 = (@23+@49) */
  w23 += w49;
  /* #366: @21 = (@21+@23) */
  w21 += w23;
  /* #367: @21 = (@21/@16) */
  w21 /= w16;
  /* #368: @23 = (@12/@16) */
  w23  = (w12/w16);
  /* #369: @55 = (@23*@55) */
  w55  = (w23*w55);
  /* #370: @21 = (@21-@55) */
  w21 -= w55;
  /* #371: @27 = (@37*@21) */
  for (i=0, rr=w27, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #372: @30 = (@12*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #373: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #374: @30 = (@40*@50) */
  for (i=0, rr=w30, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #375: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #376: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #377: @30 = (2.*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #378: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #379: (@62[1:4] += @27) */
  for (rr=w62+1, ss=w27; rr!=w62+4; rr+=1) *rr += *ss++;
  /* #380: @69 = (@0*@62) */
  for (i=0, rr=w69, cs=w62; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #381: @62 = (@19*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #382: @69 = (@69-@62) */
  for (i=0, rr=w69, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #383: {@50, @21, @55, @49} = vertsplit(@69) */
  w50 = w69[0];
  w21 = w69[1];
  w55 = w69[2];
  w49 = w69[3];
  /* #384: @20 = (@9*@49) */
  w20  = (w9*w49);
  /* #385: @72 = (@8*@55) */
  w72  = (w8*w55);
  /* #386: @20 = (@20+@72) */
  w20 += w72;
  /* #387: @72 = (@7*@21) */
  w72  = (w7*w21);
  /* #388: @20 = (@20+@72) */
  w20 += w72;
  /* #389: @72 = (@6*@50) */
  w72  = (w6*w50);
  /* #390: @20 = (@20+@72) */
  w20 += w72;
  /* #391: @72 = (@8*@49) */
  w72  = (w8*w49);
  /* #392: @73 = (@9*@55) */
  w73  = (w9*w55);
  /* #393: @72 = (@72-@73) */
  w72 -= w73;
  /* #394: @73 = (@6*@21) */
  w73  = (w6*w21);
  /* #395: @72 = (@72+@73) */
  w72 += w73;
  /* #396: @73 = (@7*@50) */
  w73  = (w7*w50);
  /* #397: @72 = (@72-@73) */
  w72 -= w73;
  /* #398: @73 = (@6*@55) */
  w73  = (w6*w55);
  /* #399: @74 = (@7*@49) */
  w74  = (w7*w49);
  /* #400: @73 = (@73-@74) */
  w73 -= w74;
  /* #401: @74 = (@9*@21) */
  w74  = (w9*w21);
  /* #402: @73 = (@73+@74) */
  w73 += w74;
  /* #403: @74 = (@8*@50) */
  w74  = (w8*w50);
  /* #404: @73 = (@73-@74) */
  w73 -= w74;
  /* #405: @49 = (@6*@49) */
  w49  = (w6*w49);
  /* #406: @55 = (@7*@55) */
  w55  = (w7*w55);
  /* #407: @49 = (@49+@55) */
  w49 += w55;
  /* #408: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #409: @49 = (@49-@21) */
  w49 -= w21;
  /* #410: @50 = (@9*@50) */
  w50  = (w9*w50);
  /* #411: @49 = (@49-@50) */
  w49 -= w50;
  /* #412: @69 = vertcat(@20, @72, @73, @49) */
  rr=w69;
  *rr++ = w20;
  *rr++ = w72;
  *rr++ = w73;
  *rr++ = w49;
  /* #413: @20 = dot(@35, @69) */
  w20 = casadi_dot(4, w35, w69);
  /* #414: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #415: @36 = (@36/@10) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w10;
  /* #416: @62 = (@36*@59) */
  for (i=0, rr=w62, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w59);
  /* #417: @67 = (@67-@62) */
  for (i=0, rr=w67, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #418: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #419: @72 = dot(@67, @48) */
  w72 = casadi_dot(4, w67, w48);
  /* #420: @20 = (@20+@72) */
  w20 += w72;
  /* #421: @20 = (@20/@10) */
  w20 /= w10;
  /* #422: @72 = (@24/@10) */
  w72  = (w24/w10);
  /* #423: @73 = (@72*@59) */
  w73  = (w72*w59);
  /* #424: @20 = (@20-@73) */
  w20 -= w73;
  /* #425: @67 = (@34*@20) */
  for (i=0, rr=w67, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #426: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #427: @62 = dense(@57) */
  casadi_densify((&w57), casadi_s1, w62, 0);
  /* #428: @67 = (@67+@62) */
  for (i=0, rr=w67, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #429: (@29[6:10] += @67) */
  for (rr=w29+6, ss=w67; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #430: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #431: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s2, 0);
  /* #432: @20 = @60[0] */
  for (rr=(&w20), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #433: @20 = (-@20) */
  w20 = (- w20 );
  /* #434: @60 = dot(@57, @20) */
  w60 = casadi_dot(1, (&w57), (&w20));
  /* #435: @30 = (@26*@60) */
  for (i=0, rr=w30, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #436: @2 = @30' */
  casadi_copy(w30, 3, w2);
  /* #437: @27 = mac(@2,@32,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #438: @27 = @27' */
  /* #439: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #440: @30 = @30' */
  /* #441: @2 = mac(@30,@52,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #442: @2 = @2' */
  /* #443: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #444: @60 = dot(@26, @27) */
  w60 = casadi_dot(3, w26, w27);
  /* #445: @27 = (@26*@60) */
  for (i=0, rr=w27, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #446: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #447: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #448: @46 = zeros(3x1) */
  casadi_clear(w46, 3);
  /* #449: @46 = mac(@3,@20,@46) */
  casadi_mtimes(w3, casadi_s4, (&w20), casadi_s2, w46, casadi_s3, w, 0);
  /* #450: @1 = @46' */
  casadi_copy(w46, 3, w1);
  /* #451: @30 = mac(@1,@28,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #452: @30 = @30' */
  /* #453: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #454: @46 = @46' */
  /* #455: @1 = mac(@46,@54,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #456: @1 = @1' */
  /* #457: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #458: @2 = mac(@53,@30,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w53+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #459: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #460: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #461: (@29[:3] += @27) */
  for (rr=w29+0, ss=w27; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #462: {@20, @60, @57, @73, @49, @50, @21, @55, @74, @75, @76, @77, @78} = vertsplit(@29) */
  w20 = w29[0];
  w60 = w29[1];
  w57 = w29[2];
  w73 = w29[3];
  w49 = w29[4];
  w50 = w29[5];
  w21 = w29[6];
  w55 = w29[7];
  w74 = w29[8];
  w75 = w29[9];
  w76 = w29[10];
  w77 = w29[11];
  w78 = w29[12];
  /* #463: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #464: @42 = (@42/@10) */
  for (i=0, rr=w42; i<4; ++i) (*rr++) /= w10;
  /* #465: @67 = (@42*@59) */
  for (i=0, rr=w67, cr=w42; i<4; ++i) (*rr++)  = ((*cr++)*w59);
  /* #466: @69 = (@69-@67) */
  for (i=0, rr=w69, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #467: {@59, @79, @80, @81} = vertsplit(@69) */
  w59 = w69[0];
  w79 = w69[1];
  w80 = w69[2];
  w81 = w69[3];
  /* #468: @59 = (@59+@21) */
  w59 += w21;
  /* #469: @55 = (@55-@79) */
  w55 -= w79;
  /* #470: @74 = (@74-@80) */
  w74 -= w80;
  /* #471: @75 = (@75-@81) */
  w75 -= w81;
  /* #472: @29 = vertcat(@20, @60, @57, @73, @49, @50, @59, @55, @74, @75, @76, @77, @78) */
  rr=w29;
  *rr++ = w20;
  *rr++ = w60;
  *rr++ = w57;
  *rr++ = w73;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w59;
  *rr++ = w55;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w77;
  *rr++ = w78;
  /* #473: @82 = @29[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w29; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #474: (@61[0, 1, 2, 9, 10, 11, 12] = @82) */
  for (cii=casadi_s6, rr=w61, ss=w82; cii!=casadi_s6+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #475: @82 = @29[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w29; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #476: (@61[0, 3, 6, 9, 13, 17, 21] = @82) */
  for (cii=casadi_s7, rr=w61, ss=w82; cii!=casadi_s7+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #477: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #478: @69 = zeros(4x1) */
  casadi_clear(w69, 4);
  /* #479: @64 = 00 */
  /* #480: @83 = ones(13x1,2nz) */
  casadi_fill(w83, 2, 1.);
  /* #481: {NULL, @20, NULL, NULL, NULL, NULL, NULL, @60, NULL, NULL, NULL, NULL, NULL} = vertsplit(@83) */
  w20 = w83[0];
  w60 = w83[1];
  /* #482: @57 = (-@60) */
  w57 = (- w60 );
  /* #483: @65 = 00 */
  /* #484: @66 = 00 */
  /* #485: @73 = vertcat(@64, @57, @65, @66) */
  rr=(&w73);
  *rr++ = w57;
  /* #486: @73 = (@73/@10) */
  w73 /= w10;
  /* #487: @67 = dense(@73) */
  casadi_densify((&w73), casadi_s8, w67, 0);
  /* #488: @73 = project(@34) */
  casadi_sparsify(w34, (&w73), casadi_s8, 0);
  /* #489: @57 = @60[0] */
  for (rr=(&w57), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #490: @60 = dot(@73, @57) */
  w60 = casadi_dot(1, (&w73), (&w57));
  /* #491: @60 = (@60/@10) */
  w60 /= w10;
  /* #492: @62 = (@33*@60) */
  for (i=0, rr=w62, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #493: @67 = (@67-@62) */
  for (i=0, rr=w67, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #494: {@73, @49, @50, @59} = vertsplit(@67) */
  w73 = w67[0];
  w49 = w67[1];
  w50 = w67[2];
  w59 = w67[3];
  /* #495: @55 = (@6*@73) */
  w55  = (w6*w73);
  /* #496: @74 = (@7*@49) */
  w74  = (w7*w49);
  /* #497: @55 = (@55-@74) */
  w55 -= w74;
  /* #498: @74 = (@8*@50) */
  w74  = (w8*w50);
  /* #499: @55 = (@55-@74) */
  w55 -= w74;
  /* #500: @74 = (@9*@59) */
  w74  = (w9*w59);
  /* #501: @55 = (@55-@74) */
  w55 -= w74;
  /* #502: @74 = (@7*@73) */
  w74  = (w7*w73);
  /* #503: @75 = (@6*@49) */
  w75  = (w6*w49);
  /* #504: @74 = (@74+@75) */
  w74 += w75;
  /* #505: @75 = (@9*@50) */
  w75  = (w9*w50);
  /* #506: @74 = (@74+@75) */
  w74 += w75;
  /* #507: @75 = (@8*@59) */
  w75  = (w8*w59);
  /* #508: @74 = (@74-@75) */
  w74 -= w75;
  /* #509: @75 = (@8*@73) */
  w75  = (w8*w73);
  /* #510: @76 = (@9*@49) */
  w76  = (w9*w49);
  /* #511: @75 = (@75-@76) */
  w75 -= w76;
  /* #512: @76 = (@6*@50) */
  w76  = (w6*w50);
  /* #513: @75 = (@75+@76) */
  w75 += w76;
  /* #514: @76 = (@7*@59) */
  w76  = (w7*w59);
  /* #515: @75 = (@75+@76) */
  w75 += w76;
  /* #516: @73 = (@9*@73) */
  w73  = (w9*w73);
  /* #517: @49 = (@8*@49) */
  w49  = (w8*w49);
  /* #518: @73 = (@73+@49) */
  w73 += w49;
  /* #519: @50 = (@7*@50) */
  w50  = (w7*w50);
  /* #520: @73 = (@73-@50) */
  w73 -= w50;
  /* #521: @59 = (@6*@59) */
  w59  = (w6*w59);
  /* #522: @73 = (@73+@59) */
  w73 += w59;
  /* #523: @62 = vertcat(@55, @74, @75, @73) */
  rr=w62;
  *rr++ = w55;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w73;
  /* #524: @68 = (@14*@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #525: @62 = (@15*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #526: @68 = (@68-@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #527: @27 = @68[1:4] */
  for (rr=w27, ss=w68+1; ss!=w68+4; ss+=1) *rr++ = *ss;
  /* #528: @55 = dot(@37, @27) */
  w55 = casadi_dot(3, w37, w27);
  /* #529: @55 = (@55/@16) */
  w55 /= w16;
  /* #530: @74 = (@55/@4) */
  w74  = (w55/w4);
  /* #531: @75 = (@58*@55) */
  w75  = (w58*w55);
  /* #532: @73 = @68[0] */
  for (rr=(&w73), ss=w68+0; ss!=w68+1; ss+=1) *rr++ = *ss;
  /* #533: @59 = (@56*@73) */
  w59  = (w56*w73);
  /* #534: @75 = (@75+@59) */
  w75 += w59;
  /* #535: @59 = (@22*@75) */
  w59  = (w22*w75);
  /* #536: @74 = (@74-@59) */
  w74 -= w59;
  /* #537: @74 = (@13*@74) */
  w74  = (w13*w74);
  /* #538: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #539: @30 = (2.*@27) */
  for (i=0, rr=w30, cs=w27; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #540: @1 = (@11*@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #541: @59 = (@17*@55) */
  w59  = (w17*w55);
  /* #542: @50 = (@51*@73) */
  w50  = (w51*w73);
  /* #543: @59 = (@59-@50) */
  w59 -= w50;
  /* #544: @46 = (@38*@59) */
  for (i=0, rr=w46, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #545: @1 = (@1+@46) */
  for (i=0, rr=w1, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #546: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #547: @46 = (@39*@55) */
  for (i=0, rr=w46, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #548: @1 = (@1-@46) */
  for (i=0, rr=w1, cs=w46; i<3; ++i) (*rr++) -= (*cs++);
  /* #549: @46 = @1' */
  casadi_copy(w1, 3, w46);
  /* #550: @2 = mac(@46,@41,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #551: @2 = @2' */
  /* #552: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #553: @70 = @1' */
  casadi_copy(w1, 3, w70);
  /* #554: @46 = mac(@70,@44,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w70+j, tt=w44+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #555: @46 = @46' */
  /* #556: @2 = (@2+@46) */
  for (i=0, rr=w2, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #557: @46 = (@2/@16) */
  for (i=0, rr=w46, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #558: @70 = (@47*@55) */
  for (i=0, rr=w70, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #559: @46 = (@46-@70) */
  for (i=0, rr=w46, cs=w70; i<3; ++i) (*rr++) -= (*cs++);
  /* #560: @50 = dot(@38, @46) */
  w50 = casadi_dot(3, w38, w46);
  /* #561: @49 = dot(@30, @40) */
  w49 = casadi_dot(3, w30, w40);
  /* #562: @50 = (@50+@49) */
  w50 += w49;
  /* #563: @49 = (@5*@50) */
  w49  = (w5*w50);
  /* #564: @74 = (@74+@49) */
  w74 += w49;
  /* #565: @74 = (-@74) */
  w74 = (- w74 );
  /* #566: (@69[0] += @74) */
  for (rr=w69+0, ss=(&w74); rr!=w69+1; rr+=1) *rr += *ss++;
  /* #567: @74 = dot(@45, @2) */
  w74 = casadi_dot(3, w45, w2);
  /* #568: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #569: @2 = (@43*@55) */
  for (i=0, rr=w2, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #570: @1 = (@1-@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #571: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #572: @49 = dot(@1, @31) */
  w49 = casadi_dot(3, w1, w31);
  /* #573: @74 = (@74+@49) */
  w74 += w49;
  /* #574: @73 = (@73/@4) */
  w73 /= w4;
  /* #575: @75 = (@71*@75) */
  w75  = (w71*w75);
  /* #576: @73 = (@73-@75) */
  w73 -= w75;
  /* #577: @73 = (@13*@73) */
  w73  = (w13*w73);
  /* #578: @50 = (@18*@50) */
  w50  = (w18*w50);
  /* #579: @73 = (@73+@50) */
  w73 += w50;
  /* #580: @74 = (@74+@73) */
  w74 += w73;
  /* #581: @74 = (@74/@16) */
  w74 /= w16;
  /* #582: @55 = (@23*@55) */
  w55  = (w23*w55);
  /* #583: @74 = (@74-@55) */
  w74 -= w55;
  /* #584: @1 = (@37*@74) */
  for (i=0, rr=w1, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #585: @27 = (@12*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #586: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #587: @27 = (@40*@59) */
  for (i=0, rr=w27, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #588: @46 = (@11*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #589: @27 = (@27+@46) */
  for (i=0, rr=w27, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #590: @27 = (2.*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #591: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #592: (@69[1:4] += @1) */
  for (rr=w69+1, ss=w1; rr!=w69+4; rr+=1) *rr += *ss++;
  /* #593: @68 = (@0*@69) */
  for (i=0, rr=w68, cs=w69; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #594: @69 = (@19*@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #595: @68 = (@68-@69) */
  for (i=0, rr=w68, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #596: {@59, @74, @55, @73} = vertsplit(@68) */
  w59 = w68[0];
  w74 = w68[1];
  w55 = w68[2];
  w73 = w68[3];
  /* #597: @50 = (@9*@73) */
  w50  = (w9*w73);
  /* #598: @75 = (@8*@55) */
  w75  = (w8*w55);
  /* #599: @50 = (@50+@75) */
  w50 += w75;
  /* #600: @75 = (@7*@74) */
  w75  = (w7*w74);
  /* #601: @50 = (@50+@75) */
  w50 += w75;
  /* #602: @75 = (@6*@59) */
  w75  = (w6*w59);
  /* #603: @50 = (@50+@75) */
  w50 += w75;
  /* #604: @75 = (@8*@73) */
  w75  = (w8*w73);
  /* #605: @49 = (@9*@55) */
  w49  = (w9*w55);
  /* #606: @75 = (@75-@49) */
  w75 -= w49;
  /* #607: @49 = (@6*@74) */
  w49  = (w6*w74);
  /* #608: @75 = (@75+@49) */
  w75 += w49;
  /* #609: @49 = (@7*@59) */
  w49  = (w7*w59);
  /* #610: @75 = (@75-@49) */
  w75 -= w49;
  /* #611: @49 = (@6*@55) */
  w49  = (w6*w55);
  /* #612: @76 = (@7*@73) */
  w76  = (w7*w73);
  /* #613: @49 = (@49-@76) */
  w49 -= w76;
  /* #614: @76 = (@9*@74) */
  w76  = (w9*w74);
  /* #615: @49 = (@49+@76) */
  w49 += w76;
  /* #616: @76 = (@8*@59) */
  w76  = (w8*w59);
  /* #617: @49 = (@49-@76) */
  w49 -= w76;
  /* #618: @73 = (@6*@73) */
  w73  = (w6*w73);
  /* #619: @55 = (@7*@55) */
  w55  = (w7*w55);
  /* #620: @73 = (@73+@55) */
  w73 += w55;
  /* #621: @74 = (@8*@74) */
  w74  = (w8*w74);
  /* #622: @73 = (@73-@74) */
  w73 -= w74;
  /* #623: @59 = (@9*@59) */
  w59  = (w9*w59);
  /* #624: @73 = (@73-@59) */
  w73 -= w59;
  /* #625: @68 = vertcat(@50, @75, @49, @73) */
  rr=w68;
  *rr++ = w50;
  *rr++ = w75;
  *rr++ = w49;
  *rr++ = w73;
  /* #626: @50 = dot(@35, @68) */
  w50 = casadi_dot(4, w35, w68);
  /* #627: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #628: @69 = (@36*@60) */
  for (i=0, rr=w69, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #629: @67 = (@67-@69) */
  for (i=0, rr=w67, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #630: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #631: @75 = dot(@67, @48) */
  w75 = casadi_dot(4, w67, w48);
  /* #632: @50 = (@50+@75) */
  w50 += w75;
  /* #633: @50 = (@50/@10) */
  w50 /= w10;
  /* #634: @75 = (@72*@60) */
  w75  = (w72*w60);
  /* #635: @50 = (@50-@75) */
  w50 -= w75;
  /* #636: @67 = (@34*@50) */
  for (i=0, rr=w67, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #637: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #638: @69 = dense(@57) */
  casadi_densify((&w57), casadi_s8, w69, 0);
  /* #639: @67 = (@67+@69) */
  for (i=0, rr=w67, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #640: (@29[6:10] += @67) */
  for (rr=w29+6, ss=w67; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #641: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #642: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s9, 0);
  /* #643: @50 = @20[0] */
  for (rr=(&w50), ss=(&w20)+0; ss!=(&w20)+1; ss+=1) *rr++ = *ss;
  /* #644: @50 = (-@50) */
  w50 = (- w50 );
  /* #645: @20 = dot(@57, @50) */
  w20 = casadi_dot(1, (&w57), (&w50));
  /* #646: @27 = (@26*@20) */
  for (i=0, rr=w27, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #647: @46 = @27' */
  casadi_copy(w27, 3, w46);
  /* #648: @1 = mac(@46,@32,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #649: @1 = @1' */
  /* #650: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #651: @27 = @27' */
  /* #652: @46 = mac(@27,@52,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #653: @46 = @46' */
  /* #654: @1 = (@1+@46) */
  for (i=0, rr=w1, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #655: @20 = dot(@26, @1) */
  w20 = casadi_dot(3, w26, w1);
  /* #656: @1 = (@26*@20) */
  for (i=0, rr=w1, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #657: @46 = zeros(3x1) */
  casadi_clear(w46, 3);
  /* #658: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #659: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #660: @2 = mac(@3,@50,@2) */
  casadi_mtimes(w3, casadi_s4, (&w50), casadi_s9, w2, casadi_s3, w, 0);
  /* #661: @30 = @2' */
  casadi_copy(w2, 3, w30);
  /* #662: @27 = mac(@30,@28,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #663: @27 = @27' */
  /* #664: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #665: @2 = @2' */
  /* #666: @30 = mac(@2,@54,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #667: @30 = @30' */
  /* #668: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #669: @46 = mac(@53,@27,@46) */
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w53+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #670: @1 = (@1+@46) */
  for (i=0, rr=w1, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #671: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #672: (@29[:3] += @1) */
  for (rr=w29+0, ss=w1; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #673: {@50, @20, @57, @75, @49, @73, @59, @74, @55, @76, @77, @78, @81} = vertsplit(@29) */
  w50 = w29[0];
  w20 = w29[1];
  w57 = w29[2];
  w75 = w29[3];
  w49 = w29[4];
  w73 = w29[5];
  w59 = w29[6];
  w74 = w29[7];
  w55 = w29[8];
  w76 = w29[9];
  w77 = w29[10];
  w78 = w29[11];
  w81 = w29[12];
  /* #674: @68 = (@68/@10) */
  for (i=0, rr=w68; i<4; ++i) (*rr++) /= w10;
  /* #675: @67 = (@42*@60) */
  for (i=0, rr=w67, cr=w42; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #676: @68 = (@68-@67) */
  for (i=0, rr=w68, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #677: {@60, @80, @79, @21} = vertsplit(@68) */
  w60 = w68[0];
  w80 = w68[1];
  w79 = w68[2];
  w21 = w68[3];
  /* #678: @60 = (@60+@59) */
  w60 += w59;
  /* #679: @74 = (@74-@80) */
  w74 -= w80;
  /* #680: @55 = (@55-@79) */
  w55 -= w79;
  /* #681: @76 = (@76-@21) */
  w76 -= w21;
  /* #682: @29 = vertcat(@50, @20, @57, @75, @49, @73, @60, @74, @55, @76, @77, @78, @81) */
  rr=w29;
  *rr++ = w50;
  *rr++ = w20;
  *rr++ = w57;
  *rr++ = w75;
  *rr++ = w49;
  *rr++ = w73;
  *rr++ = w60;
  *rr++ = w74;
  *rr++ = w55;
  *rr++ = w76;
  *rr++ = w77;
  *rr++ = w78;
  *rr++ = w81;
  /* #683: @82 = @29[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w29; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #684: (@61[3, 4, 5, 13, 14, 15, 16] = @82) */
  for (cii=casadi_s10, rr=w61, ss=w82; cii!=casadi_s10+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #685: @82 = @29[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w29; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #686: (@61[1, 4, 7, 10, 14, 18, 22] = @82) */
  for (cii=casadi_s11, rr=w61, ss=w82; cii!=casadi_s11+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #687: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #688: @68 = zeros(4x1) */
  casadi_clear(w68, 4);
  /* #689: @64 = 00 */
  /* #690: @65 = 00 */
  /* #691: @83 = ones(13x1,2nz) */
  casadi_fill(w83, 2, 1.);
  /* #692: {NULL, NULL, @50, NULL, NULL, NULL, NULL, NULL, @20, NULL, NULL, NULL, NULL} = vertsplit(@83) */
  w50 = w83[0];
  w20 = w83[1];
  /* #693: @57 = (-@20) */
  w57 = (- w20 );
  /* #694: @66 = 00 */
  /* #695: @75 = vertcat(@64, @65, @57, @66) */
  rr=(&w75);
  *rr++ = w57;
  /* #696: @75 = (@75/@10) */
  w75 /= w10;
  /* #697: @67 = dense(@75) */
  casadi_densify((&w75), casadi_s12, w67, 0);
  /* #698: @75 = project(@34) */
  casadi_sparsify(w34, (&w75), casadi_s12, 0);
  /* #699: @57 = @20[0] */
  for (rr=(&w57), ss=(&w20)+0; ss!=(&w20)+1; ss+=1) *rr++ = *ss;
  /* #700: @20 = dot(@75, @57) */
  w20 = casadi_dot(1, (&w75), (&w57));
  /* #701: @20 = (@20/@10) */
  w20 /= w10;
  /* #702: @69 = (@33*@20) */
  for (i=0, rr=w69, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #703: @67 = (@67-@69) */
  for (i=0, rr=w67, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #704: {@75, @49, @73, @60} = vertsplit(@67) */
  w75 = w67[0];
  w49 = w67[1];
  w73 = w67[2];
  w60 = w67[3];
  /* #705: @74 = (@6*@75) */
  w74  = (w6*w75);
  /* #706: @55 = (@7*@49) */
  w55  = (w7*w49);
  /* #707: @74 = (@74-@55) */
  w74 -= w55;
  /* #708: @55 = (@8*@73) */
  w55  = (w8*w73);
  /* #709: @74 = (@74-@55) */
  w74 -= w55;
  /* #710: @55 = (@9*@60) */
  w55  = (w9*w60);
  /* #711: @74 = (@74-@55) */
  w74 -= w55;
  /* #712: @55 = (@7*@75) */
  w55  = (w7*w75);
  /* #713: @76 = (@6*@49) */
  w76  = (w6*w49);
  /* #714: @55 = (@55+@76) */
  w55 += w76;
  /* #715: @76 = (@9*@73) */
  w76  = (w9*w73);
  /* #716: @55 = (@55+@76) */
  w55 += w76;
  /* #717: @76 = (@8*@60) */
  w76  = (w8*w60);
  /* #718: @55 = (@55-@76) */
  w55 -= w76;
  /* #719: @76 = (@8*@75) */
  w76  = (w8*w75);
  /* #720: @77 = (@9*@49) */
  w77  = (w9*w49);
  /* #721: @76 = (@76-@77) */
  w76 -= w77;
  /* #722: @77 = (@6*@73) */
  w77  = (w6*w73);
  /* #723: @76 = (@76+@77) */
  w76 += w77;
  /* #724: @77 = (@7*@60) */
  w77  = (w7*w60);
  /* #725: @76 = (@76+@77) */
  w76 += w77;
  /* #726: @75 = (@9*@75) */
  w75  = (w9*w75);
  /* #727: @49 = (@8*@49) */
  w49  = (w8*w49);
  /* #728: @75 = (@75+@49) */
  w75 += w49;
  /* #729: @73 = (@7*@73) */
  w73  = (w7*w73);
  /* #730: @75 = (@75-@73) */
  w75 -= w73;
  /* #731: @60 = (@6*@60) */
  w60  = (w6*w60);
  /* #732: @75 = (@75+@60) */
  w75 += w60;
  /* #733: @69 = vertcat(@74, @55, @76, @75) */
  rr=w69;
  *rr++ = w74;
  *rr++ = w55;
  *rr++ = w76;
  *rr++ = w75;
  /* #734: @62 = (@14*@69) */
  for (i=0, rr=w62, cs=w69; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #735: @69 = (@15*@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #736: @62 = (@62-@69) */
  for (i=0, rr=w62, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #737: @1 = @62[1:4] */
  for (rr=w1, ss=w62+1; ss!=w62+4; ss+=1) *rr++ = *ss;
  /* #738: @74 = dot(@37, @1) */
  w74 = casadi_dot(3, w37, w1);
  /* #739: @74 = (@74/@16) */
  w74 /= w16;
  /* #740: @55 = (@74/@4) */
  w55  = (w74/w4);
  /* #741: @76 = (@58*@74) */
  w76  = (w58*w74);
  /* #742: @75 = @62[0] */
  for (rr=(&w75), ss=w62+0; ss!=w62+1; ss+=1) *rr++ = *ss;
  /* #743: @60 = (@56*@75) */
  w60  = (w56*w75);
  /* #744: @76 = (@76+@60) */
  w76 += w60;
  /* #745: @60 = (@22*@76) */
  w60  = (w22*w76);
  /* #746: @55 = (@55-@60) */
  w55 -= w60;
  /* #747: @55 = (@13*@55) */
  w55  = (w13*w55);
  /* #748: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #749: @27 = (2.*@1) */
  for (i=0, rr=w27, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #750: @30 = (@11*@27) */
  for (i=0, rr=w30, cs=w27; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #751: @60 = (@17*@74) */
  w60  = (w17*w74);
  /* #752: @73 = (@51*@75) */
  w73  = (w51*w75);
  /* #753: @60 = (@60-@73) */
  w60 -= w73;
  /* #754: @2 = (@38*@60) */
  for (i=0, rr=w2, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #755: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #756: @30 = (@30/@16) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w16;
  /* #757: @2 = (@39*@74) */
  for (i=0, rr=w2, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #758: @30 = (@30-@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #759: @2 = @30' */
  casadi_copy(w30, 3, w2);
  /* #760: @46 = mac(@2,@41,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #761: @46 = @46' */
  /* #762: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #763: @70 = @30' */
  casadi_copy(w30, 3, w70);
  /* #764: @2 = mac(@70,@44,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w70+j, tt=w44+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #765: @2 = @2' */
  /* #766: @46 = (@46+@2) */
  for (i=0, rr=w46, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #767: @2 = (@46/@16) */
  for (i=0, rr=w2, cr=w46; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #768: @70 = (@47*@74) */
  for (i=0, rr=w70, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #769: @2 = (@2-@70) */
  for (i=0, rr=w2, cs=w70; i<3; ++i) (*rr++) -= (*cs++);
  /* #770: @73 = dot(@38, @2) */
  w73 = casadi_dot(3, w38, w2);
  /* #771: @49 = dot(@27, @40) */
  w49 = casadi_dot(3, w27, w40);
  /* #772: @73 = (@73+@49) */
  w73 += w49;
  /* #773: @49 = (@5*@73) */
  w49  = (w5*w73);
  /* #774: @55 = (@55+@49) */
  w55 += w49;
  /* #775: @55 = (-@55) */
  w55 = (- w55 );
  /* #776: (@68[0] += @55) */
  for (rr=w68+0, ss=(&w55); rr!=w68+1; rr+=1) *rr += *ss++;
  /* #777: @55 = dot(@45, @46) */
  w55 = casadi_dot(3, w45, w46);
  /* #778: @30 = (@30/@16) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w16;
  /* #779: @46 = (@43*@74) */
  for (i=0, rr=w46, cr=w43; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #780: @30 = (@30-@46) */
  for (i=0, rr=w30, cs=w46; i<3; ++i) (*rr++) -= (*cs++);
  /* #781: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #782: @49 = dot(@30, @31) */
  w49 = casadi_dot(3, w30, w31);
  /* #783: @55 = (@55+@49) */
  w55 += w49;
  /* #784: @75 = (@75/@4) */
  w75 /= w4;
  /* #785: @76 = (@71*@76) */
  w76  = (w71*w76);
  /* #786: @75 = (@75-@76) */
  w75 -= w76;
  /* #787: @75 = (@13*@75) */
  w75  = (w13*w75);
  /* #788: @73 = (@18*@73) */
  w73  = (w18*w73);
  /* #789: @75 = (@75+@73) */
  w75 += w73;
  /* #790: @55 = (@55+@75) */
  w55 += w75;
  /* #791: @55 = (@55/@16) */
  w55 /= w16;
  /* #792: @74 = (@23*@74) */
  w74  = (w23*w74);
  /* #793: @55 = (@55-@74) */
  w55 -= w74;
  /* #794: @30 = (@37*@55) */
  for (i=0, rr=w30, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #795: @1 = (@12*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #796: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #797: @1 = (@40*@60) */
  for (i=0, rr=w1, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #798: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #799: @1 = (@1+@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #800: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #801: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #802: (@68[1:4] += @30) */
  for (rr=w68+1, ss=w30; rr!=w68+4; rr+=1) *rr += *ss++;
  /* #803: @62 = (@0*@68) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #804: @68 = (@19*@68) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #805: @62 = (@62-@68) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #806: {@60, @55, @74, @75} = vertsplit(@62) */
  w60 = w62[0];
  w55 = w62[1];
  w74 = w62[2];
  w75 = w62[3];
  /* #807: @73 = (@9*@75) */
  w73  = (w9*w75);
  /* #808: @76 = (@8*@74) */
  w76  = (w8*w74);
  /* #809: @73 = (@73+@76) */
  w73 += w76;
  /* #810: @76 = (@7*@55) */
  w76  = (w7*w55);
  /* #811: @73 = (@73+@76) */
  w73 += w76;
  /* #812: @76 = (@6*@60) */
  w76  = (w6*w60);
  /* #813: @73 = (@73+@76) */
  w73 += w76;
  /* #814: @76 = (@8*@75) */
  w76  = (w8*w75);
  /* #815: @49 = (@9*@74) */
  w49  = (w9*w74);
  /* #816: @76 = (@76-@49) */
  w76 -= w49;
  /* #817: @49 = (@6*@55) */
  w49  = (w6*w55);
  /* #818: @76 = (@76+@49) */
  w76 += w49;
  /* #819: @49 = (@7*@60) */
  w49  = (w7*w60);
  /* #820: @76 = (@76-@49) */
  w76 -= w49;
  /* #821: @49 = (@6*@74) */
  w49  = (w6*w74);
  /* #822: @77 = (@7*@75) */
  w77  = (w7*w75);
  /* #823: @49 = (@49-@77) */
  w49 -= w77;
  /* #824: @77 = (@9*@55) */
  w77  = (w9*w55);
  /* #825: @49 = (@49+@77) */
  w49 += w77;
  /* #826: @77 = (@8*@60) */
  w77  = (w8*w60);
  /* #827: @49 = (@49-@77) */
  w49 -= w77;
  /* #828: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #829: @74 = (@7*@74) */
  w74  = (w7*w74);
  /* #830: @75 = (@75+@74) */
  w75 += w74;
  /* #831: @55 = (@8*@55) */
  w55  = (w8*w55);
  /* #832: @75 = (@75-@55) */
  w75 -= w55;
  /* #833: @60 = (@9*@60) */
  w60  = (w9*w60);
  /* #834: @75 = (@75-@60) */
  w75 -= w60;
  /* #835: @62 = vertcat(@73, @76, @49, @75) */
  rr=w62;
  *rr++ = w73;
  *rr++ = w76;
  *rr++ = w49;
  *rr++ = w75;
  /* #836: @73 = dot(@35, @62) */
  w73 = casadi_dot(4, w35, w62);
  /* #837: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #838: @68 = (@36*@20) */
  for (i=0, rr=w68, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #839: @67 = (@67-@68) */
  for (i=0, rr=w67, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #840: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #841: @76 = dot(@67, @48) */
  w76 = casadi_dot(4, w67, w48);
  /* #842: @73 = (@73+@76) */
  w73 += w76;
  /* #843: @73 = (@73/@10) */
  w73 /= w10;
  /* #844: @76 = (@72*@20) */
  w76  = (w72*w20);
  /* #845: @73 = (@73-@76) */
  w73 -= w76;
  /* #846: @67 = (@34*@73) */
  for (i=0, rr=w67, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w73);
  /* #847: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #848: @68 = dense(@57) */
  casadi_densify((&w57), casadi_s12, w68, 0);
  /* #849: @67 = (@67+@68) */
  for (i=0, rr=w67, cs=w68; i<4; ++i) (*rr++) += (*cs++);
  /* #850: (@29[6:10] += @67) */
  for (rr=w29+6, ss=w67; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #851: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #852: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s13, 0);
  /* #853: @73 = @50[0] */
  for (rr=(&w73), ss=(&w50)+0; ss!=(&w50)+1; ss+=1) *rr++ = *ss;
  /* #854: @73 = (-@73) */
  w73 = (- w73 );
  /* #855: @50 = dot(@57, @73) */
  w50 = casadi_dot(1, (&w57), (&w73));
  /* #856: @1 = (@26*@50) */
  for (i=0, rr=w1, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w50);
  /* #857: @2 = @1' */
  casadi_copy(w1, 3, w2);
  /* #858: @30 = mac(@2,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #859: @30 = @30' */
  /* #860: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #861: @1 = @1' */
  /* #862: @2 = mac(@1,@52,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #863: @2 = @2' */
  /* #864: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #865: @50 = dot(@26, @30) */
  w50 = casadi_dot(3, w26, w30);
  /* #866: @26 = (@26*@50) */
  for (i=0, rr=w26; i<3; ++i) (*rr++) *= w50;
  /* #867: @30 = zeros(3x1) */
  casadi_clear(w30, 3);
  /* #868: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #869: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #870: @1 = mac(@3,@73,@1) */
  casadi_mtimes(w3, casadi_s4, (&w73), casadi_s13, w1, casadi_s3, w, 0);
  /* #871: @46 = @1' */
  casadi_copy(w1, 3, w46);
  /* #872: @2 = mac(@46,@28,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #873: @2 = @2' */
  /* #874: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #875: @1 = @1' */
  /* #876: @46 = mac(@1,@54,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #877: @46 = @46' */
  /* #878: @2 = (@2+@46) */
  for (i=0, rr=w2, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #879: @30 = mac(@53,@2,@30) */
  for (i=0, rr=w30; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w53+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #880: @26 = (@26+@30) */
  for (i=0, rr=w26, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #881: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (- *cs++ );
  /* #882: (@29[:3] += @26) */
  for (rr=w29+0, ss=w26; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #883: {@73, @50, @57, @76, @49, @75, @60, @55, @74, @77, @78, @81, @21} = vertsplit(@29) */
  w73 = w29[0];
  w50 = w29[1];
  w57 = w29[2];
  w76 = w29[3];
  w49 = w29[4];
  w75 = w29[5];
  w60 = w29[6];
  w55 = w29[7];
  w74 = w29[8];
  w77 = w29[9];
  w78 = w29[10];
  w81 = w29[11];
  w21 = w29[12];
  /* #884: @62 = (@62/@10) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w10;
  /* #885: @67 = (@42*@20) */
  for (i=0, rr=w67, cr=w42; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #886: @62 = (@62-@67) */
  for (i=0, rr=w62, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #887: {@20, @79, @80, @59} = vertsplit(@62) */
  w20 = w62[0];
  w79 = w62[1];
  w80 = w62[2];
  w59 = w62[3];
  /* #888: @20 = (@20+@60) */
  w20 += w60;
  /* #889: @55 = (@55-@79) */
  w55 -= w79;
  /* #890: @74 = (@74-@80) */
  w74 -= w80;
  /* #891: @77 = (@77-@59) */
  w77 -= w59;
  /* #892: @29 = vertcat(@73, @50, @57, @76, @49, @75, @20, @55, @74, @77, @78, @81, @21) */
  rr=w29;
  *rr++ = w73;
  *rr++ = w50;
  *rr++ = w57;
  *rr++ = w76;
  *rr++ = w49;
  *rr++ = w75;
  *rr++ = w20;
  *rr++ = w55;
  *rr++ = w74;
  *rr++ = w77;
  *rr++ = w78;
  *rr++ = w81;
  *rr++ = w21;
  /* #893: @82 = @29[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w29; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #894: (@61[6, 7, 8, 17, 18, 19, 20] = @82) */
  for (cii=casadi_s14, rr=w61, ss=w82; cii!=casadi_s14+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #895: @82 = @29[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s5, rr=w82, ss=w29; cii!=casadi_s5+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #896: (@61[2, 5, 8, 11, 15, 19, 23] = @82) */
  for (cii=casadi_s15, rr=w61, ss=w82; cii!=casadi_s15+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #897: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #898: @62 = zeros(4x1) */
  casadi_clear(w62, 4);
  /* #899: @64 = 00 */
  /* #900: @65 = 00 */
  /* #901: @66 = 00 */
  /* #902: @73 = ones(13x1,1nz) */
  w73 = 1.;
  /* #903: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @50, NULL, NULL, NULL} = vertsplit(@73) */
  w50 = w73;
  /* #904: @73 = (-@50) */
  w73 = (- w50 );
  /* #905: @57 = vertcat(@64, @65, @66, @73) */
  rr=(&w57);
  *rr++ = w73;
  /* #906: @57 = (@57/@10) */
  w57 /= w10;
  /* #907: @67 = dense(@57) */
  casadi_densify((&w57), casadi_s16, w67, 0);
  /* #908: @57 = project(@34) */
  casadi_sparsify(w34, (&w57), casadi_s16, 0);
  /* #909: @73 = @50[0] */
  for (rr=(&w73), ss=(&w50)+0; ss!=(&w50)+1; ss+=1) *rr++ = *ss;
  /* #910: @50 = dot(@57, @73) */
  w50 = casadi_dot(1, (&w57), (&w73));
  /* #911: @50 = (@50/@10) */
  w50 /= w10;
  /* #912: @33 = (@33*@50) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) *= w50;
  /* #913: @67 = (@67-@33) */
  for (i=0, rr=w67, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #914: {@57, @76, @49, @75} = vertsplit(@67) */
  w57 = w67[0];
  w76 = w67[1];
  w49 = w67[2];
  w75 = w67[3];
  /* #915: @20 = (@6*@57) */
  w20  = (w6*w57);
  /* #916: @55 = (@7*@76) */
  w55  = (w7*w76);
  /* #917: @20 = (@20-@55) */
  w20 -= w55;
  /* #918: @55 = (@8*@49) */
  w55  = (w8*w49);
  /* #919: @20 = (@20-@55) */
  w20 -= w55;
  /* #920: @55 = (@9*@75) */
  w55  = (w9*w75);
  /* #921: @20 = (@20-@55) */
  w20 -= w55;
  /* #922: @55 = (@7*@57) */
  w55  = (w7*w57);
  /* #923: @74 = (@6*@76) */
  w74  = (w6*w76);
  /* #924: @55 = (@55+@74) */
  w55 += w74;
  /* #925: @74 = (@9*@49) */
  w74  = (w9*w49);
  /* #926: @55 = (@55+@74) */
  w55 += w74;
  /* #927: @74 = (@8*@75) */
  w74  = (w8*w75);
  /* #928: @55 = (@55-@74) */
  w55 -= w74;
  /* #929: @74 = (@8*@57) */
  w74  = (w8*w57);
  /* #930: @77 = (@9*@76) */
  w77  = (w9*w76);
  /* #931: @74 = (@74-@77) */
  w74 -= w77;
  /* #932: @77 = (@6*@49) */
  w77  = (w6*w49);
  /* #933: @74 = (@74+@77) */
  w74 += w77;
  /* #934: @77 = (@7*@75) */
  w77  = (w7*w75);
  /* #935: @74 = (@74+@77) */
  w74 += w77;
  /* #936: @57 = (@9*@57) */
  w57  = (w9*w57);
  /* #937: @76 = (@8*@76) */
  w76  = (w8*w76);
  /* #938: @57 = (@57+@76) */
  w57 += w76;
  /* #939: @49 = (@7*@49) */
  w49  = (w7*w49);
  /* #940: @57 = (@57-@49) */
  w57 -= w49;
  /* #941: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #942: @57 = (@57+@75) */
  w57 += w75;
  /* #943: @33 = vertcat(@20, @55, @74, @57) */
  rr=w33;
  *rr++ = w20;
  *rr++ = w55;
  *rr++ = w74;
  *rr++ = w57;
  /* #944: @68 = (@14*@33) */
  for (i=0, rr=w68, cs=w33; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #945: @33 = (@15*@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #946: @68 = (@68-@33) */
  for (i=0, rr=w68, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #947: @26 = @68[1:4] */
  for (rr=w26, ss=w68+1; ss!=w68+4; ss+=1) *rr++ = *ss;
  /* #948: @15 = dot(@37, @26) */
  w15 = casadi_dot(3, w37, w26);
  /* #949: @15 = (@15/@16) */
  w15 /= w16;
  /* #950: @14 = (@15/@4) */
  w14  = (w15/w4);
  /* #951: @58 = (@58*@15) */
  w58 *= w15;
  /* #952: @20 = @68[0] */
  for (rr=(&w20), ss=w68+0; ss!=w68+1; ss+=1) *rr++ = *ss;
  /* #953: @56 = (@56*@20) */
  w56 *= w20;
  /* #954: @58 = (@58+@56) */
  w58 += w56;
  /* #955: @22 = (@22*@58) */
  w22 *= w58;
  /* #956: @14 = (@14-@22) */
  w14 -= w22;
  /* #957: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #958: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #959: @2 = (2.*@26) */
  for (i=0, rr=w2, cs=w26; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #960: @46 = (@11*@2) */
  for (i=0, rr=w46, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #961: @17 = (@17*@15) */
  w17 *= w15;
  /* #962: @51 = (@51*@20) */
  w51 *= w20;
  /* #963: @17 = (@17-@51) */
  w17 -= w51;
  /* #964: @1 = (@38*@17) */
  for (i=0, rr=w1, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #965: @46 = (@46+@1) */
  for (i=0, rr=w46, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #966: @46 = (@46/@16) */
  for (i=0, rr=w46; i<3; ++i) (*rr++) /= w16;
  /* #967: @39 = (@39*@15) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) *= w15;
  /* #968: @46 = (@46-@39) */
  for (i=0, rr=w46, cs=w39; i<3; ++i) (*rr++) -= (*cs++);
  /* #969: @39 = @46' */
  casadi_copy(w46, 3, w39);
  /* #970: @30 = mac(@39,@41,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #971: @30 = @30' */
  /* #972: @39 = zeros(1x3) */
  casadi_clear(w39, 3);
  /* #973: @1 = @46' */
  casadi_copy(w46, 3, w1);
  /* #974: @39 = mac(@1,@44,@39) */
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w44+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #975: @39 = @39' */
  /* #976: @30 = (@30+@39) */
  for (i=0, rr=w30, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #977: @39 = (@30/@16) */
  for (i=0, rr=w39, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #978: @47 = (@47*@15) */
  for (i=0, rr=w47; i<3; ++i) (*rr++) *= w15;
  /* #979: @39 = (@39-@47) */
  for (i=0, rr=w39, cs=w47; i<3; ++i) (*rr++) -= (*cs++);
  /* #980: @51 = dot(@38, @39) */
  w51 = casadi_dot(3, w38, w39);
  /* #981: @22 = dot(@2, @40) */
  w22 = casadi_dot(3, w2, w40);
  /* #982: @51 = (@51+@22) */
  w51 += w22;
  /* #983: @5 = (@5*@51) */
  w5 *= w51;
  /* #984: @14 = (@14+@5) */
  w14 += w5;
  /* #985: @14 = (-@14) */
  w14 = (- w14 );
  /* #986: (@62[0] += @14) */
  for (rr=w62+0, ss=(&w14); rr!=w62+1; rr+=1) *rr += *ss++;
  /* #987: @14 = dot(@45, @30) */
  w14 = casadi_dot(3, w45, w30);
  /* #988: @46 = (@46/@16) */
  for (i=0, rr=w46; i<3; ++i) (*rr++) /= w16;
  /* #989: @43 = (@43*@15) */
  for (i=0, rr=w43; i<3; ++i) (*rr++) *= w15;
  /* #990: @46 = (@46-@43) */
  for (i=0, rr=w46, cs=w43; i<3; ++i) (*rr++) -= (*cs++);
  /* #991: @46 = (-@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) *rr++ = (- *cs++ );
  /* #992: @5 = dot(@46, @31) */
  w5 = casadi_dot(3, w46, w31);
  /* #993: @14 = (@14+@5) */
  w14 += w5;
  /* #994: @20 = (@20/@4) */
  w20 /= w4;
  /* #995: @71 = (@71*@58) */
  w71 *= w58;
  /* #996: @20 = (@20-@71) */
  w20 -= w71;
  /* #997: @13 = (@13*@20) */
  w13 *= w20;
  /* #998: @18 = (@18*@51) */
  w18 *= w51;
  /* #999: @13 = (@13+@18) */
  w13 += w18;
  /* #1000: @14 = (@14+@13) */
  w14 += w13;
  /* #1001: @14 = (@14/@16) */
  w14 /= w16;
  /* #1002: @23 = (@23*@15) */
  w23 *= w15;
  /* #1003: @14 = (@14-@23) */
  w14 -= w23;
  /* #1004: @37 = (@37*@14) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w14;
  /* #1005: @26 = (@12*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #1006: @37 = (@37+@26) */
  for (i=0, rr=w37, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #1007: @40 = (@40*@17) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w17;
  /* #1008: @39 = (@11*@39) */
  for (i=0, rr=w39, cs=w39; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #1009: @40 = (@40+@39) */
  for (i=0, rr=w40, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #1010: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1011: @37 = (@37+@40) */
  for (i=0, rr=w37, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #1012: (@62[1:4] += @37) */
  for (rr=w62+1, ss=w37; rr!=w62+4; rr+=1) *rr += *ss++;
  /* #1013: @68 = (@0*@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #1014: @62 = (@19*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #1015: @68 = (@68-@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #1016: {@19, @0, @11, @17} = vertsplit(@68) */
  w19 = w68[0];
  w0 = w68[1];
  w11 = w68[2];
  w17 = w68[3];
  /* #1017: @12 = (@9*@17) */
  w12  = (w9*w17);
  /* #1018: @14 = (@8*@11) */
  w14  = (w8*w11);
  /* #1019: @12 = (@12+@14) */
  w12 += w14;
  /* #1020: @14 = (@7*@0) */
  w14  = (w7*w0);
  /* #1021: @12 = (@12+@14) */
  w12 += w14;
  /* #1022: @14 = (@6*@19) */
  w14  = (w6*w19);
  /* #1023: @12 = (@12+@14) */
  w12 += w14;
  /* #1024: @14 = (@8*@17) */
  w14  = (w8*w17);
  /* #1025: @23 = (@9*@11) */
  w23  = (w9*w11);
  /* #1026: @14 = (@14-@23) */
  w14 -= w23;
  /* #1027: @23 = (@6*@0) */
  w23  = (w6*w0);
  /* #1028: @14 = (@14+@23) */
  w14 += w23;
  /* #1029: @23 = (@7*@19) */
  w23  = (w7*w19);
  /* #1030: @14 = (@14-@23) */
  w14 -= w23;
  /* #1031: @23 = (@6*@11) */
  w23  = (w6*w11);
  /* #1032: @15 = (@7*@17) */
  w15  = (w7*w17);
  /* #1033: @23 = (@23-@15) */
  w23 -= w15;
  /* #1034: @15 = (@9*@0) */
  w15  = (w9*w0);
  /* #1035: @23 = (@23+@15) */
  w23 += w15;
  /* #1036: @15 = (@8*@19) */
  w15  = (w8*w19);
  /* #1037: @23 = (@23-@15) */
  w23 -= w15;
  /* #1038: @6 = (@6*@17) */
  w6 *= w17;
  /* #1039: @7 = (@7*@11) */
  w7 *= w11;
  /* #1040: @6 = (@6+@7) */
  w6 += w7;
  /* #1041: @8 = (@8*@0) */
  w8 *= w0;
  /* #1042: @6 = (@6-@8) */
  w6 -= w8;
  /* #1043: @9 = (@9*@19) */
  w9 *= w19;
  /* #1044: @6 = (@6-@9) */
  w6 -= w9;
  /* #1045: @68 = vertcat(@12, @14, @23, @6) */
  rr=w68;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w23;
  *rr++ = w6;
  /* #1046: @12 = dot(@35, @68) */
  w12 = casadi_dot(4, w35, w68);
  /* #1047: @67 = (@67/@10) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w10;
  /* #1048: @36 = (@36*@50) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) *= w50;
  /* #1049: @67 = (@67-@36) */
  for (i=0, rr=w67, cs=w36; i<4; ++i) (*rr++) -= (*cs++);
  /* #1050: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #1051: @14 = dot(@67, @48) */
  w14 = casadi_dot(4, w67, w48);
  /* #1052: @12 = (@12+@14) */
  w12 += w14;
  /* #1053: @12 = (@12/@10) */
  w12 /= w10;
  /* #1054: @72 = (@72*@50) */
  w72 *= w50;
  /* #1055: @12 = (@12-@72) */
  w12 -= w72;
  /* #1056: @34 = (@34*@12) */
  for (i=0, rr=w34; i<4; ++i) (*rr++) *= w12;
  /* #1057: @24 = (@24*@73) */
  w24 *= w73;
  /* #1058: @67 = dense(@24) */
  casadi_densify((&w24), casadi_s16, w67, 0);
  /* #1059: @34 = (@34+@67) */
  for (i=0, rr=w34, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #1060: (@29[6:10] += @34) */
  for (rr=w29+6, ss=w34; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #1061: {@24, @73, @12, @72, @14, @23, @6, @9, @19, @8, @0, @7, @11} = vertsplit(@29) */
  w24 = w29[0];
  w73 = w29[1];
  w12 = w29[2];
  w72 = w29[3];
  w14 = w29[4];
  w23 = w29[5];
  w6 = w29[6];
  w9 = w29[7];
  w19 = w29[8];
  w8 = w29[9];
  w0 = w29[10];
  w7 = w29[11];
  w11 = w29[12];
  /* #1062: @68 = (@68/@10) */
  for (i=0, rr=w68; i<4; ++i) (*rr++) /= w10;
  /* #1063: @42 = (@42*@50) */
  for (i=0, rr=w42; i<4; ++i) (*rr++) *= w50;
  /* #1064: @68 = (@68-@42) */
  for (i=0, rr=w68, cs=w42; i<4; ++i) (*rr++) -= (*cs++);
  /* #1065: {@50, @10, @17, @15} = vertsplit(@68) */
  w50 = w68[0];
  w10 = w68[1];
  w17 = w68[2];
  w15 = w68[3];
  /* #1066: @50 = (@50+@6) */
  w50 += w6;
  /* #1067: @9 = (@9-@10) */
  w9 -= w10;
  /* #1068: @19 = (@19-@17) */
  w19 -= w17;
  /* #1069: @8 = (@8-@15) */
  w8 -= w15;
  /* #1070: @29 = vertcat(@24, @73, @12, @72, @14, @23, @50, @9, @19, @8, @0, @7, @11) */
  rr=w29;
  *rr++ = w24;
  *rr++ = w73;
  *rr++ = w12;
  *rr++ = w72;
  *rr++ = w14;
  *rr++ = w23;
  *rr++ = w50;
  *rr++ = w9;
  *rr++ = w19;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w7;
  *rr++ = w11;
  /* #1071: @68 = @29[6:10] */
  for (rr=w68, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #1072: (@61[21:25] = @68) */
  for (rr=w61+21, ss=w68; rr!=w61+25; rr+=1) *rr = *ss++;
  /* #1073: @68 = @29[6:10] */
  for (rr=w68, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #1074: (@61[12:28:4] = @68) */
  for (rr=w61+12, ss=w68; rr!=w61+28; rr+=4) *rr = *ss++;
  /* #1075: @84 = @61' */
  casadi_trans(w61,casadi_s17, w84, casadi_s17, iw);
  /* #1076: output[2][0] = @84 */
  casadi_copy(w84, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s19;
    case 3: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s21;
    case 1: return casadi_s18;
    case 2: return casadi_s17;
    case 3: return casadi_s19;
    case 4: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 302;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
