/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s6[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s7[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[11] = {0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13};
static const casadi_int casadi_s9[11] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28};
static const casadi_int casadi_s10[11] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37};
static const casadi_int casadi_s11[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s12[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s13[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s14[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s15[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s17[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s18[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s19[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s20[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s21[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s22[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s23[61] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 29, 33, 37, 41, 41, 41, 41, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13};
static const casadi_int casadi_s24[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s25[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s26[3] = {0, 0, 0};
static const casadi_int casadi_s27[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s28[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s29[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s30[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {2.0000000000000000e-03, 0., 0., 0., 0., 200., 0., 0., 0., 0., 200., 0., 0., 0., 0., 200.};

/* Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[4],i2[],i3[20])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+7, *w3=w+10, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, *w25=w+40, *w26=w+60, *w27=w+63, *w28=w+66, *w29=w+75, *w30=w+88, *w31=w+91, *w32=w+94, *w33=w+103, *w34=w+107, *w35=w+111, *w36=w+115, *w37=w+119, *w38=w+122, *w39=w+125, *w40=w+128, *w41=w+131, *w42=w+140, *w43=w+144, *w44=w+160, *w45=w+176, *w46=w+179, *w47=w+188, *w48=w+191, *w49=w+194, *w50=w+197, w51, w52, w53, *w54=w+204, *w55=w+213, *w56=w+222, w57, w58, w59, w60, w61, w62, *w63=w+237, *w64=w+278, *w65=w+282, *w69=w+291, *w70=w+295, w71, w72, *w73=w+301, w74, w75, *w76=w+307, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, *w88=w+321, *w89=w+338, *w90=w+349, *w91=w+351, *w92=w+359;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = input[3][12] */
  w17 = arg[3] ? arg[3][12] : 0;
  /* #18: @18 = input[3][13] */
  w18 = arg[3] ? arg[3][13] : 0;
  /* #19: @19 = input[3][14] */
  w19 = arg[3] ? arg[3][14] : 0;
  /* #20: @20 = input[3][15] */
  w20 = arg[3] ? arg[3][15] : 0;
  /* #21: @21 = input[3][16] */
  w21 = arg[3] ? arg[3][16] : 0;
  /* #22: @22 = input[3][17] */
  w22 = arg[3] ? arg[3][17] : 0;
  /* #23: @23 = input[3][18] */
  w23 = arg[3] ? arg[3][18] : 0;
  /* #24: @24 = input[3][19] */
  w24 = arg[3] ? arg[3][19] : 0;
  /* #25: @25 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24) */
  rr=w25;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  /* #26: @26 = @25[3:6] */
  for (rr=w26, ss=w25+3; ss!=w25+6; ss+=1) *rr++ = *ss;
  /* #27: @27 = @26' */
  casadi_copy(w26, 3, w27);
  /* #28: @4 = mac(@27,@26,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #29: @28 = @4[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w28, ss=(&w4); cii!=casadi_s0+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #30: @3 = (@3-@28) */
  for (i=0, rr=w3, cs=w28; i<9; ++i) (*rr++) -= (*cs++);
  /* #31: @27 = @25[:3] */
  for (rr=w27, ss=w25+0; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #32: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #33: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #34: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #35: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #36: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #37: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #38: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #39: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #40: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #41: @13 = input[0][9] */
  w13 = arg[0] ? arg[0][9] : 0;
  /* #42: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #43: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #44: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #45: @29 = vertcat(@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w29;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #46: @30 = @29[:3] */
  for (rr=w30, ss=w29+0; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #47: @27 = (@27-@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #48: @2 = mac(@3,@27,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #49: @30 = @2' */
  casadi_copy(w2, 3, w30);
  /* #50: @28 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w28);
  /* #51: @1 = mac(@30,@28,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #52: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #53: @4 = 0 */
  w4 = 0.;
  /* #54: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #55: @5 = dot(@26, @27) */
  w5 = casadi_dot(3, w26, w27);
  /* #56: @27 = (@5*@26) */
  for (i=0, rr=w27, cs=w26; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #57: @31 = @27' */
  casadi_copy(w27, 3, w31);
  /* #58: @32 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w32);
  /* #59: @30 = mac(@31,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #60: @4 = mac(@30,@27,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #61: @0 = (@0+@4) */
  w0 += w4;
  /* #62: @4 = 0 */
  w4 = 0.;
  /* #63: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #64: @11 = (-@11) */
  w11 = (- w11 );
  /* #65: @12 = (-@12) */
  w12 = (- w12 );
  /* #66: @13 = (-@13) */
  w13 = (- w13 );
  /* #67: @33 = vertcat(@10, @11, @12, @13) */
  rr=w33;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #68: @34 = @29[6:10] */
  for (rr=w34, ss=w29+6; ss!=w29+10; ss+=1) *rr++ = *ss;
  /* #69: @10 = ||@34||_F */
  w10 = sqrt(casadi_dot(4, w34, w34));
  /* #70: @33 = (@33/@10) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w10;
  /* #71: {@11, @12, @13, @5} = vertsplit(@33) */
  w11 = w33[0];
  w12 = w33[1];
  w13 = w33[2];
  w5 = w33[3];
  /* #72: @35 = @25[6:10] */
  for (rr=w35, ss=w25+6; ss!=w25+10; ss+=1) *rr++ = *ss;
  /* #73: {@6, @7, @8, @9} = vertsplit(@35) */
  w6 = w35[0];
  w7 = w35[1];
  w8 = w35[2];
  w9 = w35[3];
  /* #74: @14 = (@11*@6) */
  w14  = (w11*w6);
  /* #75: @15 = (@12*@7) */
  w15  = (w12*w7);
  /* #76: @14 = (@14-@15) */
  w14 -= w15;
  /* #77: @15 = (@13*@8) */
  w15  = (w13*w8);
  /* #78: @14 = (@14-@15) */
  w14 -= w15;
  /* #79: @15 = (@5*@9) */
  w15  = (w5*w9);
  /* #80: @14 = (@14-@15) */
  w14 -= w15;
  /* #81: @15 = 0 */
  w15 = 0.;
  /* #82: @15 = (@14<@15) */
  w15  = (w14<w15);
  /* #83: @16 = (@11*@7) */
  w16  = (w11*w7);
  /* #84: @17 = (@12*@6) */
  w17  = (w12*w6);
  /* #85: @16 = (@16+@17) */
  w16 += w17;
  /* #86: @17 = (@13*@9) */
  w17  = (w13*w9);
  /* #87: @16 = (@16+@17) */
  w16 += w17;
  /* #88: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #89: @16 = (@16-@17) */
  w16 -= w17;
  /* #90: @17 = (@11*@8) */
  w17  = (w11*w8);
  /* #91: @18 = (@12*@9) */
  w18  = (w12*w9);
  /* #92: @17 = (@17-@18) */
  w17 -= w18;
  /* #93: @18 = (@13*@6) */
  w18  = (w13*w6);
  /* #94: @17 = (@17+@18) */
  w17 += w18;
  /* #95: @18 = (@5*@7) */
  w18  = (w5*w7);
  /* #96: @17 = (@17+@18) */
  w17 += w18;
  /* #97: @11 = (@11*@9) */
  w11 *= w9;
  /* #98: @12 = (@12*@8) */
  w12 *= w8;
  /* #99: @11 = (@11+@12) */
  w11 += w12;
  /* #100: @13 = (@13*@7) */
  w13 *= w7;
  /* #101: @11 = (@11-@13) */
  w11 -= w13;
  /* #102: @5 = (@5*@6) */
  w5 *= w6;
  /* #103: @11 = (@11+@5) */
  w11 += w5;
  /* #104: @35 = vertcat(@14, @16, @17, @11) */
  rr=w35;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w11;
  /* #105: @36 = (-@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) *rr++ = (- *cs++ );
  /* #106: @36 = (@15?@36:0) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) (*rr++)  = (w15?(*cs++):0);
  /* #107: @14 = (!@15) */
  w14 = (! w15 );
  /* #108: @35 = (@14?@35:0) */
  for (i=0, rr=w35, cs=w35; i<4; ++i) (*rr++)  = (w14?(*cs++):0);
  /* #109: @36 = (@36+@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) (*rr++) += (*cs++);
  /* #110: @37 = @36[1:4] */
  for (rr=w37, ss=w36+1; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #111: @38 = (2.*@37) */
  for (i=0, rr=w38, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #112: @16 = ||@37||_F */
  w16 = sqrt(casadi_dot(3, w37, w37));
  /* #113: @17 = @36[0] */
  for (rr=(&w17), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  /* #114: @11 = atan2(@16,@17) */
  w11  = atan2(w16,w17);
  /* #115: @39 = (@38*@11) */
  for (i=0, rr=w39, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w11);
  /* #116: @39 = (@39/@16) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) /= w16;
  /* #117: @40 = @39' */
  casadi_copy(w39, 3, w40);
  /* #118: @41 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w41);
  /* #119: @31 = mac(@40,@41,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #120: @4 = mac(@31,@39,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #121: @0 = (@0+@4) */
  w0 += w4;
  /* #122: @4 = 0 */
  w4 = 0.;
  /* #123: @36 = zeros(1x4) */
  casadi_clear(w36, 4);
  /* #124: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #125: @13 = input[1][1] */
  w13 = arg[1] ? arg[1][1] : 0;
  /* #126: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #127: @18 = input[1][3] */
  w18 = arg[1] ? arg[1][3] : 0;
  /* #128: @35 = vertcat(@5, @13, @12, @18) */
  rr=w35;
  *rr++ = w5;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w18;
  /* #129: @42 = @35' */
  casadi_copy(w35, 4, w42);
  /* #130: @43 = 
  [[0.002, 0, 0, 0], 
   [0, 200, 0, 0], 
   [0, 0, 200, 0], 
   [0, 0, 0, 200]] */
  casadi_copy(casadi_c1, 16, w43);
  /* #131: @36 = mac(@42,@43,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w43+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #132: @4 = mac(@36,@35,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w35+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #133: @0 = (@0+@4) */
  w0 += w4;
  /* #134: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #135: @40 = @29[3:6] */
  for (rr=w40, ss=w29+3; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #136: @5 = dot(@26, @40) */
  w5 = casadi_dot(3, w26, w40);
  /* #137: @4 = (@4*@5) */
  w4 *= w5;
  /* #138: @0 = (@0-@4) */
  w0 -= w4;
  /* #139: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #140: @36 = @36' */
  /* #141: @42 = zeros(1x4) */
  casadi_clear(w42, 4);
  /* #142: @35 = @35' */
  /* #143: @44 = @43' */
  for (i=0, rr=w44, cs=w43; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #144: @42 = mac(@35,@44,@42) */
  for (i=0, rr=w42; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w44+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #145: @42 = @42' */
  /* #146: @36 = (@36+@42) */
  for (i=0, rr=w36, cs=w42; i<4; ++i) (*rr++) += (*cs++);
  /* #147: {@0, @4, @5, @13} = vertsplit(@36) */
  w0 = w36[0];
  w4 = w36[1];
  w5 = w36[2];
  w13 = w36[3];
  /* #148: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #149: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #150: output[1][2] = @5 */
  if (res[1]) res[1][2] = w5;
  /* #151: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #152: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #153: @13 = -0.05 */
  w13 = -5.0000000000000003e-02;
  /* #154: @40 = (@13*@26) */
  for (i=0, rr=w40, cs=w26; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #155: (@29[3:6] += @40) */
  for (rr=w29+3, ss=w40; rr!=w29+6; rr+=1) *rr += *ss++;
  /* #156: @36 = (@33/@10) */
  for (i=0, rr=w36, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #157: @42 = (-@36) */
  for (i=0, rr=w42, cs=w36; i<4; ++i) *rr++ = (- *cs++ );
  /* #158: @13 = 1 */
  w13 = 1.;
  /* #159: @13 = (@14?@13:0) */
  w13  = (w14?w13:0);
  /* #160: @35 = zeros(4x1) */
  casadi_clear(w35, 4);
  /* #161: @5 = sq(@16) */
  w5 = casadi_sq( w16 );
  /* #162: @4 = sq(@17) */
  w4 = casadi_sq( w17 );
  /* #163: @5 = (@5+@4) */
  w5 += w4;
  /* #164: @4 = (@16/@5) */
  w4  = (w16/w5);
  /* #165: @31 = @31' */
  /* #166: @40 = zeros(1x3) */
  casadi_clear(w40, 3);
  /* #167: @45 = @39' */
  casadi_copy(w39, 3, w45);
  /* #168: @46 = @41' */
  for (i=0, rr=w46, cs=w41; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #169: @40 = mac(@45,@46,@40) */
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w45+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #170: @40 = @40' */
  /* #171: @31 = (@31+@40) */
  for (i=0, rr=w31, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #172: @40 = (@31/@16) */
  for (i=0, rr=w40, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #173: @0 = dot(@38, @40) */
  w0 = casadi_dot(3, w38, w40);
  /* #174: @12 = (@4*@0) */
  w12  = (w4*w0);
  /* #175: @12 = (-@12) */
  w12 = (- w12 );
  /* #176: (@35[0] += @12) */
  for (rr=w35+0, ss=(&w12); rr!=w35+1; rr+=1) *rr += *ss++;
  /* #177: @45 = (@39/@16) */
  for (i=0, rr=w45, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #178: @47 = (-@45) */
  for (i=0, rr=w47, cs=w45; i<3; ++i) *rr++ = (- *cs++ );
  /* #179: @12 = dot(@47, @31) */
  w12 = casadi_dot(3, w47, w31);
  /* #180: @18 = (@17/@5) */
  w18  = (w17/w5);
  /* #181: @19 = (@18*@0) */
  w19  = (w18*w0);
  /* #182: @12 = (@12+@19) */
  w12 += w19;
  /* #183: @12 = (@12/@16) */
  w12 /= w16;
  /* #184: @48 = (@12*@37) */
  for (i=0, rr=w48, cs=w37; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #185: @49 = (@11*@40) */
  for (i=0, rr=w49, cs=w40; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #186: @49 = (2.*@49) */
  for (i=0, rr=w49, cs=w49; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #187: @48 = (@48+@49) */
  for (i=0, rr=w48, cs=w49; i<3; ++i) (*rr++) += (*cs++);
  /* #188: (@35[1:4] += @48) */
  for (rr=w35+1, ss=w48; rr!=w35+4; rr+=1) *rr += *ss++;
  /* #189: @50 = (@13*@35) */
  for (i=0, rr=w50, cs=w35; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #190: @19 = 1 */
  w19 = 1.;
  /* #191: @19 = (@15?@19:0) */
  w19  = (w15?w19:0);
  /* #192: @35 = (@19*@35) */
  for (i=0, rr=w35, cs=w35; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #193: @50 = (@50-@35) */
  for (i=0, rr=w50, cs=w35; i<4; ++i) (*rr++) -= (*cs++);
  /* #194: {@20, @21, @22, @23} = vertsplit(@50) */
  w20 = w50[0];
  w21 = w50[1];
  w22 = w50[2];
  w23 = w50[3];
  /* #195: @24 = (@9*@23) */
  w24  = (w9*w23);
  /* #196: @51 = (@8*@22) */
  w51  = (w8*w22);
  /* #197: @24 = (@24+@51) */
  w24 += w51;
  /* #198: @51 = (@7*@21) */
  w51  = (w7*w21);
  /* #199: @24 = (@24+@51) */
  w24 += w51;
  /* #200: @51 = (@6*@20) */
  w51  = (w6*w20);
  /* #201: @24 = (@24+@51) */
  w24 += w51;
  /* #202: @51 = (@8*@23) */
  w51  = (w8*w23);
  /* #203: @52 = (@9*@22) */
  w52  = (w9*w22);
  /* #204: @51 = (@51-@52) */
  w51 -= w52;
  /* #205: @52 = (@6*@21) */
  w52  = (w6*w21);
  /* #206: @51 = (@51+@52) */
  w51 += w52;
  /* #207: @52 = (@7*@20) */
  w52  = (w7*w20);
  /* #208: @51 = (@51-@52) */
  w51 -= w52;
  /* #209: @52 = (@6*@22) */
  w52  = (w6*w22);
  /* #210: @53 = (@7*@23) */
  w53  = (w7*w23);
  /* #211: @52 = (@52-@53) */
  w52 -= w53;
  /* #212: @53 = (@9*@21) */
  w53  = (w9*w21);
  /* #213: @52 = (@52+@53) */
  w52 += w53;
  /* #214: @53 = (@8*@20) */
  w53  = (w8*w20);
  /* #215: @52 = (@52-@53) */
  w52 -= w53;
  /* #216: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #217: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #218: @23 = (@23+@22) */
  w23 += w22;
  /* #219: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #220: @23 = (@23-@21) */
  w23 -= w21;
  /* #221: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #222: @23 = (@23-@20) */
  w23 -= w20;
  /* #223: @50 = vertcat(@24, @51, @52, @23) */
  rr=w50;
  *rr++ = w24;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w23;
  /* #224: @24 = dot(@42, @50) */
  w24 = casadi_dot(4, w42, w50);
  /* #225: @24 = (@24/@10) */
  w24 /= w10;
  /* #226: @35 = (@24*@34) */
  for (i=0, rr=w35, cs=w34; i<4; ++i) (*rr++)  = (w24*(*cs++));
  /* #227: (@29[6:10] += @35) */
  for (rr=w29+6, ss=w35; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #228: @30 = @30' */
  /* #229: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #230: @27 = @27' */
  /* #231: @54 = @32' */
  for (i=0, rr=w54, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #232: @48 = mac(@27,@54,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #233: @48 = @48' */
  /* #234: @30 = (@30+@48) */
  for (i=0, rr=w30, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #235: @51 = dot(@26, @30) */
  w51 = casadi_dot(3, w26, w30);
  /* #236: @30 = (@51*@26) */
  for (i=0, rr=w30, cs=w26; i<3; ++i) (*rr++)  = (w51*(*cs++));
  /* #237: @48 = zeros(3x1) */
  casadi_clear(w48, 3);
  /* #238: @55 = @3' */
  for (i=0, rr=w55, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #239: @1 = @1' */
  /* #240: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #241: @2 = @2' */
  /* #242: @56 = @28' */
  for (i=0, rr=w56, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: @27 = mac(@2,@56,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #244: @27 = @27' */
  /* #245: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #246: @48 = mac(@55,@1,@48) */
  for (i=0, rr=w48; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #247: @30 = (@30+@48) */
  for (i=0, rr=w30, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #248: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #249: (@29[:3] += @30) */
  for (rr=w29+0, ss=w30; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #250: {@51, @52, @23, @20, @21, @22, @53, @57, @58, @59, @60, @61, @62} = vertsplit(@29) */
  w51 = w29[0];
  w52 = w29[1];
  w23 = w29[2];
  w20 = w29[3];
  w21 = w29[4];
  w22 = w29[5];
  w53 = w29[6];
  w57 = w29[7];
  w58 = w29[8];
  w59 = w29[9];
  w60 = w29[10];
  w61 = w29[11];
  w62 = w29[12];
  /* #251: output[1][4] = @51 */
  if (res[1]) res[1][4] = w51;
  /* #252: output[1][5] = @52 */
  if (res[1]) res[1][5] = w52;
  /* #253: output[1][6] = @23 */
  if (res[1]) res[1][6] = w23;
  /* #254: output[1][7] = @20 */
  if (res[1]) res[1][7] = w20;
  /* #255: output[1][8] = @21 */
  if (res[1]) res[1][8] = w21;
  /* #256: output[1][9] = @22 */
  if (res[1]) res[1][9] = w22;
  /* #257: @35 = (@50/@10) */
  for (i=0, rr=w35, cr=w50; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #258: {@22, @21, @20, @23} = vertsplit(@35) */
  w22 = w35[0];
  w21 = w35[1];
  w20 = w35[2];
  w23 = w35[3];
  /* #259: @22 = (@22+@53) */
  w22 += w53;
  /* #260: output[1][10] = @22 */
  if (res[1]) res[1][10] = w22;
  /* #261: @57 = (@57-@21) */
  w57 -= w21;
  /* #262: output[1][11] = @57 */
  if (res[1]) res[1][11] = w57;
  /* #263: @58 = (@58-@20) */
  w58 -= w20;
  /* #264: output[1][12] = @58 */
  if (res[1]) res[1][12] = w58;
  /* #265: @59 = (@59-@23) */
  w59 -= w23;
  /* #266: output[1][13] = @59 */
  if (res[1]) res[1][13] = w59;
  /* #267: output[1][14] = @60 */
  if (res[1]) res[1][14] = w60;
  /* #268: output[1][15] = @61 */
  if (res[1]) res[1][15] = w61;
  /* #269: output[1][16] = @62 */
  if (res[1]) res[1][16] = w62;
  /* #270: @63 = zeros(17x17,41nz) */
  casadi_clear(w63, 41);
  /* #271: @64 = zeros(1x4) */
  casadi_clear(w64, 4);
  /* #272: @65 = ones(17x1,9nz) */
  casadi_fill(w65, 9, 1.);
  /* #273: {@62, NULL, NULL, NULL, @61, NULL, NULL, NULL, NULL, NULL, @60, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@65) */
  w62 = w65[0];
  w61 = w65[1];
  w60 = w65[5];
  /* #274: @66 = 00 */
  /* #275: @67 = 00 */
  /* #276: @68 = 00 */
  /* #277: @59 = vertcat(@62, @66, @67, @68) */
  rr=(&w59);
  *rr++ = w62;
  /* #278: @62 = @59' */
  casadi_copy((&w59), 1, (&w62));
  /* #279: @64 = mac(@62,@43,@64) */
  casadi_mtimes((&w62), casadi_s3, w43, casadi_s2, w64, casadi_s1, w, 0);
  /* #280: @64 = @64' */
  /* #281: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #282: @59 = @59' */
  /* #283: @69 = mac(@59,@44,@69) */
  casadi_mtimes((&w59), casadi_s3, w44, casadi_s2, w69, casadi_s1, w, 0);
  /* #284: @69 = @69' */
  /* #285: @64 = (@64+@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #286: {@59, @62, @23, @58} = vertsplit(@64) */
  w59 = w64[0];
  w62 = w64[1];
  w23 = w64[2];
  w58 = w64[3];
  /* #287: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #288: @64 = zeros(4x1) */
  casadi_clear(w64, 4);
  /* #289: @20 = 1 */
  w20 = 1.;
  /* #290: @14 = (@14?@20:0) */
  w14  = (w14?w20:0);
  /* #291: @66 = 00 */
  /* #292: @67 = 00 */
  /* #293: @68 = 00 */
  /* #294: @20 = vertcat(@60, @66, @67, @68) */
  rr=(&w20);
  *rr++ = w60;
  /* #295: @20 = (@20/@10) */
  w20 /= w10;
  /* #296: @69 = dense(@20) */
  casadi_densify((&w20), casadi_s4, w69, 0);
  /* #297: @33 = (@33/@10) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w10;
  /* #298: @20 = project(@34) */
  casadi_sparsify(w34, (&w20), casadi_s4, 0);
  /* #299: @57 = @60[0] */
  for (rr=(&w57), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #300: @60 = dot(@20, @57) */
  w60 = casadi_dot(1, (&w20), (&w57));
  /* #301: @60 = (@60/@10) */
  w60 /= w10;
  /* #302: @70 = (@33*@60) */
  for (i=0, rr=w70, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #303: @69 = (@69-@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #304: {@20, @21, @22, @53} = vertsplit(@69) */
  w20 = w69[0];
  w21 = w69[1];
  w22 = w69[2];
  w53 = w69[3];
  /* #305: @52 = (@6*@20) */
  w52  = (w6*w20);
  /* #306: @51 = (@7*@21) */
  w51  = (w7*w21);
  /* #307: @52 = (@52-@51) */
  w52 -= w51;
  /* #308: @51 = (@8*@22) */
  w51  = (w8*w22);
  /* #309: @52 = (@52-@51) */
  w52 -= w51;
  /* #310: @51 = (@9*@53) */
  w51  = (w9*w53);
  /* #311: @52 = (@52-@51) */
  w52 -= w51;
  /* #312: @51 = (@7*@20) */
  w51  = (w7*w20);
  /* #313: @71 = (@6*@21) */
  w71  = (w6*w21);
  /* #314: @51 = (@51+@71) */
  w51 += w71;
  /* #315: @71 = (@9*@22) */
  w71  = (w9*w22);
  /* #316: @51 = (@51+@71) */
  w51 += w71;
  /* #317: @71 = (@8*@53) */
  w71  = (w8*w53);
  /* #318: @51 = (@51-@71) */
  w51 -= w71;
  /* #319: @71 = (@8*@20) */
  w71  = (w8*w20);
  /* #320: @72 = (@9*@21) */
  w72  = (w9*w21);
  /* #321: @71 = (@71-@72) */
  w71 -= w72;
  /* #322: @72 = (@6*@22) */
  w72  = (w6*w22);
  /* #323: @71 = (@71+@72) */
  w71 += w72;
  /* #324: @72 = (@7*@53) */
  w72  = (w7*w53);
  /* #325: @71 = (@71+@72) */
  w71 += w72;
  /* #326: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #327: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #328: @20 = (@20+@21) */
  w20 += w21;
  /* #329: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #330: @20 = (@20-@22) */
  w20 -= w22;
  /* #331: @53 = (@6*@53) */
  w53  = (w6*w53);
  /* #332: @20 = (@20+@53) */
  w20 += w53;
  /* #333: @70 = vertcat(@52, @51, @71, @20) */
  rr=w70;
  *rr++ = w52;
  *rr++ = w51;
  *rr++ = w71;
  *rr++ = w20;
  /* #334: @73 = (@14*@70) */
  for (i=0, rr=w73, cs=w70; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #335: @52 = 1 */
  w52 = 1.;
  /* #336: @15 = (@15?@52:0) */
  w15  = (w15?w52:0);
  /* #337: @70 = (@15*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #338: @73 = (@73-@70) */
  for (i=0, rr=w73, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #339: @30 = @73[1:4] */
  for (rr=w30, ss=w73+1; ss!=w73+4; ss+=1) *rr++ = *ss;
  /* #340: @52 = dot(@37, @30) */
  w52 = casadi_dot(3, w37, w30);
  /* #341: @52 = (@52/@16) */
  w52 /= w16;
  /* #342: @51 = (@52/@5) */
  w51  = (w52/w5);
  /* #343: @71 = (@4/@5) */
  w71  = (w4/w5);
  /* #344: @20 = (2.*@16) */
  w20 = (2.* w16 );
  /* #345: @53 = (@20*@52) */
  w53  = (w20*w52);
  /* #346: @22 = (2.*@17) */
  w22 = (2.* w17 );
  /* #347: @21 = @73[0] */
  for (rr=(&w21), ss=w73+0; ss!=w73+1; ss+=1) *rr++ = *ss;
  /* #348: @72 = (@22*@21) */
  w72  = (w22*w21);
  /* #349: @53 = (@53+@72) */
  w53 += w72;
  /* #350: @72 = (@71*@53) */
  w72  = (w71*w53);
  /* #351: @51 = (@51-@72) */
  w51 -= w72;
  /* #352: @51 = (@0*@51) */
  w51  = (w0*w51);
  /* #353: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #354: @1 = (2.*@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #355: @27 = (@11*@1) */
  for (i=0, rr=w27, cs=w1; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #356: @72 = sq(@16) */
  w72 = casadi_sq( w16 );
  /* #357: @74 = sq(@17) */
  w74 = casadi_sq( w17 );
  /* #358: @72 = (@72+@74) */
  w72 += w74;
  /* #359: @17 = (@17/@72) */
  w17 /= w72;
  /* #360: @74 = (@17*@52) */
  w74  = (w17*w52);
  /* #361: @72 = (@16/@72) */
  w72  = (w16/w72);
  /* #362: @75 = (@72*@21) */
  w75  = (w72*w21);
  /* #363: @74 = (@74-@75) */
  w74 -= w75;
  /* #364: @2 = (@38*@74) */
  for (i=0, rr=w2, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #365: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #366: @27 = (@27/@16) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w16;
  /* #367: @39 = (@39/@16) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) /= w16;
  /* #368: @2 = (@39*@52) */
  for (i=0, rr=w2, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #369: @27 = (@27-@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #370: @2 = @27' */
  casadi_copy(w27, 3, w2);
  /* #371: @48 = mac(@2,@41,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #372: @48 = @48' */
  /* #373: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #374: @49 = @27' */
  casadi_copy(w27, 3, w49);
  /* #375: @2 = mac(@49,@46,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #376: @2 = @2' */
  /* #377: @48 = (@48+@2) */
  for (i=0, rr=w48, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #378: @2 = (@48/@16) */
  for (i=0, rr=w2, cr=w48; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #379: @49 = (@40/@16) */
  for (i=0, rr=w49, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #380: @76 = (@49*@52) */
  for (i=0, rr=w76, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #381: @2 = (@2-@76) */
  for (i=0, rr=w2, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #382: @75 = dot(@38, @2) */
  w75 = casadi_dot(3, w38, w2);
  /* #383: @77 = dot(@1, @40) */
  w77 = casadi_dot(3, w1, w40);
  /* #384: @75 = (@75+@77) */
  w75 += w77;
  /* #385: @77 = (@4*@75) */
  w77  = (w4*w75);
  /* #386: @51 = (@51+@77) */
  w51 += w77;
  /* #387: @51 = (-@51) */
  w51 = (- w51 );
  /* #388: (@64[0] += @51) */
  for (rr=w64+0, ss=(&w51); rr!=w64+1; rr+=1) *rr += *ss++;
  /* #389: @51 = dot(@47, @48) */
  w51 = casadi_dot(3, w47, w48);
  /* #390: @27 = (@27/@16) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w16;
  /* #391: @45 = (@45/@16) */
  for (i=0, rr=w45; i<3; ++i) (*rr++) /= w16;
  /* #392: @48 = (@45*@52) */
  for (i=0, rr=w48, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #393: @27 = (@27-@48) */
  for (i=0, rr=w27, cs=w48; i<3; ++i) (*rr++) -= (*cs++);
  /* #394: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #395: @77 = dot(@27, @31) */
  w77 = casadi_dot(3, w27, w31);
  /* #396: @51 = (@51+@77) */
  w51 += w77;
  /* #397: @21 = (@21/@5) */
  w21 /= w5;
  /* #398: @77 = (@18/@5) */
  w77  = (w18/w5);
  /* #399: @53 = (@77*@53) */
  w53  = (w77*w53);
  /* #400: @21 = (@21-@53) */
  w21 -= w53;
  /* #401: @21 = (@0*@21) */
  w21  = (w0*w21);
  /* #402: @75 = (@18*@75) */
  w75  = (w18*w75);
  /* #403: @21 = (@21+@75) */
  w21 += w75;
  /* #404: @51 = (@51+@21) */
  w51 += w21;
  /* #405: @51 = (@51/@16) */
  w51 /= w16;
  /* #406: @21 = (@12/@16) */
  w21  = (w12/w16);
  /* #407: @52 = (@21*@52) */
  w52  = (w21*w52);
  /* #408: @51 = (@51-@52) */
  w51 -= w52;
  /* #409: @27 = (@37*@51) */
  for (i=0, rr=w27, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w51);
  /* #410: @30 = (@12*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #411: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #412: @30 = (@40*@74) */
  for (i=0, rr=w30, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  /* #413: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #414: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #415: @30 = (2.*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #416: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #417: (@64[1:4] += @27) */
  for (rr=w64+1, ss=w27; rr!=w64+4; rr+=1) *rr += *ss++;
  /* #418: @73 = (@13*@64) */
  for (i=0, rr=w73, cs=w64; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #419: @64 = (@19*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #420: @73 = (@73-@64) */
  for (i=0, rr=w73, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #421: {@74, @51, @52, @75} = vertsplit(@73) */
  w74 = w73[0];
  w51 = w73[1];
  w52 = w73[2];
  w75 = w73[3];
  /* #422: @53 = (@9*@75) */
  w53  = (w9*w75);
  /* #423: @78 = (@8*@52) */
  w78  = (w8*w52);
  /* #424: @53 = (@53+@78) */
  w53 += w78;
  /* #425: @78 = (@7*@51) */
  w78  = (w7*w51);
  /* #426: @53 = (@53+@78) */
  w53 += w78;
  /* #427: @78 = (@6*@74) */
  w78  = (w6*w74);
  /* #428: @53 = (@53+@78) */
  w53 += w78;
  /* #429: @78 = (@8*@75) */
  w78  = (w8*w75);
  /* #430: @79 = (@9*@52) */
  w79  = (w9*w52);
  /* #431: @78 = (@78-@79) */
  w78 -= w79;
  /* #432: @79 = (@6*@51) */
  w79  = (w6*w51);
  /* #433: @78 = (@78+@79) */
  w78 += w79;
  /* #434: @79 = (@7*@74) */
  w79  = (w7*w74);
  /* #435: @78 = (@78-@79) */
  w78 -= w79;
  /* #436: @79 = (@6*@52) */
  w79  = (w6*w52);
  /* #437: @80 = (@7*@75) */
  w80  = (w7*w75);
  /* #438: @79 = (@79-@80) */
  w79 -= w80;
  /* #439: @80 = (@9*@51) */
  w80  = (w9*w51);
  /* #440: @79 = (@79+@80) */
  w79 += w80;
  /* #441: @80 = (@8*@74) */
  w80  = (w8*w74);
  /* #442: @79 = (@79-@80) */
  w79 -= w80;
  /* #443: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #444: @52 = (@7*@52) */
  w52  = (w7*w52);
  /* #445: @75 = (@75+@52) */
  w75 += w52;
  /* #446: @51 = (@8*@51) */
  w51  = (w8*w51);
  /* #447: @75 = (@75-@51) */
  w75 -= w51;
  /* #448: @74 = (@9*@74) */
  w74  = (w9*w74);
  /* #449: @75 = (@75-@74) */
  w75 -= w74;
  /* #450: @73 = vertcat(@53, @78, @79, @75) */
  rr=w73;
  *rr++ = w53;
  *rr++ = w78;
  *rr++ = w79;
  *rr++ = w75;
  /* #451: @53 = dot(@42, @73) */
  w53 = casadi_dot(4, w42, w73);
  /* #452: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #453: @36 = (@36/@10) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w10;
  /* #454: @64 = (@36*@60) */
  for (i=0, rr=w64, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #455: @69 = (@69-@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #456: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #457: @78 = dot(@69, @50) */
  w78 = casadi_dot(4, w69, w50);
  /* #458: @53 = (@53+@78) */
  w53 += w78;
  /* #459: @53 = (@53/@10) */
  w53 /= w10;
  /* #460: @78 = (@24/@10) */
  w78  = (w24/w10);
  /* #461: @79 = (@78*@60) */
  w79  = (w78*w60);
  /* #462: @53 = (@53-@79) */
  w53 -= w79;
  /* #463: @69 = (@34*@53) */
  for (i=0, rr=w69, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #464: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #465: @64 = dense(@57) */
  casadi_densify((&w57), casadi_s4, w64, 0);
  /* #466: @69 = (@69+@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #467: (@29[6:10] += @69) */
  for (rr=w29+6, ss=w69; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #468: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #469: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s5, 0);
  /* #470: @53 = @61[0] */
  for (rr=(&w53), ss=(&w61)+0; ss!=(&w61)+1; ss+=1) *rr++ = *ss;
  /* #471: @53 = (-@53) */
  w53 = (- w53 );
  /* #472: @61 = dot(@57, @53) */
  w61 = casadi_dot(1, (&w57), (&w53));
  /* #473: @30 = (@26*@61) */
  for (i=0, rr=w30, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #474: @2 = @30' */
  casadi_copy(w30, 3, w2);
  /* #475: @27 = mac(@2,@32,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #476: @27 = @27' */
  /* #477: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #478: @30 = @30' */
  /* #479: @2 = mac(@30,@54,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #480: @2 = @2' */
  /* #481: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #482: @61 = dot(@26, @27) */
  w61 = casadi_dot(3, w26, w27);
  /* #483: @27 = (@26*@61) */
  for (i=0, rr=w27, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #484: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #485: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #486: @48 = zeros(3x1) */
  casadi_clear(w48, 3);
  /* #487: @48 = mac(@3,@53,@48) */
  casadi_mtimes(w3, casadi_s7, (&w53), casadi_s5, w48, casadi_s6, w, 0);
  /* #488: @1 = @48' */
  casadi_copy(w48, 3, w1);
  /* #489: @30 = mac(@1,@28,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #490: @30 = @30' */
  /* #491: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #492: @48 = @48' */
  /* #493: @1 = mac(@48,@56,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #494: @1 = @1' */
  /* #495: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #496: @2 = mac(@55,@30,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #497: @27 = (@27+@2) */
  for (i=0, rr=w27, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #498: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #499: (@29[:3] += @27) */
  for (rr=w29+0, ss=w27; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #500: {@53, @61, @57, @79, @75, @74, @51, @52, @80, @81, @82, @83, @84} = vertsplit(@29) */
  w53 = w29[0];
  w61 = w29[1];
  w57 = w29[2];
  w79 = w29[3];
  w75 = w29[4];
  w74 = w29[5];
  w51 = w29[6];
  w52 = w29[7];
  w80 = w29[8];
  w81 = w29[9];
  w82 = w29[10];
  w83 = w29[11];
  w84 = w29[12];
  /* #501: @73 = (@73/@10) */
  for (i=0, rr=w73; i<4; ++i) (*rr++) /= w10;
  /* #502: @35 = (@35/@10) */
  for (i=0, rr=w35; i<4; ++i) (*rr++) /= w10;
  /* #503: @69 = (@35*@60) */
  for (i=0, rr=w69, cr=w35; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #504: @73 = (@73-@69) */
  for (i=0, rr=w73, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #505: {@60, @85, @86, @87} = vertsplit(@73) */
  w60 = w73[0];
  w85 = w73[1];
  w86 = w73[2];
  w87 = w73[3];
  /* #506: @60 = (@60+@51) */
  w60 += w51;
  /* #507: @52 = (@52-@85) */
  w52 -= w85;
  /* #508: @80 = (@80-@86) */
  w80 -= w86;
  /* #509: @81 = (@81-@87) */
  w81 -= w87;
  /* #510: @88 = vertcat(@59, @62, @23, @58, @53, @61, @57, @79, @75, @74, @60, @52, @80, @81, @82, @83, @84) */
  rr=w88;
  *rr++ = w59;
  *rr++ = w62;
  *rr++ = w23;
  *rr++ = w58;
  *rr++ = w53;
  *rr++ = w61;
  *rr++ = w57;
  *rr++ = w79;
  *rr++ = w75;
  *rr++ = w74;
  *rr++ = w60;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  /* #511: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #512: (@63[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @89) */
  for (cii=casadi_s9, rr=w63, ss=w89; cii!=casadi_s9+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #513: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #514: (@63[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @89) */
  for (cii=casadi_s10, rr=w63, ss=w89; cii!=casadi_s10+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #515: @73 = zeros(1x4) */
  casadi_clear(w73, 4);
  /* #516: @66 = 00 */
  /* #517: @27 = ones(17x1,3nz) */
  casadi_fill(w27, 3, 1.);
  /* #518: {NULL, @59, NULL, NULL, NULL, @62, NULL, NULL, NULL, NULL, NULL, @23, NULL, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w59 = w27[0];
  w62 = w27[1];
  w23 = w27[2];
  /* #519: @67 = 00 */
  /* #520: @68 = 00 */
  /* #521: @58 = vertcat(@66, @59, @67, @68) */
  rr=(&w58);
  *rr++ = w59;
  /* #522: @59 = @58' */
  casadi_copy((&w58), 1, (&w59));
  /* #523: @73 = mac(@59,@43,@73) */
  casadi_mtimes((&w59), casadi_s11, w43, casadi_s2, w73, casadi_s1, w, 0);
  /* #524: @73 = @73' */
  /* #525: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #526: @58 = @58' */
  /* #527: @69 = mac(@58,@44,@69) */
  casadi_mtimes((&w58), casadi_s11, w44, casadi_s2, w69, casadi_s1, w, 0);
  /* #528: @69 = @69' */
  /* #529: @73 = (@73+@69) */
  for (i=0, rr=w73, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #530: {@58, @59, @53, @61} = vertsplit(@73) */
  w58 = w73[0];
  w59 = w73[1];
  w53 = w73[2];
  w61 = w73[3];
  /* #531: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #532: @73 = zeros(4x1) */
  casadi_clear(w73, 4);
  /* #533: @66 = 00 */
  /* #534: @57 = (-@23) */
  w57 = (- w23 );
  /* #535: @67 = 00 */
  /* #536: @68 = 00 */
  /* #537: @79 = vertcat(@66, @57, @67, @68) */
  rr=(&w79);
  *rr++ = w57;
  /* #538: @79 = (@79/@10) */
  w79 /= w10;
  /* #539: @69 = dense(@79) */
  casadi_densify((&w79), casadi_s12, w69, 0);
  /* #540: @79 = project(@34) */
  casadi_sparsify(w34, (&w79), casadi_s12, 0);
  /* #541: @57 = @23[0] */
  for (rr=(&w57), ss=(&w23)+0; ss!=(&w23)+1; ss+=1) *rr++ = *ss;
  /* #542: @23 = dot(@79, @57) */
  w23 = casadi_dot(1, (&w79), (&w57));
  /* #543: @23 = (@23/@10) */
  w23 /= w10;
  /* #544: @64 = (@33*@23) */
  for (i=0, rr=w64, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #545: @69 = (@69-@64) */
  for (i=0, rr=w69, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #546: {@79, @75, @74, @60} = vertsplit(@69) */
  w79 = w69[0];
  w75 = w69[1];
  w74 = w69[2];
  w60 = w69[3];
  /* #547: @52 = (@6*@79) */
  w52  = (w6*w79);
  /* #548: @80 = (@7*@75) */
  w80  = (w7*w75);
  /* #549: @52 = (@52-@80) */
  w52 -= w80;
  /* #550: @80 = (@8*@74) */
  w80  = (w8*w74);
  /* #551: @52 = (@52-@80) */
  w52 -= w80;
  /* #552: @80 = (@9*@60) */
  w80  = (w9*w60);
  /* #553: @52 = (@52-@80) */
  w52 -= w80;
  /* #554: @80 = (@7*@79) */
  w80  = (w7*w79);
  /* #555: @81 = (@6*@75) */
  w81  = (w6*w75);
  /* #556: @80 = (@80+@81) */
  w80 += w81;
  /* #557: @81 = (@9*@74) */
  w81  = (w9*w74);
  /* #558: @80 = (@80+@81) */
  w80 += w81;
  /* #559: @81 = (@8*@60) */
  w81  = (w8*w60);
  /* #560: @80 = (@80-@81) */
  w80 -= w81;
  /* #561: @81 = (@8*@79) */
  w81  = (w8*w79);
  /* #562: @82 = (@9*@75) */
  w82  = (w9*w75);
  /* #563: @81 = (@81-@82) */
  w81 -= w82;
  /* #564: @82 = (@6*@74) */
  w82  = (w6*w74);
  /* #565: @81 = (@81+@82) */
  w81 += w82;
  /* #566: @82 = (@7*@60) */
  w82  = (w7*w60);
  /* #567: @81 = (@81+@82) */
  w81 += w82;
  /* #568: @79 = (@9*@79) */
  w79  = (w9*w79);
  /* #569: @75 = (@8*@75) */
  w75  = (w8*w75);
  /* #570: @79 = (@79+@75) */
  w79 += w75;
  /* #571: @74 = (@7*@74) */
  w74  = (w7*w74);
  /* #572: @79 = (@79-@74) */
  w79 -= w74;
  /* #573: @60 = (@6*@60) */
  w60  = (w6*w60);
  /* #574: @79 = (@79+@60) */
  w79 += w60;
  /* #575: @64 = vertcat(@52, @80, @81, @79) */
  rr=w64;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w79;
  /* #576: @70 = (@14*@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #577: @64 = (@15*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #578: @70 = (@70-@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #579: @27 = @70[1:4] */
  for (rr=w27, ss=w70+1; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #580: @52 = dot(@37, @27) */
  w52 = casadi_dot(3, w37, w27);
  /* #581: @52 = (@52/@16) */
  w52 /= w16;
  /* #582: @80 = (@52/@5) */
  w80  = (w52/w5);
  /* #583: @81 = (@20*@52) */
  w81  = (w20*w52);
  /* #584: @79 = @70[0] */
  for (rr=(&w79), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #585: @60 = (@22*@79) */
  w60  = (w22*w79);
  /* #586: @81 = (@81+@60) */
  w81 += w60;
  /* #587: @60 = (@71*@81) */
  w60  = (w71*w81);
  /* #588: @80 = (@80-@60) */
  w80 -= w60;
  /* #589: @80 = (@0*@80) */
  w80  = (w0*w80);
  /* #590: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #591: @30 = (2.*@27) */
  for (i=0, rr=w30, cs=w27; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #592: @1 = (@11*@30) */
  for (i=0, rr=w1, cs=w30; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #593: @60 = (@17*@52) */
  w60  = (w17*w52);
  /* #594: @74 = (@72*@79) */
  w74  = (w72*w79);
  /* #595: @60 = (@60-@74) */
  w60 -= w74;
  /* #596: @48 = (@38*@60) */
  for (i=0, rr=w48, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #597: @1 = (@1+@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #598: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #599: @48 = (@39*@52) */
  for (i=0, rr=w48, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #600: @1 = (@1-@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) -= (*cs++);
  /* #601: @48 = @1' */
  casadi_copy(w1, 3, w48);
  /* #602: @2 = mac(@48,@41,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #603: @2 = @2' */
  /* #604: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #605: @76 = @1' */
  casadi_copy(w1, 3, w76);
  /* #606: @48 = mac(@76,@46,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w76+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #607: @48 = @48' */
  /* #608: @2 = (@2+@48) */
  for (i=0, rr=w2, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #609: @48 = (@2/@16) */
  for (i=0, rr=w48, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #610: @76 = (@49*@52) */
  for (i=0, rr=w76, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #611: @48 = (@48-@76) */
  for (i=0, rr=w48, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #612: @74 = dot(@38, @48) */
  w74 = casadi_dot(3, w38, w48);
  /* #613: @75 = dot(@30, @40) */
  w75 = casadi_dot(3, w30, w40);
  /* #614: @74 = (@74+@75) */
  w74 += w75;
  /* #615: @75 = (@4*@74) */
  w75  = (w4*w74);
  /* #616: @80 = (@80+@75) */
  w80 += w75;
  /* #617: @80 = (-@80) */
  w80 = (- w80 );
  /* #618: (@73[0] += @80) */
  for (rr=w73+0, ss=(&w80); rr!=w73+1; rr+=1) *rr += *ss++;
  /* #619: @80 = dot(@47, @2) */
  w80 = casadi_dot(3, w47, w2);
  /* #620: @1 = (@1/@16) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w16;
  /* #621: @2 = (@45*@52) */
  for (i=0, rr=w2, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #622: @1 = (@1-@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #623: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #624: @75 = dot(@1, @31) */
  w75 = casadi_dot(3, w1, w31);
  /* #625: @80 = (@80+@75) */
  w80 += w75;
  /* #626: @79 = (@79/@5) */
  w79 /= w5;
  /* #627: @81 = (@77*@81) */
  w81  = (w77*w81);
  /* #628: @79 = (@79-@81) */
  w79 -= w81;
  /* #629: @79 = (@0*@79) */
  w79  = (w0*w79);
  /* #630: @74 = (@18*@74) */
  w74  = (w18*w74);
  /* #631: @79 = (@79+@74) */
  w79 += w74;
  /* #632: @80 = (@80+@79) */
  w80 += w79;
  /* #633: @80 = (@80/@16) */
  w80 /= w16;
  /* #634: @52 = (@21*@52) */
  w52  = (w21*w52);
  /* #635: @80 = (@80-@52) */
  w80 -= w52;
  /* #636: @1 = (@37*@80) */
  for (i=0, rr=w1, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #637: @27 = (@12*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #638: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #639: @27 = (@40*@60) */
  for (i=0, rr=w27, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #640: @48 = (@11*@48) */
  for (i=0, rr=w48, cs=w48; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #641: @27 = (@27+@48) */
  for (i=0, rr=w27, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #642: @27 = (2.*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #643: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #644: (@73[1:4] += @1) */
  for (rr=w73+1, ss=w1; rr!=w73+4; rr+=1) *rr += *ss++;
  /* #645: @70 = (@13*@73) */
  for (i=0, rr=w70, cs=w73; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #646: @73 = (@19*@73) */
  for (i=0, rr=w73, cs=w73; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #647: @70 = (@70-@73) */
  for (i=0, rr=w70, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #648: {@60, @80, @52, @79} = vertsplit(@70) */
  w60 = w70[0];
  w80 = w70[1];
  w52 = w70[2];
  w79 = w70[3];
  /* #649: @74 = (@9*@79) */
  w74  = (w9*w79);
  /* #650: @81 = (@8*@52) */
  w81  = (w8*w52);
  /* #651: @74 = (@74+@81) */
  w74 += w81;
  /* #652: @81 = (@7*@80) */
  w81  = (w7*w80);
  /* #653: @74 = (@74+@81) */
  w74 += w81;
  /* #654: @81 = (@6*@60) */
  w81  = (w6*w60);
  /* #655: @74 = (@74+@81) */
  w74 += w81;
  /* #656: @81 = (@8*@79) */
  w81  = (w8*w79);
  /* #657: @75 = (@9*@52) */
  w75  = (w9*w52);
  /* #658: @81 = (@81-@75) */
  w81 -= w75;
  /* #659: @75 = (@6*@80) */
  w75  = (w6*w80);
  /* #660: @81 = (@81+@75) */
  w81 += w75;
  /* #661: @75 = (@7*@60) */
  w75  = (w7*w60);
  /* #662: @81 = (@81-@75) */
  w81 -= w75;
  /* #663: @75 = (@6*@52) */
  w75  = (w6*w52);
  /* #664: @82 = (@7*@79) */
  w82  = (w7*w79);
  /* #665: @75 = (@75-@82) */
  w75 -= w82;
  /* #666: @82 = (@9*@80) */
  w82  = (w9*w80);
  /* #667: @75 = (@75+@82) */
  w75 += w82;
  /* #668: @82 = (@8*@60) */
  w82  = (w8*w60);
  /* #669: @75 = (@75-@82) */
  w75 -= w82;
  /* #670: @79 = (@6*@79) */
  w79  = (w6*w79);
  /* #671: @52 = (@7*@52) */
  w52  = (w7*w52);
  /* #672: @79 = (@79+@52) */
  w79 += w52;
  /* #673: @80 = (@8*@80) */
  w80  = (w8*w80);
  /* #674: @79 = (@79-@80) */
  w79 -= w80;
  /* #675: @60 = (@9*@60) */
  w60  = (w9*w60);
  /* #676: @79 = (@79-@60) */
  w79 -= w60;
  /* #677: @70 = vertcat(@74, @81, @75, @79) */
  rr=w70;
  *rr++ = w74;
  *rr++ = w81;
  *rr++ = w75;
  *rr++ = w79;
  /* #678: @74 = dot(@42, @70) */
  w74 = casadi_dot(4, w42, w70);
  /* #679: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #680: @73 = (@36*@23) */
  for (i=0, rr=w73, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #681: @69 = (@69-@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #682: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #683: @81 = dot(@69, @50) */
  w81 = casadi_dot(4, w69, w50);
  /* #684: @74 = (@74+@81) */
  w74 += w81;
  /* #685: @74 = (@74/@10) */
  w74 /= w10;
  /* #686: @81 = (@78*@23) */
  w81  = (w78*w23);
  /* #687: @74 = (@74-@81) */
  w74 -= w81;
  /* #688: @69 = (@34*@74) */
  for (i=0, rr=w69, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w74);
  /* #689: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #690: @73 = dense(@57) */
  casadi_densify((&w57), casadi_s12, w73, 0);
  /* #691: @69 = (@69+@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) += (*cs++);
  /* #692: (@29[6:10] += @69) */
  for (rr=w29+6, ss=w69; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #693: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #694: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s13, 0);
  /* #695: @74 = @62[0] */
  for (rr=(&w74), ss=(&w62)+0; ss!=(&w62)+1; ss+=1) *rr++ = *ss;
  /* #696: @74 = (-@74) */
  w74 = (- w74 );
  /* #697: @62 = dot(@57, @74) */
  w62 = casadi_dot(1, (&w57), (&w74));
  /* #698: @27 = (@26*@62) */
  for (i=0, rr=w27, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #699: @48 = @27' */
  casadi_copy(w27, 3, w48);
  /* #700: @1 = mac(@48,@32,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #701: @1 = @1' */
  /* #702: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #703: @27 = @27' */
  /* #704: @48 = mac(@27,@54,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #705: @48 = @48' */
  /* #706: @1 = (@1+@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #707: @62 = dot(@26, @1) */
  w62 = casadi_dot(3, w26, w1);
  /* #708: @1 = (@26*@62) */
  for (i=0, rr=w1, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #709: @48 = zeros(3x1) */
  casadi_clear(w48, 3);
  /* #710: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #711: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #712: @2 = mac(@3,@74,@2) */
  casadi_mtimes(w3, casadi_s7, (&w74), casadi_s13, w2, casadi_s6, w, 0);
  /* #713: @30 = @2' */
  casadi_copy(w2, 3, w30);
  /* #714: @27 = mac(@30,@28,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #715: @27 = @27' */
  /* #716: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #717: @2 = @2' */
  /* #718: @30 = mac(@2,@56,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #719: @30 = @30' */
  /* #720: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #721: @48 = mac(@55,@27,@48) */
  for (i=0, rr=w48; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #722: @1 = (@1+@48) */
  for (i=0, rr=w1, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #723: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #724: (@29[:3] += @1) */
  for (rr=w29+0, ss=w1; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #725: {@74, @62, @57, @81, @75, @79, @60, @80, @52, @82, @83, @84, @87} = vertsplit(@29) */
  w74 = w29[0];
  w62 = w29[1];
  w57 = w29[2];
  w81 = w29[3];
  w75 = w29[4];
  w79 = w29[5];
  w60 = w29[6];
  w80 = w29[7];
  w52 = w29[8];
  w82 = w29[9];
  w83 = w29[10];
  w84 = w29[11];
  w87 = w29[12];
  /* #726: @70 = (@70/@10) */
  for (i=0, rr=w70; i<4; ++i) (*rr++) /= w10;
  /* #727: @69 = (@35*@23) */
  for (i=0, rr=w69, cr=w35; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #728: @70 = (@70-@69) */
  for (i=0, rr=w70, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #729: {@23, @86, @85, @51} = vertsplit(@70) */
  w23 = w70[0];
  w86 = w70[1];
  w85 = w70[2];
  w51 = w70[3];
  /* #730: @23 = (@23+@60) */
  w23 += w60;
  /* #731: @80 = (@80-@86) */
  w80 -= w86;
  /* #732: @52 = (@52-@85) */
  w52 -= w85;
  /* #733: @82 = (@82-@51) */
  w82 -= w51;
  /* #734: @88 = vertcat(@58, @59, @53, @61, @74, @62, @57, @81, @75, @79, @23, @80, @52, @82, @83, @84, @87) */
  rr=w88;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w53;
  *rr++ = w61;
  *rr++ = w74;
  *rr++ = w62;
  *rr++ = w57;
  *rr++ = w81;
  *rr++ = w75;
  *rr++ = w79;
  *rr++ = w23;
  *rr++ = w80;
  *rr++ = w52;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w87;
  /* #735: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #736: (@63[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @89) */
  for (cii=casadi_s14, rr=w63, ss=w89; cii!=casadi_s14+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #737: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #738: (@63[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @89) */
  for (cii=casadi_s15, rr=w63, ss=w89; cii!=casadi_s15+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #739: @70 = zeros(1x4) */
  casadi_clear(w70, 4);
  /* #740: @66 = 00 */
  /* #741: @67 = 00 */
  /* #742: @1 = ones(17x1,3nz) */
  casadi_fill(w1, 3, 1.);
  /* #743: {NULL, NULL, @58, NULL, NULL, NULL, @59, NULL, NULL, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w58 = w1[0];
  w59 = w1[1];
  w53 = w1[2];
  /* #744: @68 = 00 */
  /* #745: @61 = vertcat(@66, @67, @58, @68) */
  rr=(&w61);
  *rr++ = w58;
  /* #746: @58 = @61' */
  casadi_copy((&w61), 1, (&w58));
  /* #747: @70 = mac(@58,@43,@70) */
  casadi_mtimes((&w58), casadi_s16, w43, casadi_s2, w70, casadi_s1, w, 0);
  /* #748: @70 = @70' */
  /* #749: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #750: @61 = @61' */
  /* #751: @69 = mac(@61,@44,@69) */
  casadi_mtimes((&w61), casadi_s16, w44, casadi_s2, w69, casadi_s1, w, 0);
  /* #752: @69 = @69' */
  /* #753: @70 = (@70+@69) */
  for (i=0, rr=w70, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #754: {@61, @58, @74, @62} = vertsplit(@70) */
  w61 = w70[0];
  w58 = w70[1];
  w74 = w70[2];
  w62 = w70[3];
  /* #755: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #756: @70 = zeros(4x1) */
  casadi_clear(w70, 4);
  /* #757: @66 = 00 */
  /* #758: @67 = 00 */
  /* #759: @57 = (-@53) */
  w57 = (- w53 );
  /* #760: @68 = 00 */
  /* #761: @81 = vertcat(@66, @67, @57, @68) */
  rr=(&w81);
  *rr++ = w57;
  /* #762: @81 = (@81/@10) */
  w81 /= w10;
  /* #763: @69 = dense(@81) */
  casadi_densify((&w81), casadi_s17, w69, 0);
  /* #764: @81 = project(@34) */
  casadi_sparsify(w34, (&w81), casadi_s17, 0);
  /* #765: @57 = @53[0] */
  for (rr=(&w57), ss=(&w53)+0; ss!=(&w53)+1; ss+=1) *rr++ = *ss;
  /* #766: @53 = dot(@81, @57) */
  w53 = casadi_dot(1, (&w81), (&w57));
  /* #767: @53 = (@53/@10) */
  w53 /= w10;
  /* #768: @73 = (@33*@53) */
  for (i=0, rr=w73, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #769: @69 = (@69-@73) */
  for (i=0, rr=w69, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #770: {@81, @75, @79, @23} = vertsplit(@69) */
  w81 = w69[0];
  w75 = w69[1];
  w79 = w69[2];
  w23 = w69[3];
  /* #771: @80 = (@6*@81) */
  w80  = (w6*w81);
  /* #772: @52 = (@7*@75) */
  w52  = (w7*w75);
  /* #773: @80 = (@80-@52) */
  w80 -= w52;
  /* #774: @52 = (@8*@79) */
  w52  = (w8*w79);
  /* #775: @80 = (@80-@52) */
  w80 -= w52;
  /* #776: @52 = (@9*@23) */
  w52  = (w9*w23);
  /* #777: @80 = (@80-@52) */
  w80 -= w52;
  /* #778: @52 = (@7*@81) */
  w52  = (w7*w81);
  /* #779: @82 = (@6*@75) */
  w82  = (w6*w75);
  /* #780: @52 = (@52+@82) */
  w52 += w82;
  /* #781: @82 = (@9*@79) */
  w82  = (w9*w79);
  /* #782: @52 = (@52+@82) */
  w52 += w82;
  /* #783: @82 = (@8*@23) */
  w82  = (w8*w23);
  /* #784: @52 = (@52-@82) */
  w52 -= w82;
  /* #785: @82 = (@8*@81) */
  w82  = (w8*w81);
  /* #786: @83 = (@9*@75) */
  w83  = (w9*w75);
  /* #787: @82 = (@82-@83) */
  w82 -= w83;
  /* #788: @83 = (@6*@79) */
  w83  = (w6*w79);
  /* #789: @82 = (@82+@83) */
  w82 += w83;
  /* #790: @83 = (@7*@23) */
  w83  = (w7*w23);
  /* #791: @82 = (@82+@83) */
  w82 += w83;
  /* #792: @81 = (@9*@81) */
  w81  = (w9*w81);
  /* #793: @75 = (@8*@75) */
  w75  = (w8*w75);
  /* #794: @81 = (@81+@75) */
  w81 += w75;
  /* #795: @79 = (@7*@79) */
  w79  = (w7*w79);
  /* #796: @81 = (@81-@79) */
  w81 -= w79;
  /* #797: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #798: @81 = (@81+@23) */
  w81 += w23;
  /* #799: @73 = vertcat(@80, @52, @82, @81) */
  rr=w73;
  *rr++ = w80;
  *rr++ = w52;
  *rr++ = w82;
  *rr++ = w81;
  /* #800: @64 = (@14*@73) */
  for (i=0, rr=w64, cs=w73; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #801: @73 = (@15*@73) */
  for (i=0, rr=w73, cs=w73; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #802: @64 = (@64-@73) */
  for (i=0, rr=w64, cs=w73; i<4; ++i) (*rr++) -= (*cs++);
  /* #803: @1 = @64[1:4] */
  for (rr=w1, ss=w64+1; ss!=w64+4; ss+=1) *rr++ = *ss;
  /* #804: @80 = dot(@37, @1) */
  w80 = casadi_dot(3, w37, w1);
  /* #805: @80 = (@80/@16) */
  w80 /= w16;
  /* #806: @52 = (@80/@5) */
  w52  = (w80/w5);
  /* #807: @82 = (@20*@80) */
  w82  = (w20*w80);
  /* #808: @81 = @64[0] */
  for (rr=(&w81), ss=w64+0; ss!=w64+1; ss+=1) *rr++ = *ss;
  /* #809: @23 = (@22*@81) */
  w23  = (w22*w81);
  /* #810: @82 = (@82+@23) */
  w82 += w23;
  /* #811: @23 = (@71*@82) */
  w23  = (w71*w82);
  /* #812: @52 = (@52-@23) */
  w52 -= w23;
  /* #813: @52 = (@0*@52) */
  w52  = (w0*w52);
  /* #814: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #815: @27 = (2.*@1) */
  for (i=0, rr=w27, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #816: @30 = (@11*@27) */
  for (i=0, rr=w30, cs=w27; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #817: @23 = (@17*@80) */
  w23  = (w17*w80);
  /* #818: @79 = (@72*@81) */
  w79  = (w72*w81);
  /* #819: @23 = (@23-@79) */
  w23 -= w79;
  /* #820: @2 = (@38*@23) */
  for (i=0, rr=w2, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w23);
  /* #821: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #822: @30 = (@30/@16) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w16;
  /* #823: @2 = (@39*@80) */
  for (i=0, rr=w2, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #824: @30 = (@30-@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #825: @2 = @30' */
  casadi_copy(w30, 3, w2);
  /* #826: @48 = mac(@2,@41,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #827: @48 = @48' */
  /* #828: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #829: @76 = @30' */
  casadi_copy(w30, 3, w76);
  /* #830: @2 = mac(@76,@46,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w76+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #831: @2 = @2' */
  /* #832: @48 = (@48+@2) */
  for (i=0, rr=w48, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #833: @2 = (@48/@16) */
  for (i=0, rr=w2, cr=w48; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #834: @76 = (@49*@80) */
  for (i=0, rr=w76, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #835: @2 = (@2-@76) */
  for (i=0, rr=w2, cs=w76; i<3; ++i) (*rr++) -= (*cs++);
  /* #836: @79 = dot(@38, @2) */
  w79 = casadi_dot(3, w38, w2);
  /* #837: @75 = dot(@27, @40) */
  w75 = casadi_dot(3, w27, w40);
  /* #838: @79 = (@79+@75) */
  w79 += w75;
  /* #839: @75 = (@4*@79) */
  w75  = (w4*w79);
  /* #840: @52 = (@52+@75) */
  w52 += w75;
  /* #841: @52 = (-@52) */
  w52 = (- w52 );
  /* #842: (@70[0] += @52) */
  for (rr=w70+0, ss=(&w52); rr!=w70+1; rr+=1) *rr += *ss++;
  /* #843: @52 = dot(@47, @48) */
  w52 = casadi_dot(3, w47, w48);
  /* #844: @30 = (@30/@16) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w16;
  /* #845: @48 = (@45*@80) */
  for (i=0, rr=w48, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  /* #846: @30 = (@30-@48) */
  for (i=0, rr=w30, cs=w48; i<3; ++i) (*rr++) -= (*cs++);
  /* #847: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #848: @75 = dot(@30, @31) */
  w75 = casadi_dot(3, w30, w31);
  /* #849: @52 = (@52+@75) */
  w52 += w75;
  /* #850: @81 = (@81/@5) */
  w81 /= w5;
  /* #851: @82 = (@77*@82) */
  w82  = (w77*w82);
  /* #852: @81 = (@81-@82) */
  w81 -= w82;
  /* #853: @81 = (@0*@81) */
  w81  = (w0*w81);
  /* #854: @79 = (@18*@79) */
  w79  = (w18*w79);
  /* #855: @81 = (@81+@79) */
  w81 += w79;
  /* #856: @52 = (@52+@81) */
  w52 += w81;
  /* #857: @52 = (@52/@16) */
  w52 /= w16;
  /* #858: @80 = (@21*@80) */
  w80  = (w21*w80);
  /* #859: @52 = (@52-@80) */
  w52 -= w80;
  /* #860: @30 = (@37*@52) */
  for (i=0, rr=w30, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #861: @1 = (@12*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #862: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #863: @1 = (@40*@23) */
  for (i=0, rr=w1, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w23);
  /* #864: @2 = (@11*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #865: @1 = (@1+@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #866: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #867: @30 = (@30+@1) */
  for (i=0, rr=w30, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #868: (@70[1:4] += @30) */
  for (rr=w70+1, ss=w30; rr!=w70+4; rr+=1) *rr += *ss++;
  /* #869: @64 = (@13*@70) */
  for (i=0, rr=w64, cs=w70; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #870: @70 = (@19*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #871: @64 = (@64-@70) */
  for (i=0, rr=w64, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #872: {@23, @52, @80, @81} = vertsplit(@64) */
  w23 = w64[0];
  w52 = w64[1];
  w80 = w64[2];
  w81 = w64[3];
  /* #873: @79 = (@9*@81) */
  w79  = (w9*w81);
  /* #874: @82 = (@8*@80) */
  w82  = (w8*w80);
  /* #875: @79 = (@79+@82) */
  w79 += w82;
  /* #876: @82 = (@7*@52) */
  w82  = (w7*w52);
  /* #877: @79 = (@79+@82) */
  w79 += w82;
  /* #878: @82 = (@6*@23) */
  w82  = (w6*w23);
  /* #879: @79 = (@79+@82) */
  w79 += w82;
  /* #880: @82 = (@8*@81) */
  w82  = (w8*w81);
  /* #881: @75 = (@9*@80) */
  w75  = (w9*w80);
  /* #882: @82 = (@82-@75) */
  w82 -= w75;
  /* #883: @75 = (@6*@52) */
  w75  = (w6*w52);
  /* #884: @82 = (@82+@75) */
  w82 += w75;
  /* #885: @75 = (@7*@23) */
  w75  = (w7*w23);
  /* #886: @82 = (@82-@75) */
  w82 -= w75;
  /* #887: @75 = (@6*@80) */
  w75  = (w6*w80);
  /* #888: @83 = (@7*@81) */
  w83  = (w7*w81);
  /* #889: @75 = (@75-@83) */
  w75 -= w83;
  /* #890: @83 = (@9*@52) */
  w83  = (w9*w52);
  /* #891: @75 = (@75+@83) */
  w75 += w83;
  /* #892: @83 = (@8*@23) */
  w83  = (w8*w23);
  /* #893: @75 = (@75-@83) */
  w75 -= w83;
  /* #894: @81 = (@6*@81) */
  w81  = (w6*w81);
  /* #895: @80 = (@7*@80) */
  w80  = (w7*w80);
  /* #896: @81 = (@81+@80) */
  w81 += w80;
  /* #897: @52 = (@8*@52) */
  w52  = (w8*w52);
  /* #898: @81 = (@81-@52) */
  w81 -= w52;
  /* #899: @23 = (@9*@23) */
  w23  = (w9*w23);
  /* #900: @81 = (@81-@23) */
  w81 -= w23;
  /* #901: @64 = vertcat(@79, @82, @75, @81) */
  rr=w64;
  *rr++ = w79;
  *rr++ = w82;
  *rr++ = w75;
  *rr++ = w81;
  /* #902: @79 = dot(@42, @64) */
  w79 = casadi_dot(4, w42, w64);
  /* #903: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #904: @70 = (@36*@53) */
  for (i=0, rr=w70, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #905: @69 = (@69-@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #906: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #907: @82 = dot(@69, @50) */
  w82 = casadi_dot(4, w69, w50);
  /* #908: @79 = (@79+@82) */
  w79 += w82;
  /* #909: @79 = (@79/@10) */
  w79 /= w10;
  /* #910: @82 = (@78*@53) */
  w82  = (w78*w53);
  /* #911: @79 = (@79-@82) */
  w79 -= w82;
  /* #912: @69 = (@34*@79) */
  for (i=0, rr=w69, cr=w34; i<4; ++i) (*rr++)  = ((*cr++)*w79);
  /* #913: @57 = (@24*@57) */
  w57  = (w24*w57);
  /* #914: @70 = dense(@57) */
  casadi_densify((&w57), casadi_s17, w70, 0);
  /* #915: @69 = (@69+@70) */
  for (i=0, rr=w69, cs=w70; i<4; ++i) (*rr++) += (*cs++);
  /* #916: (@29[6:10] += @69) */
  for (rr=w29+6, ss=w69; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #917: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #918: @57 = project(@26) */
  casadi_sparsify(w26, (&w57), casadi_s18, 0);
  /* #919: @79 = @59[0] */
  for (rr=(&w79), ss=(&w59)+0; ss!=(&w59)+1; ss+=1) *rr++ = *ss;
  /* #920: @79 = (-@79) */
  w79 = (- w79 );
  /* #921: @59 = dot(@57, @79) */
  w59 = casadi_dot(1, (&w57), (&w79));
  /* #922: @1 = (@26*@59) */
  for (i=0, rr=w1, cr=w26; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #923: @2 = @1' */
  casadi_copy(w1, 3, w2);
  /* #924: @30 = mac(@2,@32,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #925: @30 = @30' */
  /* #926: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #927: @1 = @1' */
  /* #928: @2 = mac(@1,@54,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #929: @2 = @2' */
  /* #930: @30 = (@30+@2) */
  for (i=0, rr=w30, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #931: @59 = dot(@26, @30) */
  w59 = casadi_dot(3, w26, w30);
  /* #932: @26 = (@26*@59) */
  for (i=0, rr=w26; i<3; ++i) (*rr++) *= w59;
  /* #933: @30 = zeros(3x1) */
  casadi_clear(w30, 3);
  /* #934: @2 = zeros(1x3) */
  casadi_clear(w2, 3);
  /* #935: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #936: @1 = mac(@3,@79,@1) */
  casadi_mtimes(w3, casadi_s7, (&w79), casadi_s18, w1, casadi_s6, w, 0);
  /* #937: @48 = @1' */
  casadi_copy(w1, 3, w48);
  /* #938: @2 = mac(@48,@28,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #939: @2 = @2' */
  /* #940: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #941: @1 = @1' */
  /* #942: @48 = mac(@1,@56,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w56+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #943: @48 = @48' */
  /* #944: @2 = (@2+@48) */
  for (i=0, rr=w2, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #945: @30 = mac(@55,@2,@30) */
  for (i=0, rr=w30; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w55+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #946: @26 = (@26+@30) */
  for (i=0, rr=w26, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #947: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (- *cs++ );
  /* #948: (@29[:3] += @26) */
  for (rr=w29+0, ss=w26; rr!=w29+3; rr+=1) *rr += *ss++;
  /* #949: {@79, @59, @57, @82, @75, @81, @23, @52, @80, @83, @84, @87, @51} = vertsplit(@29) */
  w79 = w29[0];
  w59 = w29[1];
  w57 = w29[2];
  w82 = w29[3];
  w75 = w29[4];
  w81 = w29[5];
  w23 = w29[6];
  w52 = w29[7];
  w80 = w29[8];
  w83 = w29[9];
  w84 = w29[10];
  w87 = w29[11];
  w51 = w29[12];
  /* #950: @64 = (@64/@10) */
  for (i=0, rr=w64; i<4; ++i) (*rr++) /= w10;
  /* #951: @69 = (@35*@53) */
  for (i=0, rr=w69, cr=w35; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #952: @64 = (@64-@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #953: {@53, @85, @86, @60} = vertsplit(@64) */
  w53 = w64[0];
  w85 = w64[1];
  w86 = w64[2];
  w60 = w64[3];
  /* #954: @53 = (@53+@23) */
  w53 += w23;
  /* #955: @52 = (@52-@85) */
  w52 -= w85;
  /* #956: @80 = (@80-@86) */
  w80 -= w86;
  /* #957: @83 = (@83-@60) */
  w83 -= w60;
  /* #958: @88 = vertcat(@61, @58, @74, @62, @79, @59, @57, @82, @75, @81, @53, @52, @80, @83, @84, @87, @51) */
  rr=w88;
  *rr++ = w61;
  *rr++ = w58;
  *rr++ = w74;
  *rr++ = w62;
  *rr++ = w79;
  *rr++ = w59;
  *rr++ = w57;
  *rr++ = w82;
  *rr++ = w75;
  *rr++ = w81;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w87;
  *rr++ = w51;
  /* #959: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #960: (@63[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @89) */
  for (cii=casadi_s19, rr=w63, ss=w89; cii!=casadi_s19+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #961: @89 = @88[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s8, rr=w89, ss=w88; cii!=casadi_s8+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #962: (@63[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @89) */
  for (cii=casadi_s20, rr=w63, ss=w89; cii!=casadi_s20+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #963: @64 = zeros(1x4) */
  casadi_clear(w64, 4);
  /* #964: @66 = 00 */
  /* #965: @67 = 00 */
  /* #966: @68 = 00 */
  /* #967: @90 = ones(17x1,2nz) */
  casadi_fill(w90, 2, 1.);
  /* #968: {NULL, NULL, NULL, @61, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @58, NULL, NULL, NULL} = vertsplit(@90) */
  w61 = w90[0];
  w58 = w90[1];
  /* #969: @74 = vertcat(@66, @67, @68, @61) */
  rr=(&w74);
  *rr++ = w61;
  /* #970: @61 = @74' */
  casadi_copy((&w74), 1, (&w61));
  /* #971: @64 = mac(@61,@43,@64) */
  casadi_mtimes((&w61), casadi_s21, w43, casadi_s2, w64, casadi_s1, w, 0);
  /* #972: @64 = @64' */
  /* #973: @69 = zeros(1x4) */
  casadi_clear(w69, 4);
  /* #974: @74 = @74' */
  /* #975: @69 = mac(@74,@44,@69) */
  casadi_mtimes((&w74), casadi_s21, w44, casadi_s2, w69, casadi_s1, w, 0);
  /* #976: @69 = @69' */
  /* #977: @64 = (@64+@69) */
  for (i=0, rr=w64, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #978: {@74, @61, @62, @79} = vertsplit(@64) */
  w74 = w64[0];
  w61 = w64[1];
  w62 = w64[2];
  w79 = w64[3];
  /* #979: @29 = zeros(13x1) */
  casadi_clear(w29, 13);
  /* #980: @64 = zeros(4x1) */
  casadi_clear(w64, 4);
  /* #981: @66 = 00 */
  /* #982: @67 = 00 */
  /* #983: @68 = 00 */
  /* #984: @59 = (-@58) */
  w59 = (- w58 );
  /* #985: @57 = vertcat(@66, @67, @68, @59) */
  rr=(&w57);
  *rr++ = w59;
  /* #986: @57 = (@57/@10) */
  w57 /= w10;
  /* #987: @69 = dense(@57) */
  casadi_densify((&w57), casadi_s22, w69, 0);
  /* #988: @57 = project(@34) */
  casadi_sparsify(w34, (&w57), casadi_s22, 0);
  /* #989: @59 = @58[0] */
  for (rr=(&w59), ss=(&w58)+0; ss!=(&w58)+1; ss+=1) *rr++ = *ss;
  /* #990: @58 = dot(@57, @59) */
  w58 = casadi_dot(1, (&w57), (&w59));
  /* #991: @58 = (@58/@10) */
  w58 /= w10;
  /* #992: @33 = (@33*@58) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) *= w58;
  /* #993: @69 = (@69-@33) */
  for (i=0, rr=w69, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #994: {@57, @82, @75, @81} = vertsplit(@69) */
  w57 = w69[0];
  w82 = w69[1];
  w75 = w69[2];
  w81 = w69[3];
  /* #995: @53 = (@6*@57) */
  w53  = (w6*w57);
  /* #996: @52 = (@7*@82) */
  w52  = (w7*w82);
  /* #997: @53 = (@53-@52) */
  w53 -= w52;
  /* #998: @52 = (@8*@75) */
  w52  = (w8*w75);
  /* #999: @53 = (@53-@52) */
  w53 -= w52;
  /* #1000: @52 = (@9*@81) */
  w52  = (w9*w81);
  /* #1001: @53 = (@53-@52) */
  w53 -= w52;
  /* #1002: @52 = (@7*@57) */
  w52  = (w7*w57);
  /* #1003: @80 = (@6*@82) */
  w80  = (w6*w82);
  /* #1004: @52 = (@52+@80) */
  w52 += w80;
  /* #1005: @80 = (@9*@75) */
  w80  = (w9*w75);
  /* #1006: @52 = (@52+@80) */
  w52 += w80;
  /* #1007: @80 = (@8*@81) */
  w80  = (w8*w81);
  /* #1008: @52 = (@52-@80) */
  w52 -= w80;
  /* #1009: @80 = (@8*@57) */
  w80  = (w8*w57);
  /* #1010: @83 = (@9*@82) */
  w83  = (w9*w82);
  /* #1011: @80 = (@80-@83) */
  w80 -= w83;
  /* #1012: @83 = (@6*@75) */
  w83  = (w6*w75);
  /* #1013: @80 = (@80+@83) */
  w80 += w83;
  /* #1014: @83 = (@7*@81) */
  w83  = (w7*w81);
  /* #1015: @80 = (@80+@83) */
  w80 += w83;
  /* #1016: @57 = (@9*@57) */
  w57  = (w9*w57);
  /* #1017: @82 = (@8*@82) */
  w82  = (w8*w82);
  /* #1018: @57 = (@57+@82) */
  w57 += w82;
  /* #1019: @75 = (@7*@75) */
  w75  = (w7*w75);
  /* #1020: @57 = (@57-@75) */
  w57 -= w75;
  /* #1021: @81 = (@6*@81) */
  w81  = (w6*w81);
  /* #1022: @57 = (@57+@81) */
  w57 += w81;
  /* #1023: @33 = vertcat(@53, @52, @80, @57) */
  rr=w33;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w80;
  *rr++ = w57;
  /* #1024: @70 = (@14*@33) */
  for (i=0, rr=w70, cs=w33; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #1025: @33 = (@15*@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #1026: @70 = (@70-@33) */
  for (i=0, rr=w70, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #1027: @26 = @70[1:4] */
  for (rr=w26, ss=w70+1; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #1028: @15 = dot(@37, @26) */
  w15 = casadi_dot(3, w37, w26);
  /* #1029: @15 = (@15/@16) */
  w15 /= w16;
  /* #1030: @14 = (@15/@5) */
  w14  = (w15/w5);
  /* #1031: @20 = (@20*@15) */
  w20 *= w15;
  /* #1032: @53 = @70[0] */
  for (rr=(&w53), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #1033: @22 = (@22*@53) */
  w22 *= w53;
  /* #1034: @20 = (@20+@22) */
  w20 += w22;
  /* #1035: @71 = (@71*@20) */
  w71 *= w20;
  /* #1036: @14 = (@14-@71) */
  w14 -= w71;
  /* #1037: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #1038: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #1039: @2 = (2.*@26) */
  for (i=0, rr=w2, cs=w26; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1040: @48 = (@11*@2) */
  for (i=0, rr=w48, cs=w2; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #1041: @17 = (@17*@15) */
  w17 *= w15;
  /* #1042: @72 = (@72*@53) */
  w72 *= w53;
  /* #1043: @17 = (@17-@72) */
  w17 -= w72;
  /* #1044: @1 = (@38*@17) */
  for (i=0, rr=w1, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #1045: @48 = (@48+@1) */
  for (i=0, rr=w48, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #1046: @48 = (@48/@16) */
  for (i=0, rr=w48; i<3; ++i) (*rr++) /= w16;
  /* #1047: @39 = (@39*@15) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) *= w15;
  /* #1048: @48 = (@48-@39) */
  for (i=0, rr=w48, cs=w39; i<3; ++i) (*rr++) -= (*cs++);
  /* #1049: @39 = @48' */
  casadi_copy(w48, 3, w39);
  /* #1050: @30 = mac(@39,@41,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1051: @30 = @30' */
  /* #1052: @39 = zeros(1x3) */
  casadi_clear(w39, 3);
  /* #1053: @1 = @48' */
  casadi_copy(w48, 3, w1);
  /* #1054: @39 = mac(@1,@46,@39) */
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1055: @39 = @39' */
  /* #1056: @30 = (@30+@39) */
  for (i=0, rr=w30, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #1057: @39 = (@30/@16) */
  for (i=0, rr=w39, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)/w16);
  /* #1058: @49 = (@49*@15) */
  for (i=0, rr=w49; i<3; ++i) (*rr++) *= w15;
  /* #1059: @39 = (@39-@49) */
  for (i=0, rr=w39, cs=w49; i<3; ++i) (*rr++) -= (*cs++);
  /* #1060: @72 = dot(@38, @39) */
  w72 = casadi_dot(3, w38, w39);
  /* #1061: @71 = dot(@2, @40) */
  w71 = casadi_dot(3, w2, w40);
  /* #1062: @72 = (@72+@71) */
  w72 += w71;
  /* #1063: @4 = (@4*@72) */
  w4 *= w72;
  /* #1064: @14 = (@14+@4) */
  w14 += w4;
  /* #1065: @14 = (-@14) */
  w14 = (- w14 );
  /* #1066: (@64[0] += @14) */
  for (rr=w64+0, ss=(&w14); rr!=w64+1; rr+=1) *rr += *ss++;
  /* #1067: @14 = dot(@47, @30) */
  w14 = casadi_dot(3, w47, w30);
  /* #1068: @48 = (@48/@16) */
  for (i=0, rr=w48; i<3; ++i) (*rr++) /= w16;
  /* #1069: @45 = (@45*@15) */
  for (i=0, rr=w45; i<3; ++i) (*rr++) *= w15;
  /* #1070: @48 = (@48-@45) */
  for (i=0, rr=w48, cs=w45; i<3; ++i) (*rr++) -= (*cs++);
  /* #1071: @48 = (-@48) */
  for (i=0, rr=w48, cs=w48; i<3; ++i) *rr++ = (- *cs++ );
  /* #1072: @4 = dot(@48, @31) */
  w4 = casadi_dot(3, w48, w31);
  /* #1073: @14 = (@14+@4) */
  w14 += w4;
  /* #1074: @53 = (@53/@5) */
  w53 /= w5;
  /* #1075: @77 = (@77*@20) */
  w77 *= w20;
  /* #1076: @53 = (@53-@77) */
  w53 -= w77;
  /* #1077: @0 = (@0*@53) */
  w0 *= w53;
  /* #1078: @18 = (@18*@72) */
  w18 *= w72;
  /* #1079: @0 = (@0+@18) */
  w0 += w18;
  /* #1080: @14 = (@14+@0) */
  w14 += w0;
  /* #1081: @14 = (@14/@16) */
  w14 /= w16;
  /* #1082: @21 = (@21*@15) */
  w21 *= w15;
  /* #1083: @14 = (@14-@21) */
  w14 -= w21;
  /* #1084: @37 = (@37*@14) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w14;
  /* #1085: @26 = (@12*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #1086: @37 = (@37+@26) */
  for (i=0, rr=w37, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #1087: @40 = (@40*@17) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w17;
  /* #1088: @39 = (@11*@39) */
  for (i=0, rr=w39, cs=w39; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #1089: @40 = (@40+@39) */
  for (i=0, rr=w40, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #1090: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1091: @37 = (@37+@40) */
  for (i=0, rr=w37, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #1092: (@64[1:4] += @37) */
  for (rr=w64+1, ss=w37; rr!=w64+4; rr+=1) *rr += *ss++;
  /* #1093: @70 = (@13*@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #1094: @64 = (@19*@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w19*(*cs++));
  /* #1095: @70 = (@70-@64) */
  for (i=0, rr=w70, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #1096: {@19, @13, @11, @17} = vertsplit(@70) */
  w19 = w70[0];
  w13 = w70[1];
  w11 = w70[2];
  w17 = w70[3];
  /* #1097: @12 = (@9*@17) */
  w12  = (w9*w17);
  /* #1098: @14 = (@8*@11) */
  w14  = (w8*w11);
  /* #1099: @12 = (@12+@14) */
  w12 += w14;
  /* #1100: @14 = (@7*@13) */
  w14  = (w7*w13);
  /* #1101: @12 = (@12+@14) */
  w12 += w14;
  /* #1102: @14 = (@6*@19) */
  w14  = (w6*w19);
  /* #1103: @12 = (@12+@14) */
  w12 += w14;
  /* #1104: @14 = (@8*@17) */
  w14  = (w8*w17);
  /* #1105: @21 = (@9*@11) */
  w21  = (w9*w11);
  /* #1106: @14 = (@14-@21) */
  w14 -= w21;
  /* #1107: @21 = (@6*@13) */
  w21  = (w6*w13);
  /* #1108: @14 = (@14+@21) */
  w14 += w21;
  /* #1109: @21 = (@7*@19) */
  w21  = (w7*w19);
  /* #1110: @14 = (@14-@21) */
  w14 -= w21;
  /* #1111: @21 = (@6*@11) */
  w21  = (w6*w11);
  /* #1112: @15 = (@7*@17) */
  w15  = (w7*w17);
  /* #1113: @21 = (@21-@15) */
  w21 -= w15;
  /* #1114: @15 = (@9*@13) */
  w15  = (w9*w13);
  /* #1115: @21 = (@21+@15) */
  w21 += w15;
  /* #1116: @15 = (@8*@19) */
  w15  = (w8*w19);
  /* #1117: @21 = (@21-@15) */
  w21 -= w15;
  /* #1118: @6 = (@6*@17) */
  w6 *= w17;
  /* #1119: @7 = (@7*@11) */
  w7 *= w11;
  /* #1120: @6 = (@6+@7) */
  w6 += w7;
  /* #1121: @8 = (@8*@13) */
  w8 *= w13;
  /* #1122: @6 = (@6-@8) */
  w6 -= w8;
  /* #1123: @9 = (@9*@19) */
  w9 *= w19;
  /* #1124: @6 = (@6-@9) */
  w6 -= w9;
  /* #1125: @70 = vertcat(@12, @14, @21, @6) */
  rr=w70;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w21;
  *rr++ = w6;
  /* #1126: @12 = dot(@42, @70) */
  w12 = casadi_dot(4, w42, w70);
  /* #1127: @69 = (@69/@10) */
  for (i=0, rr=w69; i<4; ++i) (*rr++) /= w10;
  /* #1128: @36 = (@36*@58) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) *= w58;
  /* #1129: @69 = (@69-@36) */
  for (i=0, rr=w69, cs=w36; i<4; ++i) (*rr++) -= (*cs++);
  /* #1130: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #1131: @14 = dot(@69, @50) */
  w14 = casadi_dot(4, w69, w50);
  /* #1132: @12 = (@12+@14) */
  w12 += w14;
  /* #1133: @12 = (@12/@10) */
  w12 /= w10;
  /* #1134: @78 = (@78*@58) */
  w78 *= w58;
  /* #1135: @12 = (@12-@78) */
  w12 -= w78;
  /* #1136: @34 = (@34*@12) */
  for (i=0, rr=w34; i<4; ++i) (*rr++) *= w12;
  /* #1137: @24 = (@24*@59) */
  w24 *= w59;
  /* #1138: @69 = dense(@24) */
  casadi_densify((&w24), casadi_s22, w69, 0);
  /* #1139: @34 = (@34+@69) */
  for (i=0, rr=w34, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #1140: (@29[6:10] += @34) */
  for (rr=w29+6, ss=w34; rr!=w29+10; rr+=1) *rr += *ss++;
  /* #1141: {@24, @59, @12, @78, @14, @21, @6, @9, @19, @8, @13, @7, @11} = vertsplit(@29) */
  w24 = w29[0];
  w59 = w29[1];
  w12 = w29[2];
  w78 = w29[3];
  w14 = w29[4];
  w21 = w29[5];
  w6 = w29[6];
  w9 = w29[7];
  w19 = w29[8];
  w8 = w29[9];
  w13 = w29[10];
  w7 = w29[11];
  w11 = w29[12];
  /* #1142: @70 = (@70/@10) */
  for (i=0, rr=w70; i<4; ++i) (*rr++) /= w10;
  /* #1143: @35 = (@35*@58) */
  for (i=0, rr=w35; i<4; ++i) (*rr++) *= w58;
  /* #1144: @70 = (@70-@35) */
  for (i=0, rr=w70, cs=w35; i<4; ++i) (*rr++) -= (*cs++);
  /* #1145: {@58, @10, @17, @15} = vertsplit(@70) */
  w58 = w70[0];
  w10 = w70[1];
  w17 = w70[2];
  w15 = w70[3];
  /* #1146: @58 = (@58+@6) */
  w58 += w6;
  /* #1147: @9 = (@9-@10) */
  w9 -= w10;
  /* #1148: @19 = (@19-@17) */
  w19 -= w17;
  /* #1149: @8 = (@8-@15) */
  w8 -= w15;
  /* #1150: @88 = vertcat(@74, @61, @62, @79, @24, @59, @12, @78, @14, @21, @58, @9, @19, @8, @13, @7, @11) */
  rr=w88;
  *rr++ = w74;
  *rr++ = w61;
  *rr++ = w62;
  *rr++ = w79;
  *rr++ = w24;
  *rr++ = w59;
  *rr++ = w12;
  *rr++ = w78;
  *rr++ = w14;
  *rr++ = w21;
  *rr++ = w58;
  *rr++ = w9;
  *rr++ = w19;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w7;
  *rr++ = w11;
  /* #1151: @91 = @88[:20:10;:4] */
  for (rr=w91, ss=w88+0; ss!=w88+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1152: (@63[:50:25;12:16] = @91) */
  for (rr=w63+0, ss=w91; rr!=w63+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #1153: @91 = @88[:20:10;:4] */
  for (rr=w91, ss=w88+0; ss!=w88+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1154: (@63[:50:25;3:19:4] = @91) */
  for (rr=w63+0, ss=w91; rr!=w63+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #1155: @92 = @63' */
  casadi_trans(w63,casadi_s23, w92, casadi_s23, iw);
  /* #1156: output[2][0] = @92 */
  casadi_copy(w92, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s24;
    case 1: return casadi_s25;
    case 2: return casadi_s26;
    case 3: return casadi_s27;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s28;
    case 1: return casadi_s29;
    case 2: return casadi_s23;
    case 3: return casadi_s26;
    case 4: return casadi_s30;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 400;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
