/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[7] = {13, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s5[22] = {1, 13, 0, 1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s7[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[13] = {13, 4, 0, 3, 4, 5, 6, 3, 4, 5, 10, 11, 12};
static const casadi_int casadi_s9[22] = {4, 13, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5, 6, 0, 0, 0, 1, 2, 3};
static const casadi_int casadi_s10[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[19] = {1, 13, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0};
static const casadi_int casadi_s13[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s14[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s15[10] = {13, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s16[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[3] = {0, 0, 0};
static const casadi_int casadi_s18[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s19[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s20[22] = {17, 2, 0, 11, 17, 0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s21[3] = {2, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c3[9] = {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0., 1.5968700000000000e-03};
static const casadi_real casadi_c4[2] = {20., 8.};

/* Drone_ode_complete_2_constr_h_fun_jac_uxt_zt:(i0[13],i1[4],i2[],i3[20])->(o0[2],o1[17x2,17nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+14, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+37, *w20=w+40, *w21=w+49, *w22=w+58, w23, w24, w25, w26, *w27=w+71, w28, *w29=w+76, w30, *w31=w+81, w32, w33, w34, *w35=w+93, *w36=w+96, w37, w38, w39, w40, w41, w42, w43, *w44=w+106, *w45=w+110, *w46=w+113, *w47=w+116, *w48=w+119, w49, w50, w51, *w52=w+125, *w53=w+138, w54, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, *w65=w+162, w66, w67, w68, w69, w70, w71, w72, w73, w74, w75, w76, w77, w78, w79, w80, *w81=w+183, *w82=w+189, w88, w89, w90, *w91=w+198, *w92=w+204, *w93=w+210, *w94=w+212, *w95=w+214, w96, w97, w98, w99, w100, w101, w102, w103, *w104=w+224, *w105=w+244, *w106=w+261, *w107=w+265, *w108=w+268, *w109=w+281, *w110=w+287, *w111=w+293, *w112=w+306, *w113=w+319, *w114=w+332, *w115=w+345, *w116=w+358, *w117=w+371, *w118=w+380;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(13x1,6nz) */
  casadi_clear(w1, 6);
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[3][17] */
  w3 = arg[3] ? arg[3][17] : 0;
  /* #4: @4 = (@2-@3) */
  w4  = (w2-w3);
  /* #5: @5 = (2.*@4) */
  w5 = (2.* w4 );
  /* #6: @6 = input[0][1] */
  w6 = arg[0] ? arg[0][1] : 0;
  /* #7: @7 = input[3][18] */
  w7 = arg[3] ? arg[3][18] : 0;
  /* #8: @8 = (@6-@7) */
  w8  = (w6-w7);
  /* #9: @9 = (2.*@8) */
  w9 = (2.* w8 );
  /* #10: @10 = sq(@4) */
  w10 = casadi_sq( w4 );
  /* #11: @11 = sq(@8) */
  w11 = casadi_sq( w8 );
  /* #12: @10 = (@10+@11) */
  w10 += w11;
  /* #13: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #14: @12 = input[3][19] */
  w12 = arg[3] ? arg[3][19] : 0;
  /* #15: @13 = (@11-@12) */
  w13  = (w11-w12);
  /* #16: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #17: @10 = (@10+@14) */
  w10 += w14;
  /* #18: @10 = sqrt(@10) */
  w10 = sqrt( w10 );
  /* #19: @14 = (2.*@10) */
  w14 = (2.* w10 );
  /* #20: @9 = (@9/@14) */
  w9 /= w14;
  /* #21: @15 = (@9/@14) */
  w15  = (w9/w14);
  /* #22: @16 = input[0][3] */
  w16 = arg[0] ? arg[0][3] : 0;
  /* #23: @17 = input[0][4] */
  w17 = arg[0] ? arg[0][4] : 0;
  /* #24: @18 = input[0][5] */
  w18 = arg[0] ? arg[0][5] : 0;
  /* #25: @19 = zeros(3x1) */
  casadi_clear(w19, 3);
  /* #26: @20 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w20);
  /* #27: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #28: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #29: @23 = input[0][6] */
  w23 = arg[0] ? arg[0][6] : 0;
  /* #30: @24 = input[0][7] */
  w24 = arg[0] ? arg[0][7] : 0;
  /* #31: @25 = input[0][8] */
  w25 = arg[0] ? arg[0][8] : 0;
  /* #32: @26 = input[0][9] */
  w26 = arg[0] ? arg[0][9] : 0;
  /* #33: @27 = vertcat(@23, @24, @25, @26) */
  rr=w27;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  /* #34: @28 = ||@27||_F */
  w28 = sqrt(casadi_dot(4, w27, w27));
  /* #35: @29 = (@27/@28) */
  for (i=0, rr=w29, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)/w28);
  /* #36: @30 = @29[3] */
  for (rr=(&w30), ss=w29+3; ss!=w29+4; ss+=1) *rr++ = *ss;
  /* #37: @30 = (-@30) */
  w30 = (- w30 );
  /* #38: (@22[3] = @30) */
  for (rr=w22+3, ss=(&w30); rr!=w22+4; rr+=1) *rr = *ss++;
  /* #39: @30 = @29[2] */
  for (rr=(&w30), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #40: (@22[6] = @30) */
  for (rr=w22+6, ss=(&w30); rr!=w22+7; rr+=1) *rr = *ss++;
  /* #41: @30 = @29[1] */
  for (rr=(&w30), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #42: @30 = (-@30) */
  w30 = (- w30 );
  /* #43: (@22[7] = @30) */
  for (rr=w22+7, ss=(&w30); rr!=w22+8; rr+=1) *rr = *ss++;
  /* #44: @30 = @29[3] */
  for (rr=(&w30), ss=w29+3; ss!=w29+4; ss+=1) *rr++ = *ss;
  /* #45: (@22[1] = @30) */
  for (rr=w22+1, ss=(&w30); rr!=w22+2; rr+=1) *rr = *ss++;
  /* #46: @30 = @29[2] */
  for (rr=(&w30), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #47: @30 = (-@30) */
  w30 = (- w30 );
  /* #48: (@22[2] = @30) */
  for (rr=w22+2, ss=(&w30); rr!=w22+3; rr+=1) *rr = *ss++;
  /* #49: @30 = @29[1] */
  for (rr=(&w30), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #50: (@22[5] = @30) */
  for (rr=w22+5, ss=(&w30); rr!=w22+6; rr+=1) *rr = *ss++;
  /* #51: @31 = (2.*@22) */
  for (i=0, rr=w31, cs=w22; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #52: @21 = mac(@31,@22,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w31+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #53: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<9; ++i) (*rr++) += (*cs++);
  /* #54: @30 = @29[0] */
  for (rr=(&w30), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #55: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #56: @21 = (@30*@22) */
  for (i=0, rr=w21, cs=w22; i<9; ++i) (*rr++)  = (w30*(*cs++));
  /* #57: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<9; ++i) (*rr++) += (*cs++);
  /* #58: @32 = 0 */
  w32 = 0.;
  /* #59: @33 = 0 */
  w33 = 0.;
  /* #60: @34 = input[1][0] */
  w34 = arg[1] ? arg[1][0] : 0;
  /* #61: @35 = vertcat(@32, @33, @34) */
  rr=w35;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  /* #62: @19 = mac(@20,@35,@19) */
  for (i=0, rr=w19; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #63: @32 = 0.85 */
  w32 = 8.4999999999999998e-01;
  /* #64: @19 = (@19/@32) */
  for (i=0, rr=w19; i<3; ++i) (*rr++) /= w32;
  /* #65: @36 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w36);
  /* #66: @32 = 9.81 */
  w32 = 9.8100000000000005e+00;
  /* #67: @36 = (@36*@32) */
  for (i=0, rr=w36; i<3; ++i) (*rr++) *= w32;
  /* #68: @19 = (@19-@36) */
  for (i=0, rr=w19, cs=w36; i<3; ++i) (*rr++) -= (*cs++);
  /* #69: @32 = 0.5 */
  w32 = 5.0000000000000000e-01;
  /* #70: @33 = input[0][10] */
  w33 = arg[0] ? arg[0][10] : 0;
  /* #71: @37 = (@24*@33) */
  w37  = (w24*w33);
  /* #72: @37 = (-@37) */
  w37 = (- w37 );
  /* #73: @38 = input[0][11] */
  w38 = arg[0] ? arg[0][11] : 0;
  /* #74: @39 = (@25*@38) */
  w39  = (w25*w38);
  /* #75: @37 = (@37-@39) */
  w37 -= w39;
  /* #76: @39 = input[0][12] */
  w39 = arg[0] ? arg[0][12] : 0;
  /* #77: @40 = (@26*@39) */
  w40  = (w26*w39);
  /* #78: @37 = (@37-@40) */
  w37 -= w40;
  /* #79: @40 = (@23*@33) */
  w40  = (w23*w33);
  /* #80: @41 = (@25*@39) */
  w41  = (w25*w39);
  /* #81: @40 = (@40+@41) */
  w40 += w41;
  /* #82: @41 = (@26*@38) */
  w41  = (w26*w38);
  /* #83: @40 = (@40-@41) */
  w40 -= w41;
  /* #84: @41 = (@23*@38) */
  w41  = (w23*w38);
  /* #85: @42 = (@24*@39) */
  w42  = (w24*w39);
  /* #86: @41 = (@41-@42) */
  w41 -= w42;
  /* #87: @42 = (@26*@33) */
  w42  = (w26*w33);
  /* #88: @41 = (@41+@42) */
  w41 += w42;
  /* #89: @42 = (@23*@39) */
  w42  = (w23*w39);
  /* #90: @43 = (@24*@38) */
  w43  = (w24*w38);
  /* #91: @42 = (@42+@43) */
  w42 += w43;
  /* #92: @43 = (@25*@33) */
  w43  = (w25*w33);
  /* #93: @42 = (@42-@43) */
  w42 -= w43;
  /* #94: @44 = vertcat(@37, @40, @41, @42) */
  rr=w44;
  *rr++ = w37;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  /* #95: @44 = (@32*@44) */
  for (i=0, rr=w44, cs=w44; i<4; ++i) (*rr++)  = (w32*(*cs++));
  /* #96: @36 = zeros(3x1) */
  casadi_clear(w36, 3);
  /* #97: @45 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c2, 3, w45);
  /* #98: @37 = input[1][1] */
  w37 = arg[1] ? arg[1][1] : 0;
  /* #99: @40 = input[1][2] */
  w40 = arg[1] ? arg[1][2] : 0;
  /* #100: @41 = input[1][3] */
  w41 = arg[1] ? arg[1][3] : 0;
  /* #101: @46 = vertcat(@37, @40, @41) */
  rr=w46;
  *rr++ = w37;
  *rr++ = w40;
  *rr++ = w41;
  /* #102: @47 = zeros(3x1) */
  casadi_clear(w47, 3);
  /* #103: @21 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  casadi_copy(casadi_c3, 9, w21);
  /* #104: @48 = vertcat(@33, @38, @39) */
  rr=w48;
  *rr++ = w33;
  *rr++ = w38;
  *rr++ = w39;
  /* #105: @47 = mac(@21,@48,@47) */
  for (i=0, rr=w47; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #106: @42 = @47[2] */
  for (rr=(&w42), ss=w47+2; ss!=w47+3; ss+=1) *rr++ = *ss;
  /* #107: @43 = (@38*@42) */
  w43  = (w38*w42);
  /* #108: @49 = @47[1] */
  for (rr=(&w49), ss=w47+1; ss!=w47+2; ss+=1) *rr++ = *ss;
  /* #109: @50 = (@39*@49) */
  w50  = (w39*w49);
  /* #110: @43 = (@43-@50) */
  w43 -= w50;
  /* #111: @50 = @47[0] */
  for (rr=(&w50), ss=w47+0; ss!=w47+1; ss+=1) *rr++ = *ss;
  /* #112: @51 = (@39*@50) */
  w51  = (w39*w50);
  /* #113: @42 = (@33*@42) */
  w42  = (w33*w42);
  /* #114: @51 = (@51-@42) */
  w51 -= w42;
  /* #115: @49 = (@33*@49) */
  w49  = (w33*w49);
  /* #116: @50 = (@38*@50) */
  w50  = (w38*w50);
  /* #117: @49 = (@49-@50) */
  w49 -= w50;
  /* #118: @47 = vertcat(@43, @51, @49) */
  rr=w47;
  *rr++ = w43;
  *rr++ = w51;
  *rr++ = w49;
  /* #119: @46 = (@46-@47) */
  for (i=0, rr=w46, cs=w47; i<3; ++i) (*rr++) -= (*cs++);
  /* #120: @36 = mac(@45,@46,@36) */
  casadi_mtimes(w45, casadi_s1, w46, casadi_s0, w36, casadi_s0, w, 0);
  /* #121: @52 = vertcat(@16, @17, @18, @19, @44, @36) */
  rr=w52;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  /* #122: @43 = 0 */
  w43 = 0.;
  /* #123: @53 = @52; (@53[2] = @43) */
  casadi_copy(w52, 13, w53);
  for (rr=w53+2, ss=(&w43); rr!=w53+3; rr+=1) *rr = *ss++;
  /* #124: @43 = @53[1] */
  for (rr=(&w43), ss=w53+1; ss!=w53+2; ss+=1) *rr++ = *ss;
  /* #125: @51 = (@15*@43) */
  w51  = (w15*w43);
  /* #126: @51 = (-@51) */
  w51 = (- w51 );
  /* #127: @49 = (2.*@13) */
  w49 = (2.* w13 );
  /* #128: @49 = (@49/@14) */
  w49 /= w14;
  /* #129: @50 = (@49/@14) */
  w50  = (w49/w14);
  /* #130: @42 = (@50*@18) */
  w42  = (w50*w18);
  /* #131: @51 = (@51-@42) */
  w51 -= w42;
  /* #132: @42 = (2.*@4) */
  w42 = (2.* w4 );
  /* #133: @42 = (@42/@14) */
  w42 /= w14;
  /* #134: @54 = (@42/@14) */
  w54  = (w42/w14);
  /* #135: @55 = 0 */
  w55 = 0.;
  /* #136: (@53[1] = @55) */
  for (rr=w53+1, ss=(&w55); rr!=w53+2; rr+=1) *rr = *ss++;
  /* #137: @55 = @53[0] */
  for (rr=(&w55), ss=w53+0; ss!=w53+1; ss+=1) *rr++ = *ss;
  /* #138: @56 = (@54*@55) */
  w56  = (w54*w55);
  /* #139: @51 = (@51-@56) */
  w51 -= w56;
  /* #140: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #141: @56 = (2.*@10) */
  w56 = (2.* w10 );
  /* #142: @51 = (@51/@56) */
  w51 /= w56;
  /* #143: @57 = (@5*@51) */
  w57  = (w5*w51);
  /* #144: @58 = (@55/@14) */
  w58  = (w55/w14);
  /* #145: @59 = (2.*@58) */
  w59 = (2.* w58 );
  /* #146: @57 = (@57+@59) */
  w57 += w59;
  /* #147: (@1[0] = @57) */
  for (rr=w1+0, ss=(&w57); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #148: @57 = (@43/@14) */
  w57  = (w43/w14);
  /* #149: @59 = (2.*@57) */
  w59 = (2.* w57 );
  /* #150: @60 = (2.*@8) */
  w60 = (2.* w8 );
  /* #151: @61 = (@60*@51) */
  w61  = (w60*w51);
  /* #152: @59 = (@59+@61) */
  w59 += w61;
  /* #153: (@1[1] = @59) */
  for (rr=w1+1, ss=(&w59); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #154: @59 = (@18/@14) */
  w59  = (w18/w14);
  /* #155: @61 = (2.*@59) */
  w61 = (2.* w59 );
  /* #156: @62 = (2.*@13) */
  w62 = (2.* w13 );
  /* #157: @63 = (@62*@51) */
  w63  = (w62*w51);
  /* #158: @61 = (@61+@63) */
  w61 += w63;
  /* #159: (@1[2] = @61) */
  for (rr=w1+2, ss=(&w61); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #160: @19 = zeros(13x1,3nz) */
  casadi_clear(w19, 3);
  /* #161: (@19[0] = @42) */
  for (rr=w19+0, ss=(&w42); rr!=w19+1; rr+=1) *rr = *ss++;
  /* #162: (@19[1] = @9) */
  for (rr=w19+1, ss=(&w9); rr!=w19+2; rr+=1) *rr = *ss++;
  /* #163: (@19[2] = @49) */
  for (rr=w19+2, ss=(&w49); rr!=w19+3; rr+=1) *rr = *ss++;
  /* #164: @53 = dense(@19) */
  casadi_densify(w19, casadi_s2, w53, 0);
  /* #165: {@61, @63, @64, NULL, NULL, NULL} = vertsplit(@53) */
  w61 = w53[0];
  w63 = w53[1];
  w64 = w53[2];
  /* #166: (@1[3] = @61) */
  for (rr=w1+3, ss=(&w61); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #167: (@1[4] = @63) */
  for (rr=w1+4, ss=(&w63); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #168: (@1[5] = @64) */
  for (rr=w1+5, ss=(&w64); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #169: @65 = @1' */
  casadi_copy(w1, 6, w65);
  /* #170: @0 = mac(@65,@52,@0) */
  casadi_mtimes(w65, casadi_s5, w52, casadi_s4, (&w0), casadi_s3, w, 0);
  /* #171: @64 = 0 */
  w64 = 0.;
  /* #172: @63 = zeros(1x4,1nz) */
  w63 = 0.;
  /* #173: @65 = zeros(13x1,6nz) */
  casadi_clear(w65, 6);
  /* #174: @61 = (2.*@4) */
  w61 = (2.* w4 );
  /* #175: @66 = (@9/@14) */
  w66  = (w9/w14);
  /* #176: @67 = 0 */
  w67 = 0.;
  /* #177: @53 = @52; (@53[2] = @67) */
  casadi_copy(w52, 13, w53);
  for (rr=w53+2, ss=(&w67); rr!=w53+3; rr+=1) *rr = *ss++;
  /* #178: @67 = @53[1] */
  for (rr=(&w67), ss=w53+1; ss!=w53+2; ss+=1) *rr++ = *ss;
  /* #179: @68 = (@66*@67) */
  w68  = (w66*w67);
  /* #180: @68 = (-@68) */
  w68 = (- w68 );
  /* #181: @69 = (@49/@14) */
  w69  = (w49/w14);
  /* #182: @70 = (@69*@18) */
  w70  = (w69*w18);
  /* #183: @68 = (@68-@70) */
  w68 -= w70;
  /* #184: @70 = (@42/@14) */
  w70  = (w42/w14);
  /* #185: @71 = 0 */
  w71 = 0.;
  /* #186: (@53[1] = @71) */
  for (rr=w53+1, ss=(&w71); rr!=w53+2; rr+=1) *rr = *ss++;
  /* #187: @71 = @53[0] */
  for (rr=(&w71), ss=w53+0; ss!=w53+1; ss+=1) *rr++ = *ss;
  /* #188: @72 = (@70*@71) */
  w72  = (w70*w71);
  /* #189: @68 = (@68-@72) */
  w68 -= w72;
  /* #190: @68 = (2.*@68) */
  w68 = (2.* w68 );
  /* #191: @72 = (2.*@10) */
  w72 = (2.* w10 );
  /* #192: @68 = (@68/@72) */
  w68 /= w72;
  /* #193: @73 = (@61*@68) */
  w73  = (w61*w68);
  /* #194: @74 = (@71/@14) */
  w74  = (w71/w14);
  /* #195: @75 = (2.*@74) */
  w75 = (2.* w74 );
  /* #196: @73 = (@73+@75) */
  w73 += w75;
  /* #197: (@65[0] = @73) */
  for (rr=w65+0, ss=(&w73); rr!=w65+1; rr+=1) *rr = *ss++;
  /* #198: @73 = (@67/@14) */
  w73  = (w67/w14);
  /* #199: @75 = (2.*@73) */
  w75 = (2.* w73 );
  /* #200: @76 = (2.*@8) */
  w76 = (2.* w8 );
  /* #201: @77 = (@76*@68) */
  w77  = (w76*w68);
  /* #202: @75 = (@75+@77) */
  w75 += w77;
  /* #203: (@65[1] = @75) */
  for (rr=w65+1, ss=(&w75); rr!=w65+2; rr+=1) *rr = *ss++;
  /* #204: @75 = (@18/@14) */
  w75  = (w18/w14);
  /* #205: @77 = (2.*@75) */
  w77 = (2.* w75 );
  /* #206: @78 = (2.*@13) */
  w78 = (2.* w13 );
  /* #207: @79 = (@78*@68) */
  w79  = (w78*w68);
  /* #208: @77 = (@77+@79) */
  w77 += w79;
  /* #209: (@65[2] = @77) */
  for (rr=w65+2, ss=(&w77); rr!=w65+3; rr+=1) *rr = *ss++;
  /* #210: @53 = dense(@19) */
  casadi_densify(w19, casadi_s2, w53, 0);
  /* #211: {@77, @79, @80, NULL, NULL, NULL} = vertsplit(@53) */
  w77 = w53[0];
  w79 = w53[1];
  w80 = w53[2];
  /* #212: (@65[3] = @77) */
  for (rr=w65+3, ss=(&w77); rr!=w65+4; rr+=1) *rr = *ss++;
  /* #213: (@65[4] = @79) */
  for (rr=w65+4, ss=(&w79); rr!=w65+5; rr+=1) *rr = *ss++;
  /* #214: (@65[5] = @80) */
  for (rr=w65+5, ss=(&w80); rr!=w65+6; rr+=1) *rr = *ss++;
  /* #215: @81 = @65' */
  casadi_copy(w65, 6, w81);
  /* #216: @82 = zeros(4x13,6nz) */
  casadi_clear(w82, 6);
  /* #217: @83 = 00 */
  /* #218: @84 = 00 */
  /* #219: @85 = 00 */
  /* #220: @80 = 1.17647 */
  w80 = 1.1764705882352942e+00;
  /* #221: @36 = zeros(3x1) */
  casadi_clear(w36, 3);
  /* #222: @86 = 00 */
  /* #223: @87 = 00 */
  /* #224: @44 = ones(4x1) */
  casadi_fill(w44, 4, 1.);
  /* #225: {@79, @77, @88, @89} = vertsplit(@44) */
  w79 = w44[0];
  w77 = w44[1];
  w88 = w44[2];
  w89 = w44[3];
  /* #226: @90 = vertcat(@86, @87, @79) */
  rr=(&w90);
  *rr++ = w79;
  /* #227: @36 = mac(@20,@90,@36) */
  casadi_mtimes(w20, casadi_s7, (&w90), casadi_s6, w36, casadi_s0, w, 0);
  /* #228: @36 = (@80*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) (*rr++)  = (w80*(*cs++));
  /* #229: @86 = zeros(4x1,0nz) */
  /* #230: @46 = zeros(3x1) */
  casadi_clear(w46, 3);
  /* #231: @47 = vertcat(@77, @88, @89) */
  rr=w47;
  *rr++ = w77;
  *rr++ = w88;
  *rr++ = w89;
  /* #232: @46 = mac(@45,@47,@46) */
  casadi_mtimes(w45, casadi_s1, w47, casadi_s0, w46, casadi_s0, w, 0);
  /* #233: @91 = vertcat(@83, @84, @85, @36, @86, @46) */
  rr=w91;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  /* #234: @92 = @91[:6] */
  for (rr=w92, ss=w91+0; ss!=w91+6; ss+=1) *rr++ = *ss;
  /* #235: (@82[:6] = @92) */
  for (rr=w82+0, ss=w92; rr!=w82+6; rr+=1) *rr = *ss++;
  /* #236: @92 = @82' */
  casadi_trans(w82,casadi_s9, w92, casadi_s8, iw);
  /* #237: @63 = mac(@81,@92,@63) */
  casadi_mtimes(w81, casadi_s5, w92, casadi_s8, (&w63), casadi_s10, w, 0);
  /* #238: @44 = vertcat(@34, @37, @40, @41) */
  rr=w44;
  *rr++ = w34;
  *rr++ = w37;
  *rr++ = w40;
  *rr++ = w41;
  /* #239: @64 = mac(@63,@44,@64) */
  casadi_mtimes((&w63), casadi_s10, w44, casadi_s11, (&w64), casadi_s3, w, 0);
  /* #240: @0 = (@0+@64) */
  w0 += w64;
  /* #241: @64 = 0 */
  w64 = 0.;
  /* #242: @93 = [20, 8] */
  casadi_copy(casadi_c4, 2, w93);
  /* #243: @94 = @93' */
  casadi_copy(w93, 2, w94);
  /* #244: @34 = 0.9 */
  w34 = 9.0000000000000002e-01;
  /* #245: @34 = (@10-@34) */
  w34  = (w10-w34);
  /* #246: @37 = 0 */
  w37 = 0.;
  /* #247: @36 = @19' */
  casadi_copy(w19, 3, w36);
  /* #248: @37 = mac(@36,@52,@37) */
  casadi_mtimes(w36, casadi_s12, w52, casadi_s4, (&w37), casadi_s3, w, 0);
  /* #249: @95 = vertcat(@34, @37) */
  rr=w95;
  *rr++ = w34;
  *rr++ = w37;
  /* #250: @64 = mac(@94,@95,@64) */
  for (i=0, rr=(&w64); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w94+j, tt=w95+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #251: @0 = (@0+@64) */
  w0 += w64;
  /* #252: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #253: @0 = 0 */
  w0 = 0.;
  /* #254: @64 = input[3][0] */
  w64 = arg[3] ? arg[3][0] : 0;
  /* #255: @34 = input[3][1] */
  w34 = arg[3] ? arg[3][1] : 0;
  /* #256: @37 = input[3][2] */
  w37 = arg[3] ? arg[3][2] : 0;
  /* #257: @40 = input[3][3] */
  w40 = arg[3] ? arg[3][3] : 0;
  /* #258: @41 = input[3][4] */
  w41 = arg[3] ? arg[3][4] : 0;
  /* #259: @77 = input[3][5] */
  w77 = arg[3] ? arg[3][5] : 0;
  /* #260: @88 = input[3][6] */
  w88 = arg[3] ? arg[3][6] : 0;
  /* #261: @89 = input[3][7] */
  w89 = arg[3] ? arg[3][7] : 0;
  /* #262: @79 = input[3][8] */
  w79 = arg[3] ? arg[3][8] : 0;
  /* #263: @96 = input[3][9] */
  w96 = arg[3] ? arg[3][9] : 0;
  /* #264: @97 = input[3][10] */
  w97 = arg[3] ? arg[3][10] : 0;
  /* #265: @98 = input[3][11] */
  w98 = arg[3] ? arg[3][11] : 0;
  /* #266: @99 = input[3][12] */
  w99 = arg[3] ? arg[3][12] : 0;
  /* #267: @100 = input[3][13] */
  w100 = arg[3] ? arg[3][13] : 0;
  /* #268: @101 = input[3][14] */
  w101 = arg[3] ? arg[3][14] : 0;
  /* #269: @102 = input[3][15] */
  w102 = arg[3] ? arg[3][15] : 0;
  /* #270: @103 = input[3][16] */
  w103 = arg[3] ? arg[3][16] : 0;
  /* #271: @104 = vertcat(@64, @34, @37, @40, @41, @77, @88, @89, @79, @96, @97, @98, @99, @100, @101, @102, @103, @3, @7, @12) */
  rr=w104;
  *rr++ = w64;
  *rr++ = w34;
  *rr++ = w37;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w77;
  *rr++ = w88;
  *rr++ = w89;
  *rr++ = w79;
  *rr++ = w96;
  *rr++ = w97;
  *rr++ = w98;
  *rr++ = w99;
  *rr++ = w100;
  *rr++ = w101;
  *rr++ = w102;
  *rr++ = w103;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w12;
  /* #272: @36 = @104[3:6] */
  for (rr=w36, ss=w104+3; ss!=w104+6; ss+=1) *rr++ = *ss;
  /* #273: @46 = @104[:3] */
  for (rr=w46, ss=w104+0; ss!=w104+3; ss+=1) *rr++ = *ss;
  /* #274: @53 = vertcat(@2, @6, @11, @16, @17, @18, @23, @24, @25, @26, @33, @38, @39) */
  rr=w53;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w33;
  *rr++ = w38;
  *rr++ = w39;
  /* #275: @45 = @53[:3] */
  for (rr=w45, ss=w53+0; ss!=w53+3; ss+=1) *rr++ = *ss;
  /* #276: @46 = (@46-@45) */
  for (i=0, rr=w46, cs=w45; i<3; ++i) (*rr++) -= (*cs++);
  /* #277: @2 = dot(@36, @46) */
  w2 = casadi_dot(3, w36, w46);
  /* #278: @46 = (@2*@36) */
  for (i=0, rr=w46, cs=w36; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #279: @45 = @46' */
  casadi_copy(w46, 3, w45);
  /* #280: @45 = (-@45) */
  for (i=0, rr=w45, cs=w45; i<3; ++i) *rr++ = (- *cs++ );
  /* #281: @47 = @53[3:6] */
  for (rr=w47, ss=w53+3; ss!=w53+6; ss+=1) *rr++ = *ss;
  /* #282: @2 = dot(@36, @47) */
  w2 = casadi_dot(3, w36, w47);
  /* #283: @47 = (@2*@36) */
  for (i=0, rr=w47, cs=w36; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #284: @0 = mac(@45,@47,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w45+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #285: @2 = 0.1 */
  w2 = 1.0000000000000001e-01;
  /* #286: @6 = 0 */
  w6 = 0.;
  /* #287: @11 = 0.5 */
  w11 = 5.0000000000000000e-01;
  /* #288: @48 = @46' */
  casadi_copy(w46, 3, w48);
  /* #289: @48 = (@11*@48) */
  for (i=0, rr=w48, cs=w48; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #290: @6 = mac(@48,@46,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w48+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #291: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #292: @0 = (@0+@6) */
  w0 += w6;
  /* #293: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #294: @105 = zeros(17x2,17nz) */
  casadi_clear(w105, 17);
  /* #295: @63 = @63' */
  /* #296: @0 = ones(2x1,1nz) */
  w0 = 1.;
  /* #297: {@6, NULL} = vertsplit(@0) */
  w6 = w0;
  /* #298: @63 = (@63*@6) */
  w63 *= w6;
  /* #299: @106 = dense(@63) */
  casadi_densify((&w63), casadi_s13, w106, 0);
  /* #300: {@63, NULL, NULL, NULL} = vertsplit(@106) */
  w63 = w106[0];
  /* #301: @107 = zeros(3x1) */
  casadi_clear(w107, 3);
  /* #302: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #303: @0 = 1.17647 */
  w0 = 1.1764705882352942e+00;
  /* #304: @93 = (@93*@6) */
  for (i=0, rr=w93; i<2; ++i) (*rr++) *= w6;
  /* #305: {@16, @17} = vertsplit(@93) */
  w16 = w93[0];
  w17 = w93[1];
  /* #306: @19 = (@19*@17) */
  for (i=0, rr=w19; i<3; ++i) (*rr++) *= w17;
  /* #307: @53 = dense(@19) */
  casadi_densify(w19, casadi_s2, w53, 0);
  /* #308: @108 = zeros(13x1) */
  casadi_clear(w108, 13);
  /* #309: @81 = zeros(1x13,6nz) */
  casadi_clear(w81, 6);
  /* #310: @44 = @44' */
  /* #311: @44 = (@6*@44) */
  for (i=0, rr=w44, cs=w44; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #312: @81 = mac(@44,@82,@81) */
  casadi_mtimes(w44, casadi_s14, w82, casadi_s9, w81, casadi_s5, w, 0);
  /* #313: @81 = @81' */
  /* #314: @23 = 0 */
  w23 = 0.;
  /* #315: @82 = @81; (@82[5] = @23) */
  casadi_copy(w81, 6, w82);
  for (rr=w82+5, ss=(&w23); rr!=w82+6; rr+=1) *rr = *ss++;
  /* #316: @23 = 0 */
  w23 = 0.;
  /* #317: @92 = @82; (@92[4] = @23) */
  casadi_copy(w82, 6, w92);
  for (rr=w92+4, ss=(&w23); rr!=w92+5; rr+=1) *rr = *ss++;
  /* #318: @23 = 0 */
  w23 = 0.;
  /* #319: @91 = @92; (@91[3] = @23) */
  casadi_copy(w92, 6, w91);
  for (rr=w91+3, ss=(&w23); rr!=w91+4; rr+=1) *rr = *ss++;
  /* #320: @23 = 0 */
  w23 = 0.;
  /* #321: @109 = @91; (@109[2] = @23) */
  casadi_copy(w91, 6, w109);
  for (rr=w109+2, ss=(&w23); rr!=w109+3; rr+=1) *rr = *ss++;
  /* #322: @23 = 0 */
  w23 = 0.;
  /* #323: @110 = @109; (@110[1] = @23) */
  casadi_copy(w109, 6, w110);
  for (rr=w110+1, ss=(&w23); rr!=w110+2; rr+=1) *rr = *ss++;
  /* #324: @23 = @110[0] */
  for (rr=(&w23), ss=w110+0; ss!=w110+1; ss+=1) *rr++ = *ss;
  /* #325: @24 = (2.*@23) */
  w24 = (2.* w23 );
  /* #326: @25 = (@24/@14) */
  w25  = (w24/w14);
  /* #327: @26 = @91[2] */
  for (rr=(&w26), ss=w91+2; ss!=w91+3; ss+=1) *rr++ = *ss;
  /* #328: @78 = (@78*@26) */
  w78 *= w26;
  /* #329: @64 = @109[1] */
  for (rr=(&w64), ss=w109+1; ss!=w109+2; ss+=1) *rr++ = *ss;
  /* #330: @76 = (@76*@64) */
  w76 *= w64;
  /* #331: @78 = (@78+@76) */
  w78 += w76;
  /* #332: @61 = (@61*@23) */
  w61 *= w23;
  /* #333: @78 = (@78+@61) */
  w78 += w61;
  /* #334: @61 = (@78/@72) */
  w61  = (w78/w72);
  /* #335: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #336: @76 = (@70*@61) */
  w76  = (w70*w61);
  /* #337: @25 = (@25-@76) */
  w25 -= w76;
  /* #338: (@108[0] += @25) */
  for (rr=w108+0, ss=(&w25); rr!=w108+1; rr+=1) *rr += *ss++;
  /* #339: @25 = 0 */
  w25 = 0.;
  /* #340: (@108[1] = @25) */
  for (rr=w108+1, ss=(&w25); rr!=w108+2; rr+=1) *rr = *ss++;
  /* #341: @25 = (2.*@64) */
  w25 = (2.* w64 );
  /* #342: @76 = (@25/@14) */
  w76  = (w25/w14);
  /* #343: @34 = (@66*@61) */
  w34  = (w66*w61);
  /* #344: @76 = (@76-@34) */
  w76 -= w34;
  /* #345: (@108[1] += @76) */
  for (rr=w108+1, ss=(&w76); rr!=w108+2; rr+=1) *rr += *ss++;
  /* #346: @76 = 0 */
  w76 = 0.;
  /* #347: (@108[2] = @76) */
  for (rr=w108+2, ss=(&w76); rr!=w108+3; rr+=1) *rr = *ss++;
  /* #348: @53 = (@53+@108) */
  for (i=0, rr=w53, cs=w108; i<13; ++i) (*rr++) += (*cs++);
  /* #349: @1 = (@1*@6) */
  for (i=0, rr=w1; i<6; ++i) (*rr++) *= w6;
  /* #350: @108 = dense(@1) */
  casadi_densify(w1, casadi_s15, w108, 0);
  /* #351: @53 = (@53+@108) */
  for (i=0, rr=w53, cs=w108; i<13; ++i) (*rr++) += (*cs++);
  /* #352: @108 = zeros(13x1) */
  casadi_clear(w108, 13);
  /* #353: @111 = @52' */
  casadi_copy(w52, 13, w111);
  /* #354: @111 = (@6*@111) */
  for (i=0, rr=w111, cs=w111; i<13; ++i) (*rr++)  = (w6*(*cs++));
  /* #355: @111 = @111' */
  /* #356: @6 = 0 */
  w6 = 0.;
  /* #357: @112 = @111; (@112[5] = @6) */
  casadi_copy(w111, 13, w112);
  for (rr=w112+5, ss=(&w6); rr!=w112+6; rr+=1) *rr = *ss++;
  /* #358: @6 = 0 */
  w6 = 0.;
  /* #359: @113 = @112; (@113[4] = @6) */
  casadi_copy(w112, 13, w113);
  for (rr=w113+4, ss=(&w6); rr!=w113+5; rr+=1) *rr = *ss++;
  /* #360: @6 = 0 */
  w6 = 0.;
  /* #361: @114 = @113; (@114[3] = @6) */
  casadi_copy(w113, 13, w114);
  for (rr=w114+3, ss=(&w6); rr!=w114+4; rr+=1) *rr = *ss++;
  /* #362: @6 = 0 */
  w6 = 0.;
  /* #363: @115 = @114; (@115[2] = @6) */
  casadi_copy(w114, 13, w115);
  for (rr=w115+2, ss=(&w6); rr!=w115+3; rr+=1) *rr = *ss++;
  /* #364: @6 = 0 */
  w6 = 0.;
  /* #365: @116 = @115; (@116[1] = @6) */
  casadi_copy(w115, 13, w116);
  for (rr=w116+1, ss=(&w6); rr!=w116+2; rr+=1) *rr = *ss++;
  /* #366: @6 = @116[0] */
  for (rr=(&w6), ss=w116+0; ss!=w116+1; ss+=1) *rr++ = *ss;
  /* #367: @76 = (2.*@6) */
  w76 = (2.* w6 );
  /* #368: @34 = (@76/@14) */
  w34  = (w76/w14);
  /* #369: @37 = @114[2] */
  for (rr=(&w37), ss=w114+2; ss!=w114+3; ss+=1) *rr++ = *ss;
  /* #370: @62 = (@62*@37) */
  w62 *= w37;
  /* #371: @40 = @115[1] */
  for (rr=(&w40), ss=w115+1; ss!=w115+2; ss+=1) *rr++ = *ss;
  /* #372: @60 = (@60*@40) */
  w60 *= w40;
  /* #373: @62 = (@62+@60) */
  w62 += w60;
  /* #374: @5 = (@5*@6) */
  w5 *= w6;
  /* #375: @62 = (@62+@5) */
  w62 += w5;
  /* #376: @5 = (@62/@56) */
  w5  = (w62/w56);
  /* #377: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #378: @60 = (@54*@5) */
  w60  = (w54*w5);
  /* #379: @34 = (@34-@60) */
  w34 -= w60;
  /* #380: (@108[0] += @34) */
  for (rr=w108+0, ss=(&w34); rr!=w108+1; rr+=1) *rr += *ss++;
  /* #381: @34 = 0 */
  w34 = 0.;
  /* #382: (@108[1] = @34) */
  for (rr=w108+1, ss=(&w34); rr!=w108+2; rr+=1) *rr = *ss++;
  /* #383: @34 = (2.*@40) */
  w34 = (2.* w40 );
  /* #384: @60 = (@34/@14) */
  w60  = (w34/w14);
  /* #385: @41 = (@15*@5) */
  w41  = (w15*w5);
  /* #386: @60 = (@60-@41) */
  w60 -= w41;
  /* #387: (@108[1] += @60) */
  for (rr=w108+1, ss=(&w60); rr!=w108+2; rr+=1) *rr += *ss++;
  /* #388: @60 = 0 */
  w60 = 0.;
  /* #389: (@108[2] = @60) */
  for (rr=w108+2, ss=(&w60); rr!=w108+3; rr+=1) *rr = *ss++;
  /* #390: @53 = (@53+@108) */
  for (i=0, rr=w53, cs=w108; i<13; ++i) (*rr++) += (*cs++);
  /* #391: {@60, @41, @77, @19, @106, NULL} = vertsplit(@53) */
  w60 = w53[0];
  w41 = w53[1];
  w77 = w53[2];
  casadi_copy(w53+3, 3, w19);
  casadi_copy(w53+6, 4, w106);
  /* #392: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #393: @107 = mac(@21,@19,@107) */
  for (i=0, rr=w107; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #394: {NULL, NULL, @0} = vertsplit(@107) */
  w0 = w107[2];
  /* #395: @63 = (@63+@0) */
  w63 += w0;
  /* #396: (@105[0] = @63) */
  for (rr=w105+0, ss=(&w63); rr!=w105+1; rr+=1) *rr = *ss++;
  /* #397: @23 = (@68*@23) */
  w23  = (w68*w23);
  /* #398: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #399: @52 = @52' */
  /* #400: @52 = (@17*@52) */
  for (i=0, rr=w52, cs=w52; i<13; ++i) (*rr++)  = (w17*(*cs++));
  /* #401: @52 = @52' */
  /* #402: @17 = @92[3] */
  for (rr=(&w17), ss=w92+3; ss!=w92+4; ss+=1) *rr++ = *ss;
  /* #403: @63 = @82[4] */
  for (rr=(&w63), ss=w82+4; ss!=w82+5; ss+=1) *rr++ = *ss;
  /* #404: @0 = @81[5] */
  for (rr=(&w0), ss=w81+5; ss!=w81+6; ss+=1) *rr++ = *ss;
  /* #405: @83 = zeros(3x1,0nz) */
  /* #406: @84 = zeros(4x1,0nz) */
  /* #407: @85 = zeros(3x1,0nz) */
  /* #408: @107 = vertcat(@17, @63, @0, @83, @84, @85) */
  rr=w107;
  *rr++ = w17;
  *rr++ = w63;
  *rr++ = w0;
  /* #409: @53 = dense(@107) */
  casadi_densify(w107, casadi_s2, w53, 0);
  /* #410: @52 = (@52+@53) */
  for (i=0, rr=w52, cs=w53; i<13; ++i) (*rr++) += (*cs++);
  /* #411: @17 = @113[3] */
  for (rr=(&w17), ss=w113+3; ss!=w113+4; ss+=1) *rr++ = *ss;
  /* #412: @63 = @112[4] */
  for (rr=(&w63), ss=w112+4; ss!=w112+5; ss+=1) *rr++ = *ss;
  /* #413: @0 = @111[5] */
  for (rr=(&w0), ss=w111+5; ss!=w111+6; ss+=1) *rr++ = *ss;
  /* #414: @83 = zeros(3x1,0nz) */
  /* #415: @84 = zeros(4x1,0nz) */
  /* #416: @85 = zeros(3x1,0nz) */
  /* #417: @107 = vertcat(@17, @63, @0, @83, @84, @85) */
  rr=w107;
  *rr++ = w17;
  *rr++ = w63;
  *rr++ = w0;
  /* #418: @111 = dense(@107) */
  casadi_densify(w107, casadi_s2, w111, 0);
  /* #419: @52 = (@52+@111) */
  for (i=0, rr=w52, cs=w111; i<13; ++i) (*rr++) += (*cs++);
  /* #420: @17 = 0 */
  w17 = 0.;
  /* #421: @111 = @52; (@111[2] = @17) */
  casadi_copy(w52, 13, w111);
  for (rr=w111+2, ss=(&w17); rr!=w111+3; rr+=1) *rr = *ss++;
  /* #422: @17 = 0 */
  w17 = 0.;
  /* #423: @112 = @111; (@112[1] = @17) */
  casadi_copy(w111, 13, w112);
  for (rr=w112+1, ss=(&w17); rr!=w112+2; rr+=1) *rr = *ss++;
  /* #424: @17 = @112[0] */
  for (rr=(&w17), ss=w112+0; ss!=w112+1; ss+=1) *rr++ = *ss;
  /* #425: @71 = (@71*@61) */
  w71 *= w61;
  /* #426: @63 = (@71/@14) */
  w63  = (w71/w14);
  /* #427: @17 = (@17-@63) */
  w17 -= w63;
  /* #428: @55 = (@55*@5) */
  w55 *= w5;
  /* #429: @63 = (@55/@14) */
  w63  = (w55/w14);
  /* #430: @17 = (@17-@63) */
  w17 -= w63;
  /* #431: @63 = (@17/@14) */
  w63  = (w17/w14);
  /* #432: @63 = (2.*@63) */
  w63 = (2.* w63 );
  /* #433: @23 = (@23+@63) */
  w23 += w63;
  /* #434: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #435: @72 = (@68/@72) */
  w72  = (w68/w72);
  /* #436: @72 = (@72*@78) */
  w72 *= w78;
  /* #437: @72 = (-@72) */
  w72 = (- w72 );
  /* #438: @72 = (2.*@72) */
  w72 = (2.* w72 );
  /* #439: @16 = (@16+@72) */
  w16 += w72;
  /* #440: @56 = (@51/@56) */
  w56  = (w51/w56);
  /* #441: @56 = (@56*@62) */
  w56 *= w62;
  /* #442: @56 = (-@56) */
  w56 = (- w56 );
  /* #443: @56 = (2.*@56) */
  w56 = (2.* w56 );
  /* #444: @16 = (@16+@56) */
  w16 += w56;
  /* #445: @73 = (@73/@14) */
  w73 /= w14;
  /* #446: @73 = (@73*@25) */
  w73 *= w25;
  /* #447: @73 = (-@73) */
  w73 = (- w73 );
  /* #448: @75 = (@75/@14) */
  w75 /= w14;
  /* #449: @25 = (2.*@26) */
  w25 = (2.* w26 );
  /* #450: @75 = (@75*@25) */
  w75 *= w25;
  /* #451: @73 = (@73-@75) */
  w73 -= w75;
  /* #452: @74 = (@74/@14) */
  w74 /= w14;
  /* #453: @74 = (@74*@24) */
  w74 *= w24;
  /* #454: @73 = (@73-@74) */
  w73 -= w74;
  /* #455: @70 = (@70/@14) */
  w70 /= w14;
  /* #456: @70 = (@70*@71) */
  w70 *= w71;
  /* #457: @73 = (@73+@70) */
  w73 += w70;
  /* #458: @70 = (@69/@14) */
  w70  = (w69/w14);
  /* #459: @71 = (@18*@61) */
  w71  = (w18*w61);
  /* #460: @70 = (@70*@71) */
  w70 *= w71;
  /* #461: @73 = (@73+@70) */
  w73 += w70;
  /* #462: @66 = (@66/@14) */
  w66 /= w14;
  /* #463: @67 = (@67*@61) */
  w67 *= w61;
  /* #464: @66 = (@66*@67) */
  w66 *= w67;
  /* #465: @73 = (@73+@66) */
  w73 += w66;
  /* #466: @59 = (@59/@14) */
  w59 /= w14;
  /* #467: @66 = (2.*@37) */
  w66 = (2.* w37 );
  /* #468: @59 = (@59*@66) */
  w59 *= w66;
  /* #469: @73 = (@73-@59) */
  w73 -= w59;
  /* #470: @57 = (@57/@14) */
  w57 /= w14;
  /* #471: @57 = (@57*@34) */
  w57 *= w34;
  /* #472: @73 = (@73-@57) */
  w73 -= w57;
  /* #473: @58 = (@58/@14) */
  w58 /= w14;
  /* #474: @58 = (@58*@76) */
  w58 *= w76;
  /* #475: @73 = (@73-@58) */
  w73 -= w58;
  /* #476: @54 = (@54/@14) */
  w54 /= w14;
  /* #477: @54 = (@54*@55) */
  w54 *= w55;
  /* #478: @73 = (@73+@54) */
  w73 += w54;
  /* #479: @42 = (@42/@14) */
  w42 /= w14;
  /* #480: @42 = (@42*@17) */
  w42 *= w17;
  /* #481: @73 = (@73-@42) */
  w73 -= w42;
  /* #482: @42 = (@50/@14) */
  w42  = (w50/w14);
  /* #483: @18 = (@18*@5) */
  w18 *= w5;
  /* #484: @42 = (@42*@18) */
  w42 *= w18;
  /* #485: @73 = (@73+@42) */
  w73 += w42;
  /* #486: @49 = (@49/@14) */
  w49 /= w14;
  /* #487: @42 = @52[2] */
  for (rr=(&w42), ss=w52+2; ss!=w52+3; ss+=1) *rr++ = *ss;
  /* #488: @71 = (@71/@14) */
  w71 /= w14;
  /* #489: @42 = (@42-@71) */
  w42 -= w71;
  /* #490: @18 = (@18/@14) */
  w18 /= w14;
  /* #491: @42 = (@42-@18) */
  w42 -= w18;
  /* #492: @49 = (@49*@42) */
  w49 *= w42;
  /* #493: @73 = (@73-@49) */
  w73 -= w49;
  /* #494: @15 = (@15/@14) */
  w15 /= w14;
  /* #495: @43 = (@43*@5) */
  w43 *= w5;
  /* #496: @15 = (@15*@43) */
  w15 *= w43;
  /* #497: @73 = (@73+@15) */
  w73 += w15;
  /* #498: @9 = (@9/@14) */
  w9 /= w14;
  /* #499: @15 = @111[1] */
  for (rr=(&w15), ss=w111+1; ss!=w111+2; ss+=1) *rr++ = *ss;
  /* #500: @67 = (@67/@14) */
  w67 /= w14;
  /* #501: @15 = (@15-@67) */
  w15 -= w67;
  /* #502: @43 = (@43/@14) */
  w43 /= w14;
  /* #503: @15 = (@15-@43) */
  w15 -= w43;
  /* #504: @9 = (@9*@15) */
  w9 *= w15;
  /* #505: @73 = (@73-@9) */
  w73 -= w9;
  /* #506: @73 = (2.*@73) */
  w73 = (2.* w73 );
  /* #507: @16 = (@16+@73) */
  w16 += w73;
  /* #508: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #509: @16 = (@16/@10) */
  w16 /= w10;
  /* #510: @4 = (@4*@16) */
  w4 *= w16;
  /* #511: @23 = (@23+@4) */
  w23 += w4;
  /* #512: @6 = (@51*@6) */
  w6  = (w51*w6);
  /* #513: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #514: @23 = (@23+@6) */
  w23 += w6;
  /* #515: (@105[1] = @23) */
  for (rr=w105+1, ss=(&w23); rr!=w105+2; rr+=1) *rr = *ss++;
  /* #516: @64 = (@68*@64) */
  w64  = (w68*w64);
  /* #517: @64 = (2.*@64) */
  w64 = (2.* w64 );
  /* #518: @40 = (@51*@40) */
  w40  = (w51*w40);
  /* #519: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #520: @64 = (@64+@40) */
  w64 += w40;
  /* #521: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #522: @8 = (@8*@16) */
  w8 *= w16;
  /* #523: @64 = (@64+@8) */
  w64 += w8;
  /* #524: @15 = (@15/@14) */
  w15 /= w14;
  /* #525: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #526: @64 = (@64+@15) */
  w64 += w15;
  /* #527: (@105[2] = @64) */
  for (rr=w105+2, ss=(&w64); rr!=w105+3; rr+=1) *rr = *ss++;
  /* #528: @68 = (@68*@26) */
  w68 *= w26;
  /* #529: @68 = (2.*@68) */
  w68 = (2.* w68 );
  /* #530: @51 = (@51*@37) */
  w51 *= w37;
  /* #531: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #532: @68 = (@68+@51) */
  w68 += w51;
  /* #533: @42 = (@42/@14) */
  w42 /= w14;
  /* #534: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #535: @68 = (@68+@42) */
  w68 += w42;
  /* #536: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #537: @13 = (@13*@16) */
  w13 *= w16;
  /* #538: @68 = (@68+@13) */
  w68 += w13;
  /* #539: (@105[3] = @68) */
  for (rr=w105+3, ss=(&w68); rr!=w105+4; rr+=1) *rr = *ss++;
  /* #540: (@105[4] = @60) */
  for (rr=w105+4, ss=(&w60); rr!=w105+5; rr+=1) *rr = *ss++;
  /* #541: (@105[5] = @41) */
  for (rr=w105+5, ss=(&w41); rr!=w105+6; rr+=1) *rr = *ss++;
  /* #542: @25 = (@25/@14) */
  w25 /= w14;
  /* #543: @69 = (@69*@61) */
  w69 *= w61;
  /* #544: @25 = (@25-@69) */
  w25 -= w69;
  /* #545: @66 = (@66/@14) */
  w66 /= w14;
  /* #546: @25 = (@25+@66) */
  w25 += w66;
  /* #547: @50 = (@50*@5) */
  w50 *= w5;
  /* #548: @25 = (@25-@50) */
  w25 -= w50;
  /* #549: @25 = (@25+@77) */
  w25 += w77;
  /* #550: (@105[6] = @25) */
  for (rr=w105+6, ss=(&w25); rr!=w105+7; rr+=1) *rr = *ss++;
  /* #551: @106 = (@32*@106) */
  for (i=0, rr=w106, cs=w106; i<4; ++i) (*rr++)  = (w32*(*cs++));
  /* #552: {@32, @25, @77, @50} = vertsplit(@106) */
  w32 = w106[0];
  w25 = w106[1];
  w77 = w106[2];
  w50 = w106[3];
  /* #553: @5 = (@39*@50) */
  w5  = (w39*w50);
  /* #554: @66 = (@38*@77) */
  w66  = (w38*w77);
  /* #555: @5 = (@5+@66) */
  w5 += w66;
  /* #556: @66 = (@33*@25) */
  w66  = (w33*w25);
  /* #557: @5 = (@5+@66) */
  w5 += w66;
  /* #558: @106 = zeros(4x1) */
  casadi_clear(w106, 4);
  /* #559: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #560: @81 = zeros(13x1,6nz) */
  casadi_clear(w81, 6);
  /* #561: @82 = zeros(13x4,6nz) */
  casadi_clear(w82, 6);
  /* #562: @82 = mac(@65,@44,@82) */
  casadi_mtimes(w65, casadi_s15, w44, casadi_s14, w82, casadi_s8, w, 0);
  /* #563: @65 = @82' */
  casadi_trans(w82,casadi_s8, w65, casadi_s9, iw);
  /* #564: @82 = @65[:6] */
  for (rr=w82, ss=w65+0; ss!=w65+6; ss+=1) *rr++ = *ss;
  /* #565: (@81[:6] += @82) */
  for (rr=w81+0, ss=w82; rr!=w81+6; rr+=1) *rr += *ss++;
  /* #566: {NULL, NULL, NULL, @107, NULL, NULL} = vertsplit(@81) */
  casadi_copy(w81, 3, w107);
  /* #567: @107 = (@80*@107) */
  for (i=0, rr=w107, cs=w107; i<3; ++i) (*rr++)  = (w80*(*cs++));
  /* #568: @90 = @90' */
  /* #569: @21 = mac(@107,@90,@21) */
  casadi_mtimes(w107, casadi_s0, (&w90), casadi_s16, w21, casadi_s7, w, 0);
  /* #570: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #571: @35 = @35' */
  /* #572: @20 = mac(@19,@35,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w35+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #573: @21 = (@21+@20) */
  for (i=0, rr=w21, cs=w20; i<9; ++i) (*rr++) += (*cs++);
  /* #574: @90 = dot(@22, @21) */
  w90 = casadi_dot(9, w22, w21);
  /* #575: @90 = (2.*@90) */
  w90 = (2.* w90 );
  /* #576: (@106[0] += @90) */
  for (rr=w106+0, ss=(&w90); rr!=w106+1; rr+=1) *rr += *ss++;
  /* #577: @20 = (@30*@21) */
  for (i=0, rr=w20, cs=w21; i<9; ++i) (*rr++)  = (w30*(*cs++));
  /* #578: @117 = zeros(3x3) */
  casadi_clear(w117, 9);
  /* #579: @118 = @31' */
  for (i=0, rr=w118, cs=w31; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #580: @117 = mac(@118,@21,@117) */
  for (i=0, rr=w117; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w118+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #581: @20 = (@20+@117) */
  for (i=0, rr=w20, cs=w117; i<9; ++i) (*rr++) += (*cs++);
  /* #582: @117 = zeros(3x3) */
  casadi_clear(w117, 9);
  /* #583: @118 = @22' */
  for (i=0, rr=w118, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #584: @117 = mac(@21,@118,@117) */
  for (i=0, rr=w117; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w118+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #585: @117 = (2.*@117) */
  for (i=0, rr=w117, cs=w117; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #586: @20 = (@20+@117) */
  for (i=0, rr=w20, cs=w117; i<9; ++i) (*rr++) += (*cs++);
  /* #587: @30 = @20[5] */
  for (rr=(&w30), ss=w20+5; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #588: (@106[1] += @30) */
  for (rr=w106+1, ss=(&w30); rr!=w106+2; rr+=1) *rr += *ss++;
  /* #589: @30 = 0 */
  w30 = 0.;
  /* #590: (@20[5] = @30) */
  for (rr=w20+5, ss=(&w30); rr!=w20+6; rr+=1) *rr = *ss++;
  /* #591: @30 = @20[2] */
  for (rr=(&w30), ss=w20+2; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #592: @30 = (-@30) */
  w30 = (- w30 );
  /* #593: (@106[2] += @30) */
  for (rr=w106+2, ss=(&w30); rr!=w106+3; rr+=1) *rr += *ss++;
  /* #594: @30 = 0 */
  w30 = 0.;
  /* #595: (@20[2] = @30) */
  for (rr=w20+2, ss=(&w30); rr!=w20+3; rr+=1) *rr = *ss++;
  /* #596: @30 = @20[1] */
  for (rr=(&w30), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #597: (@106[3] += @30) */
  for (rr=w106+3, ss=(&w30); rr!=w106+4; rr+=1) *rr += *ss++;
  /* #598: @30 = 0 */
  w30 = 0.;
  /* #599: (@20[1] = @30) */
  for (rr=w20+1, ss=(&w30); rr!=w20+2; rr+=1) *rr = *ss++;
  /* #600: @30 = @20[7] */
  for (rr=(&w30), ss=w20+7; ss!=w20+8; ss+=1) *rr++ = *ss;
  /* #601: @30 = (-@30) */
  w30 = (- w30 );
  /* #602: (@106[1] += @30) */
  for (rr=w106+1, ss=(&w30); rr!=w106+2; rr+=1) *rr += *ss++;
  /* #603: @30 = 0 */
  w30 = 0.;
  /* #604: (@20[7] = @30) */
  for (rr=w20+7, ss=(&w30); rr!=w20+8; rr+=1) *rr = *ss++;
  /* #605: @30 = @20[6] */
  for (rr=(&w30), ss=w20+6; ss!=w20+7; ss+=1) *rr++ = *ss;
  /* #606: (@106[2] += @30) */
  for (rr=w106+2, ss=(&w30); rr!=w106+3; rr+=1) *rr += *ss++;
  /* #607: @30 = 0 */
  w30 = 0.;
  /* #608: (@20[6] = @30) */
  for (rr=w20+6, ss=(&w30); rr!=w20+7; rr+=1) *rr = *ss++;
  /* #609: @30 = @20[3] */
  for (rr=(&w30), ss=w20+3; ss!=w20+4; ss+=1) *rr++ = *ss;
  /* #610: @30 = (-@30) */
  w30 = (- w30 );
  /* #611: (@106[3] += @30) */
  for (rr=w106+3, ss=(&w30); rr!=w106+4; rr+=1) *rr += *ss++;
  /* #612: @44 = (@106/@28) */
  for (i=0, rr=w44, cr=w106; i<4; ++i) (*rr++)  = ((*cr++)/w28);
  /* #613: @29 = (@29/@28) */
  for (i=0, rr=w29; i<4; ++i) (*rr++) /= w28;
  /* #614: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) *rr++ = (- *cs++ );
  /* #615: @30 = dot(@29, @106) */
  w30 = casadi_dot(4, w29, w106);
  /* #616: @30 = (@30/@28) */
  w30 /= w28;
  /* #617: @27 = (@30*@27) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w30*(*cs++));
  /* #618: @44 = (@44+@27) */
  for (i=0, rr=w44, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #619: {@30, @28, @90, @80} = vertsplit(@44) */
  w30 = w44[0];
  w28 = w44[1];
  w90 = w44[2];
  w80 = w44[3];
  /* #620: @5 = (@5+@30) */
  w5 += w30;
  /* #621: (@105[7] = @5) */
  for (rr=w105+7, ss=(&w5); rr!=w105+8; rr+=1) *rr = *ss++;
  /* #622: @5 = (@38*@50) */
  w5  = (w38*w50);
  /* #623: @30 = (@39*@77) */
  w30  = (w39*w77);
  /* #624: @5 = (@5-@30) */
  w5 -= w30;
  /* #625: @30 = (@33*@32) */
  w30  = (w33*w32);
  /* #626: @5 = (@5-@30) */
  w5 -= w30;
  /* #627: @5 = (@5+@28) */
  w5 += w28;
  /* #628: (@105[8] = @5) */
  for (rr=w105+8, ss=(&w5); rr!=w105+9; rr+=1) *rr = *ss++;
  /* #629: @5 = (@39*@25) */
  w5  = (w39*w25);
  /* #630: @50 = (@33*@50) */
  w50  = (w33*w50);
  /* #631: @5 = (@5-@50) */
  w5 -= w50;
  /* #632: @50 = (@38*@32) */
  w50  = (w38*w32);
  /* #633: @5 = (@5-@50) */
  w5 -= w50;
  /* #634: @5 = (@5+@90) */
  w5 += w90;
  /* #635: (@105[9] = @5) */
  for (rr=w105+9, ss=(&w5); rr!=w105+10; rr+=1) *rr = *ss++;
  /* #636: @33 = (@33*@77) */
  w33 *= w77;
  /* #637: @38 = (@38*@25) */
  w38 *= w25;
  /* #638: @33 = (@33-@38) */
  w33 -= w38;
  /* #639: @39 = (@39*@32) */
  w39 *= w32;
  /* #640: @33 = (@33-@39) */
  w33 -= w39;
  /* #641: @33 = (@33+@80) */
  w33 += w80;
  /* #642: (@105[10] = @33) */
  for (rr=w105+10, ss=(&w33); rr!=w105+11; rr+=1) *rr = *ss++;
  /* #643: @111 = zeros(13x1) */
  casadi_clear(w111, 13);
  /* #644: @45 = @45' */
  /* #645: @33 = ones(2x1,1nz) */
  w33 = 1.;
  /* #646: {NULL, @80} = vertsplit(@33) */
  w80 = w33;
  /* #647: @45 = (@45*@80) */
  for (i=0, rr=w45; i<3; ++i) (*rr++) *= w80;
  /* #648: @33 = dot(@36, @45) */
  w33 = casadi_dot(3, w36, w45);
  /* #649: @45 = (@33*@36) */
  for (i=0, rr=w45, cs=w36; i<3; ++i) (*rr++)  = (w33*(*cs++));
  /* #650: (@111[3:6] += @45) */
  for (rr=w111+3, ss=w45; rr!=w111+6; rr+=1) *rr += *ss++;
  /* #651: @48 = @48' */
  /* #652: @2 = (@2*@80) */
  w2 *= w80;
  /* #653: @48 = (@48*@2) */
  for (i=0, rr=w48; i<3; ++i) (*rr++) *= w2;
  /* #654: @46 = @46' */
  /* #655: @46 = (@2*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #656: @46 = (@11*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #657: @46 = @46' */
  /* #658: @48 = (@48+@46) */
  for (i=0, rr=w48, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #659: @47 = @47' */
  /* #660: @47 = (@80*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) (*rr++)  = (w80*(*cs++));
  /* #661: @47 = (-@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) *rr++ = (- *cs++ );
  /* #662: @47 = @47' */
  /* #663: @48 = (@48+@47) */
  for (i=0, rr=w48, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #664: @80 = dot(@36, @48) */
  w80 = casadi_dot(3, w36, w48);
  /* #665: @36 = (@80*@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) (*rr++)  = (w80*(*cs++));
  /* #666: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<3; ++i) *rr++ = (- *cs++ );
  /* #667: (@111[:3] += @36) */
  for (rr=w111+0, ss=w36; rr!=w111+3; rr+=1) *rr += *ss++;
  /* #668: {@80, @11, @2, @33, @39, @32, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@111) */
  w80 = w111[0];
  w11 = w111[1];
  w2 = w111[2];
  w33 = w111[3];
  w39 = w111[4];
  w32 = w111[5];
  /* #669: (@105[11] = @80) */
  for (rr=w105+11, ss=(&w80); rr!=w105+12; rr+=1) *rr = *ss++;
  /* #670: (@105[12] = @11) */
  for (rr=w105+12, ss=(&w11); rr!=w105+13; rr+=1) *rr = *ss++;
  /* #671: (@105[13] = @2) */
  for (rr=w105+13, ss=(&w2); rr!=w105+14; rr+=1) *rr = *ss++;
  /* #672: (@105[14] = @33) */
  for (rr=w105+14, ss=(&w33); rr!=w105+15; rr+=1) *rr = *ss++;
  /* #673: (@105[15] = @39) */
  for (rr=w105+15, ss=(&w39); rr!=w105+16; rr+=1) *rr = *ss++;
  /* #674: (@105[16] = @32) */
  for (rr=w105+16, ss=(&w32); rr!=w105+17; rr+=1) *rr = *ss++;
  /* #675: output[1][0] = @105 */
  casadi_copy(w105, 17, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s11;
    case 2: return casadi_s17;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s20;
    case 2: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_2_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 389;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
