/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s2[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[4] = {0, 1, 0, 0};
static const casadi_int casadi_s4[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {1.0000000000000000e-02, 0., 0., 0., 0., 1.0000000000000000e-02, 0., 0., 0., 0., 1.0000000000000000e-02, 0., 0., 0., 0., 1.0000000000000000e-02};

/* Drone_ode_cost_ext_cost_0_fun:(i0[11],i1[4],i2[0],i3[25])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+4, *w2=w+7, *w3=w+10, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, *w30=w+45, *w31=w+70, *w32=w+73, *w33=w+76, *w34=w+85, *w35=w+88, *w36=w+92, *w37=w+96, *w38=w+100, *w39=w+116, *w40=w+125;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = input[3][12] */
  w17 = arg[3] ? arg[3][12] : 0;
  /* #18: @18 = input[3][13] */
  w18 = arg[3] ? arg[3][13] : 0;
  /* #19: @19 = input[3][14] */
  w19 = arg[3] ? arg[3][14] : 0;
  /* #20: @20 = input[3][15] */
  w20 = arg[3] ? arg[3][15] : 0;
  /* #21: @21 = input[3][16] */
  w21 = arg[3] ? arg[3][16] : 0;
  /* #22: @22 = input[3][17] */
  w22 = arg[3] ? arg[3][17] : 0;
  /* #23: @23 = input[3][18] */
  w23 = arg[3] ? arg[3][18] : 0;
  /* #24: @24 = input[3][19] */
  w24 = arg[3] ? arg[3][19] : 0;
  /* #25: @25 = input[3][20] */
  w25 = arg[3] ? arg[3][20] : 0;
  /* #26: @26 = input[3][21] */
  w26 = arg[3] ? arg[3][21] : 0;
  /* #27: @27 = input[3][22] */
  w27 = arg[3] ? arg[3][22] : 0;
  /* #28: @28 = input[3][23] */
  w28 = arg[3] ? arg[3][23] : 0;
  /* #29: @29 = input[3][24] */
  w29 = arg[3] ? arg[3][24] : 0;
  /* #30: @30 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29) */
  rr=w30;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  /* #31: @31 = @30[15:18] */
  for (rr=w31, ss=w30+15; ss!=w30+18; ss+=1) *rr++ = *ss;
  /* #32: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #33: @4 = mac(@32,@31,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #34: @33 = @4[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w33, ss=(&w4); cii!=casadi_s0+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #35: @3 = (@3-@33) */
  for (i=0, rr=w3, cs=w33; i<9; ++i) (*rr++) -= (*cs++);
  /* #36: @32 = @30[:3] */
  for (rr=w32, ss=w30+0; ss!=w30+3; ss+=1) *rr++ = *ss;
  /* #37: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #38: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #39: @6 = input[0][2] */
  w6 = arg[0] ? arg[0][2] : 0;
  /* #40: @34 = vertcat(@4, @5, @6) */
  rr=w34;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #41: @32 = (@32-@34) */
  for (i=0, rr=w32, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #42: @2 = mac(@3,@32,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #43: @34 = @2' */
  casadi_copy(w2, 3, w34);
  /* #44: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #45: @1 = mac(@34,@3,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @4 = 0 */
  w4 = 0.;
  /* #48: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #49: @5 = dot(@31, @32) */
  w5 = casadi_dot(3, w31, w32);
  /* #50: @32 = (@5*@31) */
  for (i=0, rr=w32, cs=w31; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #51: @2 = @32' */
  casadi_copy(w32, 3, w2);
  /* #52: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #53: @1 = mac(@2,@3,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #54: @4 = mac(@1,@32,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #55: @0 = (@0+@4) */
  w0 += w4;
  /* #56: @4 = 0 */
  w4 = 0.;
  /* #57: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #58: @9 = (-@9) */
  w9 = (- w9 );
  /* #59: @10 = (-@10) */
  w10 = (- w10 );
  /* #60: @11 = (-@11) */
  w11 = (- w11 );
  /* #61: @35 = vertcat(@8, @9, @10, @11) */
  rr=w35;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #62: @36 = @30[3:7] */
  for (rr=w36, ss=w30+3; ss!=w30+7; ss+=1) *rr++ = *ss;
  /* #63: @8 = ||@36||_F */
  w8 = sqrt(casadi_dot(4, w36, w36));
  /* #64: @35 = (@35/@8) */
  for (i=0, rr=w35; i<4; ++i) (*rr++) /= w8;
  /* #65: @8 = @35[0] */
  for (rr=(&w8), ss=w35+0; ss!=w35+1; ss+=1) *rr++ = *ss;
  /* #66: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #67: @10 = (@8*@9) */
  w10  = (w8*w9);
  /* #68: @11 = @35[1] */
  for (rr=(&w11), ss=w35+1; ss!=w35+2; ss+=1) *rr++ = *ss;
  /* #69: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #70: @6 = (@11*@5) */
  w6  = (w11*w5);
  /* #71: @10 = (@10-@6) */
  w10 -= w6;
  /* #72: @6 = @35[2] */
  for (rr=(&w6), ss=w35+2; ss!=w35+3; ss+=1) *rr++ = *ss;
  /* #73: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #74: @12 = (@6*@7) */
  w12  = (w6*w7);
  /* #75: @10 = (@10-@12) */
  w10 -= w12;
  /* #76: @12 = @35[3] */
  for (rr=(&w12), ss=w35+3; ss!=w35+4; ss+=1) *rr++ = *ss;
  /* #77: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #78: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #79: @10 = (@10-@14) */
  w10 -= w14;
  /* #80: @14 = 0 */
  w14 = 0.;
  /* #81: @14 = (@10<@14) */
  w14  = (w10<w14);
  /* #82: @15 = (@8*@5) */
  w15  = (w8*w5);
  /* #83: @16 = (@11*@9) */
  w16  = (w11*w9);
  /* #84: @15 = (@15+@16) */
  w15 += w16;
  /* #85: @16 = (@6*@13) */
  w16  = (w6*w13);
  /* #86: @15 = (@15+@16) */
  w15 += w16;
  /* #87: @16 = (@12*@7) */
  w16  = (w12*w7);
  /* #88: @15 = (@15-@16) */
  w15 -= w16;
  /* #89: @16 = (@8*@7) */
  w16  = (w8*w7);
  /* #90: @17 = (@11*@13) */
  w17  = (w11*w13);
  /* #91: @16 = (@16-@17) */
  w16 -= w17;
  /* #92: @17 = (@6*@9) */
  w17  = (w6*w9);
  /* #93: @16 = (@16+@17) */
  w16 += w17;
  /* #94: @17 = (@12*@5) */
  w17  = (w12*w5);
  /* #95: @16 = (@16+@17) */
  w16 += w17;
  /* #96: @8 = (@8*@13) */
  w8 *= w13;
  /* #97: @11 = (@11*@7) */
  w11 *= w7;
  /* #98: @8 = (@8+@11) */
  w8 += w11;
  /* #99: @6 = (@6*@5) */
  w6 *= w5;
  /* #100: @8 = (@8-@6) */
  w8 -= w6;
  /* #101: @12 = (@12*@9) */
  w12 *= w9;
  /* #102: @8 = (@8+@12) */
  w8 += w12;
  /* #103: @35 = vertcat(@10, @15, @16, @8) */
  rr=w35;
  *rr++ = w10;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w8;
  /* #104: @36 = (-@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) *rr++ = (- *cs++ );
  /* #105: @36 = (@14?@36:0) */
  for (i=0, rr=w36, cs=w36; i<4; ++i) (*rr++)  = (w14?(*cs++):0);
  /* #106: @14 = (!@14) */
  w14 = (! w14 );
  /* #107: @35 = (@14?@35:0) */
  for (i=0, rr=w35, cs=w35; i<4; ++i) (*rr++)  = (w14?(*cs++):0);
  /* #108: @36 = (@36+@35) */
  for (i=0, rr=w36, cs=w35; i<4; ++i) (*rr++) += (*cs++);
  /* #109: @32 = @36[1:4] */
  for (rr=w32, ss=w36+1; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #110: @2 = (2.*@32) */
  for (i=0, rr=w2, cs=w32; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #111: @14 = ||@32||_F */
  w14 = sqrt(casadi_dot(3, w32, w32));
  /* #112: @10 = @36[0] */
  for (rr=(&w10), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  /* #113: @10 = atan2(@14,@10) */
  w10  = atan2(w14,w10);
  /* #114: @2 = (@2*@10) */
  for (i=0, rr=w2; i<3; ++i) (*rr++) *= w10;
  /* #115: @2 = (@2/@14) */
  for (i=0, rr=w2; i<3; ++i) (*rr++) /= w14;
  /* #116: @32 = @2' */
  casadi_copy(w2, 3, w32);
  /* #117: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #118: @1 = mac(@32,@3,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #119: @4 = mac(@1,@2,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #120: @0 = (@0+@4) */
  w0 += w4;
  /* #121: @4 = 0 */
  w4 = 0.;
  /* #122: @36 = zeros(1x4) */
  casadi_clear(w36, 4);
  /* #123: @14 = input[1][0] */
  w14 = arg[1] ? arg[1][0] : 0;
  /* #124: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #125: @15 = input[1][2] */
  w15 = arg[1] ? arg[1][2] : 0;
  /* #126: @16 = input[1][3] */
  w16 = arg[1] ? arg[1][3] : 0;
  /* #127: @35 = vertcat(@14, @10, @15, @16) */
  rr=w35;
  *rr++ = w14;
  *rr++ = w10;
  *rr++ = w15;
  *rr++ = w16;
  /* #128: @37 = @35' */
  casadi_copy(w35, 4, w37);
  /* #129: @38 = 
  [[0.01, 0, 0, 0], 
   [0, 0.01, 0, 0], 
   [0, 0, 0.01, 0], 
   [0, 0, 0, 0.01]] */
  casadi_copy(casadi_c1, 16, w38);
  /* #130: @36 = mac(@37,@38,@36) */
  for (i=0, rr=w36; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #131: @4 = mac(@36,@35,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w36+j, tt=w35+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #132: @0 = (@0+@4) */
  w0 += w4;
  /* #133: @4 = 0.1 */
  w4 = 1.0000000000000001e-01;
  /* #134: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #135: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #136: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #137: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #138: @36 = vertcat(@9, @5, @7, @13) */
  rr=w36;
  *rr++ = w9;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w13;
  /* #139: @9 = ||@36||_F */
  w9 = sqrt(casadi_dot(4, w36, w36));
  /* #140: @36 = (@36/@9) */
  for (i=0, rr=w36; i<4; ++i) (*rr++) /= w9;
  /* #141: @9 = @36[3] */
  for (rr=(&w9), ss=w36+3; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #142: @9 = (-@9) */
  w9 = (- w9 );
  /* #143: (@39[3] = @9) */
  for (rr=w39+3, ss=(&w9); rr!=w39+4; rr+=1) *rr = *ss++;
  /* #144: @9 = @36[2] */
  for (rr=(&w9), ss=w36+2; ss!=w36+3; ss+=1) *rr++ = *ss;
  /* #145: (@39[6] = @9) */
  for (rr=w39+6, ss=(&w9); rr!=w39+7; rr+=1) *rr = *ss++;
  /* #146: @9 = @36[1] */
  for (rr=(&w9), ss=w36+1; ss!=w36+2; ss+=1) *rr++ = *ss;
  /* #147: @9 = (-@9) */
  w9 = (- w9 );
  /* #148: (@39[7] = @9) */
  for (rr=w39+7, ss=(&w9); rr!=w39+8; rr+=1) *rr = *ss++;
  /* #149: @9 = @36[3] */
  for (rr=(&w9), ss=w36+3; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #150: (@39[1] = @9) */
  for (rr=w39+1, ss=(&w9); rr!=w39+2; rr+=1) *rr = *ss++;
  /* #151: @9 = @36[2] */
  for (rr=(&w9), ss=w36+2; ss!=w36+3; ss+=1) *rr++ = *ss;
  /* #152: @9 = (-@9) */
  w9 = (- w9 );
  /* #153: (@39[2] = @9) */
  for (rr=w39+2, ss=(&w9); rr!=w39+3; rr+=1) *rr = *ss++;
  /* #154: @9 = @36[1] */
  for (rr=(&w9), ss=w36+1; ss!=w36+2; ss+=1) *rr++ = *ss;
  /* #155: (@39[5] = @9) */
  for (rr=w39+5, ss=(&w9); rr!=w39+6; rr+=1) *rr = *ss++;
  /* #156: @40 = (2.*@39) */
  for (i=0, rr=w40, cs=w39; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #157: @33 = mac(@40,@39,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w40+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #158: @3 = (@3+@33) */
  for (i=0, rr=w3, cs=w33; i<9; ++i) (*rr++) += (*cs++);
  /* #159: @9 = @36[0] */
  for (rr=(&w9), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  /* #160: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #161: @39 = (@9*@39) */
  for (i=0, rr=w39, cs=w39; i<9; ++i) (*rr++)  = (w9*(*cs++));
  /* #162: @3 = (@3+@39) */
  for (i=0, rr=w3, cs=w39; i<9; ++i) (*rr++) += (*cs++);
  /* #163: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #164: @5 = input[0][8] */
  w5 = arg[0] ? arg[0][8] : 0;
  /* #165: @7 = input[0][9] */
  w7 = arg[0] ? arg[0][9] : 0;
  /* #166: @2 = vertcat(@9, @5, @7) */
  rr=w2;
  *rr++ = w9;
  *rr++ = w5;
  *rr++ = w7;
  /* #167: @1 = mac(@3,@2,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #168: @9 = dot(@31, @1) */
  w9 = casadi_dot(3, w31, w1);
  /* #169: @4 = (@4*@9) */
  w4 *= w9;
  /* #170: @0 = (@0-@4) */
  w0 -= w4;
  /* #171: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 29;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 134;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
