/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[7] = {11, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s5[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s7[51] = {11, 4, 0, 11, 22, 33, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s10[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s11[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s12[17] = {1, 11, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0};
static const casadi_int casadi_s13[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s14[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s15[3] = {0, 0, 0};
static const casadi_int casadi_s16[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s17[7] = {3, 1, 0, 3, 0, 1, 2};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};
static const casadi_real casadi_c2[2] = {25., 15.};

/* Drone_ode_constr_h_fun:(i0[11],i1[4],i2[],i3[25])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+12, *w2=w+23, *w3=w+34, *w4=w+55, *w5=w+64, *w6=w+73, w7, w8, w9, w10, *w11=w+86, w12, *w13=w+91, w14, *w15=w+96, *w16=w+105, *w17=w+108, *w18=w+141, *w19=w+174, w20, w21, w22, w23, w24, w25, *w26=w+192, *w27=w+196, *w28=w+200, *w29=w+204, *w30=w+208, *w31=w+224, *w32=w+240, *w33=w+284, *w34=w+328, *w35=w+356, *w36=w+372, *w37=w+388, *w38=w+432, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, *w51=w+565, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, *w65=w+589, w66, w67, w68, *w69=w+713, *w70=w+724, w71, w72, w73, *w74=w+738, *w75=w+859, *w76=w+868, *w77=w+877, *w78=w+921, *w79=w+925, *w83=w+929, *w84=w+931, w85, w86, w87, w88, *w89=w+937, *w90=w+962, *w91=w+965, *w92=w+968, *w93=w+971, *w94=w+974, *w95=w+977, *w96=w+980, *w97=w+983;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(11x1) */
  casadi_clear(w1, 11);
  /* #2: @2 = zeros(11x1) */
  casadi_clear(w2, 11);
  /* #3: @3 = zeros(3x7) */
  casadi_clear(w3, 21);
  /* #4: @4 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w4);
  /* #5: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #6: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #7: @7 = input[0][3] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #8: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #9: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #10: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #11: @11 = vertcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #12: @12 = ||@11||_F */
  w12 = sqrt(casadi_dot(4, w11, w11));
  /* #13: @13 = (@11/@12) */
  for (i=0, rr=w13, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #14: @14 = @13[3] */
  for (rr=(&w14), ss=w13+3; ss!=w13+4; ss+=1) *rr++ = *ss;
  /* #15: @14 = (-@14) */
  w14 = (- w14 );
  /* #16: (@6[3] = @14) */
  for (rr=w6+3, ss=(&w14); rr!=w6+4; rr+=1) *rr = *ss++;
  /* #17: @14 = @13[2] */
  for (rr=(&w14), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #18: (@6[6] = @14) */
  for (rr=w6+6, ss=(&w14); rr!=w6+7; rr+=1) *rr = *ss++;
  /* #19: @14 = @13[1] */
  for (rr=(&w14), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #20: @14 = (-@14) */
  w14 = (- w14 );
  /* #21: (@6[7] = @14) */
  for (rr=w6+7, ss=(&w14); rr!=w6+8; rr+=1) *rr = *ss++;
  /* #22: @14 = @13[3] */
  for (rr=(&w14), ss=w13+3; ss!=w13+4; ss+=1) *rr++ = *ss;
  /* #23: (@6[1] = @14) */
  for (rr=w6+1, ss=(&w14); rr!=w6+2; rr+=1) *rr = *ss++;
  /* #24: @14 = @13[2] */
  for (rr=(&w14), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #25: @14 = (-@14) */
  w14 = (- w14 );
  /* #26: (@6[2] = @14) */
  for (rr=w6+2, ss=(&w14); rr!=w6+3; rr+=1) *rr = *ss++;
  /* #27: @14 = @13[1] */
  for (rr=(&w14), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #28: (@6[5] = @14) */
  for (rr=w6+5, ss=(&w14); rr!=w6+6; rr+=1) *rr = *ss++;
  /* #29: @15 = (2.*@6) */
  for (i=0, rr=w15, cs=w6; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #30: @5 = mac(@15,@6,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #31: @4 = (@4+@5) */
  for (i=0, rr=w4, cs=w5; i<9; ++i) (*rr++) += (*cs++);
  /* #32: @14 = @13[0] */
  for (rr=(&w14), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #33: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #34: @5 = (@14*@6) */
  for (i=0, rr=w5, cs=w6; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #35: @4 = (@4+@5) */
  for (i=0, rr=w4, cs=w5; i<9; ++i) (*rr++) += (*cs++);
  /* #36: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #37: @17 = horzcat(@3, @4, @16) */
  rr=w17;
  for (i=0, cs=w3; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  /* #38: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #39: @19 = zeros(4x3) */
  casadi_clear(w19, 12);
  /* #40: @20 = 0.5 */
  w20 = 5.0000000000000000e-01;
  /* #41: @21 = 0 */
  w21 = 0.;
  /* #42: @22 = 0 */
  w22 = 0.;
  /* #43: @23 = 0 */
  w23 = 0.;
  /* #44: @24 = input[0][10] */
  w24 = arg[0] ? arg[0][10] : 0;
  /* #45: @25 = (-@24) */
  w25 = (- w24 );
  /* #46: @26 = horzcat(@21, @22, @23, @25) */
  rr=w26;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w25;
  /* #47: @26 = @26' */
  /* #48: @21 = 0 */
  w21 = 0.;
  /* #49: @22 = 0 */
  w22 = 0.;
  /* #50: @23 = 0 */
  w23 = 0.;
  /* #51: @27 = horzcat(@21, @22, @24, @23) */
  rr=w27;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w24;
  *rr++ = w23;
  /* #52: @27 = @27' */
  /* #53: @21 = 0 */
  w21 = 0.;
  /* #54: @22 = (-@24) */
  w22 = (- w24 );
  /* #55: @23 = 0 */
  w23 = 0.;
  /* #56: @25 = 0 */
  w25 = 0.;
  /* #57: @28 = horzcat(@21, @22, @23, @25) */
  rr=w28;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w25;
  /* #58: @28 = @28' */
  /* #59: @21 = 0 */
  w21 = 0.;
  /* #60: @22 = 0 */
  w22 = 0.;
  /* #61: @23 = 0 */
  w23 = 0.;
  /* #62: @29 = horzcat(@24, @21, @22, @23) */
  rr=w29;
  *rr++ = w24;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #63: @29 = @29' */
  /* #64: @30 = horzcat(@26, @27, @28, @29) */
  rr=w30;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  /* #65: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #66: @31 = (@20*@31) */
  for (i=0, rr=w31, cs=w31; i<16; ++i) (*rr++)  = (w20*(*cs++));
  /* #67: @30 = zeros(4x4) */
  casadi_clear(w30, 16);
  /* #68: @32 = horzcat(@19, @31, @30) */
  rr=w32;
  for (i=0, cs=w19; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<16; ++i) *rr++ = *cs++;
  /* #69: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #70: @34 = zeros(4x7) */
  casadi_clear(w34, 28);
  /* #71: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #72: @30 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w30);
  /* #73: @35 = zeros(4x4) */
  casadi_clear(w35, 16);
  /* #74: @21 = 0.6756 */
  w21 = 6.7559999999999998e-01;
  /* #75: (@35[0] = @21) */
  for (rr=w35+0, ss=(&w21); rr!=w35+1; rr+=1) *rr = *ss++;
  /* #76: @21 = 0 */
  w21 = 0.;
  /* #77: (@35[4] = @21) */
  for (rr=w35+4, ss=(&w21); rr!=w35+5; rr+=1) *rr = *ss++;
  /* #78: @21 = 0 */
  w21 = 0.;
  /* #79: (@35[8] = @21) */
  for (rr=w35+8, ss=(&w21); rr!=w35+9; rr+=1) *rr = *ss++;
  /* #80: @21 = 0 */
  w21 = 0.;
  /* #81: (@35[12] = @21) */
  for (rr=w35+12, ss=(&w21); rr!=w35+13; rr+=1) *rr = *ss++;
  /* #82: @21 = 0 */
  w21 = 0.;
  /* #83: (@35[1] = @21) */
  for (rr=w35+1, ss=(&w21); rr!=w35+2; rr+=1) *rr = *ss++;
  /* #84: @21 = 0.6344 */
  w21 = 6.3439999999999996e-01;
  /* #85: (@35[5] = @21) */
  for (rr=w35+5, ss=(&w21); rr!=w35+6; rr+=1) *rr = *ss++;
  /* #86: @21 = 0 */
  w21 = 0.;
  /* #87: (@35[9] = @21) */
  for (rr=w35+9, ss=(&w21); rr!=w35+10; rr+=1) *rr = *ss++;
  /* #88: @21 = 0 */
  w21 = 0.;
  /* #89: (@35[13] = @21) */
  for (rr=w35+13, ss=(&w21); rr!=w35+14; rr+=1) *rr = *ss++;
  /* #90: @21 = 0 */
  w21 = 0.;
  /* #91: (@35[2] = @21) */
  for (rr=w35+2, ss=(&w21); rr!=w35+3; rr+=1) *rr = *ss++;
  /* #92: @21 = 0 */
  w21 = 0.;
  /* #93: (@35[6] = @21) */
  for (rr=w35+6, ss=(&w21); rr!=w35+7; rr+=1) *rr = *ss++;
  /* #94: @21 = 0.408 */
  w21 = 4.0799999999999997e-01;
  /* #95: (@35[10] = @21) */
  for (rr=w35+10, ss=(&w21); rr!=w35+11; rr+=1) *rr = *ss++;
  /* #96: @21 = 0 */
  w21 = 0.;
  /* #97: (@35[14] = @21) */
  for (rr=w35+14, ss=(&w21); rr!=w35+15; rr+=1) *rr = *ss++;
  /* #98: @21 = 0 */
  w21 = 0.;
  /* #99: (@35[3] = @21) */
  for (rr=w35+3, ss=(&w21); rr!=w35+4; rr+=1) *rr = *ss++;
  /* #100: @21 = 0 */
  w21 = 0.;
  /* #101: (@35[7] = @21) */
  for (rr=w35+7, ss=(&w21); rr!=w35+8; rr+=1) *rr = *ss++;
  /* #102: @21 = 0 */
  w21 = 0.;
  /* #103: (@35[11] = @21) */
  for (rr=w35+11, ss=(&w21); rr!=w35+12; rr+=1) *rr = *ss++;
  /* #104: @21 = 0.2953 */
  w21 = 2.9530000000000001e-01;
  /* #105: (@35[15] = @21) */
  for (rr=w35+15, ss=(&w21); rr!=w35+16; rr+=1) *rr = *ss++;
  /* #106: @30 = (@35\@30) */
  rr = w30;
  ss = w35;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #107: @36 = zeros(4x4) */
  casadi_clear(w36, 16);
  /* #108: @21 = 0.5941 */
  w21 = 5.9409999999999996e-01;
  /* #109: (@36[0] = @21) */
  for (rr=w36+0, ss=(&w21); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #110: @21 = -0.8109 */
  w21 = -8.1089999999999995e-01;
  /* #111: @22 = (@21*@24) */
  w22  = (w21*w24);
  /* #112: (@36[4] = @22) */
  for (rr=w36+4, ss=(&w22); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #113: @22 = 0 */
  w22 = 0.;
  /* #114: (@36[8] = @22) */
  for (rr=w36+8, ss=(&w22); rr!=w36+9; rr+=1) *rr = *ss++;
  /* #115: @22 = 0 */
  w22 = 0.;
  /* #116: (@36[12] = @22) */
  for (rr=w36+12, ss=(&w22); rr!=w36+13; rr+=1) *rr = *ss++;
  /* #117: @22 = 0.3984 */
  w22 = 3.9839999999999998e-01;
  /* #118: @23 = (@22*@24) */
  w23  = (w22*w24);
  /* #119: (@36[1] = @23) */
  for (rr=w36+1, ss=(&w23); rr!=w36+2; rr+=1) *rr = *ss++;
  /* #120: @23 = 0.704 */
  w23 = 7.0399999999999996e-01;
  /* #121: (@36[5] = @23) */
  for (rr=w36+5, ss=(&w23); rr!=w36+6; rr+=1) *rr = *ss++;
  /* #122: @23 = 0 */
  w23 = 0.;
  /* #123: (@36[9] = @23) */
  for (rr=w36+9, ss=(&w23); rr!=w36+10; rr+=1) *rr = *ss++;
  /* #124: @23 = 0 */
  w23 = 0.;
  /* #125: (@36[13] = @23) */
  for (rr=w36+13, ss=(&w23); rr!=w36+14; rr+=1) *rr = *ss++;
  /* #126: @23 = 0 */
  w23 = 0.;
  /* #127: (@36[2] = @23) */
  for (rr=w36+2, ss=(&w23); rr!=w36+3; rr+=1) *rr = *ss++;
  /* #128: @23 = 0 */
  w23 = 0.;
  /* #129: (@36[6] = @23) */
  for (rr=w36+6, ss=(&w23); rr!=w36+7; rr+=1) *rr = *ss++;
  /* #130: @23 = 0.9365 */
  w23 = 9.3650000000000000e-01;
  /* #131: (@36[10] = @23) */
  for (rr=w36+10, ss=(&w23); rr!=w36+11; rr+=1) *rr = *ss++;
  /* #132: @23 = 0 */
  w23 = 0.;
  /* #133: (@36[14] = @23) */
  for (rr=w36+14, ss=(&w23); rr!=w36+15; rr+=1) *rr = *ss++;
  /* #134: @23 = 0 */
  w23 = 0.;
  /* #135: (@36[3] = @23) */
  for (rr=w36+3, ss=(&w23); rr!=w36+4; rr+=1) *rr = *ss++;
  /* #136: @23 = 0 */
  w23 = 0.;
  /* #137: (@36[7] = @23) */
  for (rr=w36+7, ss=(&w23); rr!=w36+8; rr+=1) *rr = *ss++;
  /* #138: @23 = 0 */
  w23 = 0.;
  /* #139: (@36[11] = @23) */
  for (rr=w36+11, ss=(&w23); rr!=w36+12; rr+=1) *rr = *ss++;
  /* #140: @23 = 0.9752 */
  w23 = 9.7519999999999996e-01;
  /* #141: (@36[15] = @23) */
  for (rr=w36+15, ss=(&w23); rr!=w36+16; rr+=1) *rr = *ss++;
  /* #142: @31 = mac(@30,@36,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w30+j, tt=w36+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #143: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<16; ++i) *rr++ = (- *cs++ );
  /* #144: @32 = horzcat(@34, @31) */
  rr=w32;
  for (i=0, cs=w34; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<16; ++i) *rr++ = *cs++;
  /* #145: @37 = @32' */
  for (i=0, rr=w37, cs=w32; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #146: @38 = horzcat(@18, @33, @37) */
  rr=w38;
  for (i=0, cs=w18; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<44; ++i) *rr++ = *cs++;
  /* #147: @16 = zeros(11x1,3nz) */
  casadi_clear(w16, 3);
  /* #148: @23 = input[0][0] */
  w23 = arg[0] ? arg[0][0] : 0;
  /* #149: @25 = input[3][18] */
  w25 = arg[3] ? arg[3][18] : 0;
  /* #150: @39 = (@23-@25) */
  w39  = (w23-w25);
  /* #151: @40 = (2.*@39) */
  w40 = (2.* w39 );
  /* #152: @41 = sq(@39) */
  w41 = casadi_sq( w39 );
  /* #153: @42 = input[0][1] */
  w42 = arg[0] ? arg[0][1] : 0;
  /* #154: @43 = input[3][19] */
  w43 = arg[3] ? arg[3][19] : 0;
  /* #155: @44 = (@42-@43) */
  w44  = (w42-w43);
  /* #156: @45 = sq(@44) */
  w45 = casadi_sq( w44 );
  /* #157: @41 = (@41+@45) */
  w41 += w45;
  /* #158: @45 = input[0][2] */
  w45 = arg[0] ? arg[0][2] : 0;
  /* #159: @46 = input[3][20] */
  w46 = arg[3] ? arg[3][20] : 0;
  /* #160: @47 = (@45-@46) */
  w47  = (w45-w46);
  /* #161: @48 = sq(@47) */
  w48 = casadi_sq( w47 );
  /* #162: @41 = (@41+@48) */
  w41 += w48;
  /* #163: @41 = sqrt(@41) */
  w41 = sqrt( w41 );
  /* #164: @48 = (2.*@41) */
  w48 = (2.* w41 );
  /* #165: @40 = (@40/@48) */
  w40 /= w48;
  /* #166: (@16[0] = @40) */
  for (rr=w16+0, ss=(&w40); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #167: @49 = (2.*@44) */
  w49 = (2.* w44 );
  /* #168: @49 = (@49/@48) */
  w49 /= w48;
  /* #169: (@16[1] = @49) */
  for (rr=w16+1, ss=(&w49); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #170: @50 = (2.*@47) */
  w50 = (2.* w47 );
  /* #171: @50 = (@50/@48) */
  w50 /= w48;
  /* #172: (@16[2] = @50) */
  for (rr=w16+2, ss=(&w50); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #173: @51 = dense(@16) */
  casadi_densify(w16, casadi_s4, w51, 0);
  /* #174: @2 = mac(@38,@51,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w38+j, tt=w51+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #175: {@52, @53, @54, @55, @56, @57, @58, @59, @60, @61, @62} = vertsplit(@2) */
  w52 = w2[0];
  w53 = w2[1];
  w54 = w2[2];
  w55 = w2[3];
  w56 = w2[4];
  w57 = w2[5];
  w58 = w2[6];
  w59 = w2[7];
  w60 = w2[8];
  w61 = w2[9];
  w62 = w2[10];
  /* #176: @63 = (2.*@39) */
  w63 = (2.* w39 );
  /* #177: @64 = (@49/@48) */
  w64  = (w49/w48);
  /* #178: @2 = zeros(11x1) */
  casadi_clear(w2, 11);
  /* #179: @65 = @38' */
  for (i=0, rr=w65, cs=w38; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #180: @66 = input[0][7] */
  w66 = arg[0] ? arg[0][7] : 0;
  /* #181: @67 = input[0][8] */
  w67 = arg[0] ? arg[0][8] : 0;
  /* #182: @68 = input[0][9] */
  w68 = arg[0] ? arg[0][9] : 0;
  /* #183: @69 = vertcat(@23, @42, @45, @7, @8, @9, @10, @66, @67, @68, @24) */
  rr=w69;
  *rr++ = w23;
  *rr++ = w42;
  *rr++ = w45;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w68;
  *rr++ = w24;
  /* #184: @2 = mac(@65,@69,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w65+j, tt=w69+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #185: @70 = zeros(11x1) */
  casadi_clear(w70, 11);
  /* #186: @34 = zeros(4x7) */
  casadi_clear(w34, 28);
  /* #187: @31 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w31);
  /* #188: @31 = (@35\@31) */
  rr = w31;
  ss = w35;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #189: @35 = @31' */
  for (i=0, rr=w35, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #190: @33 = horzcat(@34, @35) */
  rr=w33;
  for (i=0, cs=w34; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<16; ++i) *rr++ = *cs++;
  /* #191: @37 = @33' */
  for (i=0, rr=w37, cs=w33; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #192: @24 = input[1][0] */
  w24 = arg[1] ? arg[1][0] : 0;
  /* #193: @71 = input[1][1] */
  w71 = arg[1] ? arg[1][1] : 0;
  /* #194: @72 = input[1][2] */
  w72 = arg[1] ? arg[1][2] : 0;
  /* #195: @73 = input[1][3] */
  w73 = arg[1] ? arg[1][3] : 0;
  /* #196: @26 = vertcat(@24, @71, @72, @73) */
  rr=w26;
  *rr++ = w24;
  *rr++ = w71;
  *rr++ = w72;
  *rr++ = w73;
  /* #197: @70 = mac(@37,@26,@70) */
  for (i=0, rr=w70; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w37+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*11]**tt++;
  /* #198: @2 = (@2+@70) */
  for (i=0, rr=w2, cs=w70; i<11; ++i) (*rr++) += (*cs++);
  /* #199: @24 = 0 */
  w24 = 0.;
  /* #200: @70 = @2; (@70[2] = @24) */
  casadi_copy(w2, 11, w70);
  for (rr=w70+2, ss=(&w24); rr!=w70+3; rr+=1) *rr = *ss++;
  /* #201: @24 = @70[1] */
  for (rr=(&w24), ss=w70+1; ss!=w70+2; ss+=1) *rr++ = *ss;
  /* #202: @64 = (@64*@24) */
  w64 *= w24;
  /* #203: @64 = (-@64) */
  w64 = (- w64 );
  /* #204: @71 = (@50/@48) */
  w71  = (w50/w48);
  /* #205: @72 = @2[2] */
  for (rr=(&w72), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #206: @71 = (@71*@72) */
  w71 *= w72;
  /* #207: @64 = (@64-@71) */
  w64 -= w71;
  /* #208: @71 = (@40/@48) */
  w71  = (w40/w48);
  /* #209: @73 = 0 */
  w73 = 0.;
  /* #210: (@70[1] = @73) */
  for (rr=w70+1, ss=(&w73); rr!=w70+2; rr+=1) *rr = *ss++;
  /* #211: @73 = @70[0] */
  for (rr=(&w73), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #212: @71 = (@71*@73) */
  w71 *= w73;
  /* #213: @64 = (@64-@71) */
  w64 -= w71;
  /* #214: @64 = (2.*@64) */
  w64 = (2.* w64 );
  /* #215: @71 = (2.*@41) */
  w71 = (2.* w41 );
  /* #216: @64 = (@64/@71) */
  w64 /= w71;
  /* #217: @63 = (@63*@64) */
  w63 *= w64;
  /* #218: @73 = (@73/@48) */
  w73 /= w48;
  /* #219: @73 = (2.*@73) */
  w73 = (2.* w73 );
  /* #220: @63 = (@63+@73) */
  w63 += w73;
  /* #221: @52 = (@52+@63) */
  w52 += w63;
  /* #222: (@1[0] = @52) */
  for (rr=w1+0, ss=(&w52); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #223: @24 = (@24/@48) */
  w24 /= w48;
  /* #224: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #225: @52 = (2.*@44) */
  w52 = (2.* w44 );
  /* #226: @52 = (@52*@64) */
  w52 *= w64;
  /* #227: @24 = (@24+@52) */
  w24 += w52;
  /* #228: @53 = (@53+@24) */
  w53 += w24;
  /* #229: (@1[1] = @53) */
  for (rr=w1+1, ss=(&w53); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #230: @72 = (@72/@48) */
  w72 /= w48;
  /* #231: @72 = (2.*@72) */
  w72 = (2.* w72 );
  /* #232: @53 = (2.*@47) */
  w53 = (2.* w47 );
  /* #233: @53 = (@53*@64) */
  w53 *= w64;
  /* #234: @72 = (@72+@53) */
  w72 += w53;
  /* #235: @54 = (@54+@72) */
  w54 += w72;
  /* #236: (@1[2] = @54) */
  for (rr=w1+2, ss=(&w54); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #237: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #238: @65 = zeros(11x11) */
  casadi_clear(w65, 121);
  /* #239: @70 = @69' */
  casadi_copy(w69, 11, w70);
  /* #240: @65 = mac(@51,@70,@65) */
  for (i=0, rr=w65; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w51+j, tt=w70+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #241: @74 = @65' */
  for (i=0, rr=w74, cs=w65; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #242: {@18, @33, @32} = horzsplit(@74) */
  casadi_copy(w74, 33, w18);
  casadi_copy(w74+33, 44, w33);
  casadi_copy(w74+77, 44, w32);
  /* #243: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #244: {NULL, @4, NULL} = horzsplit(@17) */
  casadi_copy(w17+21, 9, w4);
  /* #245: @54 = dot(@6, @4) */
  w54 = casadi_dot(9, w6, w4);
  /* #246: @54 = (2.*@54) */
  w54 = (2.* w54 );
  /* #247: (@27[0] += @54) */
  for (rr=w27+0, ss=(&w54); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #248: @5 = (@14*@4) */
  for (i=0, rr=w5, cs=w4; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #249: @75 = zeros(3x3) */
  casadi_clear(w75, 9);
  /* #250: @76 = @15' */
  for (i=0, rr=w76, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #251: @75 = mac(@76,@4,@75) */
  for (i=0, rr=w75; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #252: @5 = (@5+@75) */
  for (i=0, rr=w5, cs=w75; i<9; ++i) (*rr++) += (*cs++);
  /* #253: @75 = zeros(3x3) */
  casadi_clear(w75, 9);
  /* #254: @76 = @6' */
  for (i=0, rr=w76, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #255: @75 = mac(@4,@76,@75) */
  for (i=0, rr=w75; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w76+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #256: @75 = (2.*@75) */
  for (i=0, rr=w75, cs=w75; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #257: @5 = (@5+@75) */
  for (i=0, rr=w5, cs=w75; i<9; ++i) (*rr++) += (*cs++);
  /* #258: @54 = @5[5] */
  for (rr=(&w54), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #259: (@27[1] += @54) */
  for (rr=w27+1, ss=(&w54); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #260: @54 = 0 */
  w54 = 0.;
  /* #261: (@5[5] = @54) */
  for (rr=w5+5, ss=(&w54); rr!=w5+6; rr+=1) *rr = *ss++;
  /* #262: @54 = @5[2] */
  for (rr=(&w54), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #263: @54 = (-@54) */
  w54 = (- w54 );
  /* #264: (@27[2] += @54) */
  for (rr=w27+2, ss=(&w54); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #265: @54 = 0 */
  w54 = 0.;
  /* #266: (@5[2] = @54) */
  for (rr=w5+2, ss=(&w54); rr!=w5+3; rr+=1) *rr = *ss++;
  /* #267: @54 = @5[1] */
  for (rr=(&w54), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #268: (@27[3] += @54) */
  for (rr=w27+3, ss=(&w54); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #269: @54 = 0 */
  w54 = 0.;
  /* #270: (@5[1] = @54) */
  for (rr=w5+1, ss=(&w54); rr!=w5+2; rr+=1) *rr = *ss++;
  /* #271: @54 = @5[7] */
  for (rr=(&w54), ss=w5+7; ss!=w5+8; ss+=1) *rr++ = *ss;
  /* #272: @54 = (-@54) */
  w54 = (- w54 );
  /* #273: (@27[1] += @54) */
  for (rr=w27+1, ss=(&w54); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #274: @54 = 0 */
  w54 = 0.;
  /* #275: (@5[7] = @54) */
  for (rr=w5+7, ss=(&w54); rr!=w5+8; rr+=1) *rr = *ss++;
  /* #276: @54 = @5[6] */
  for (rr=(&w54), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #277: (@27[2] += @54) */
  for (rr=w27+2, ss=(&w54); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #278: @54 = 0 */
  w54 = 0.;
  /* #279: (@5[6] = @54) */
  for (rr=w5+6, ss=(&w54); rr!=w5+7; rr+=1) *rr = *ss++;
  /* #280: @54 = @5[3] */
  for (rr=(&w54), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #281: @54 = (-@54) */
  w54 = (- w54 );
  /* #282: (@27[3] += @54) */
  for (rr=w27+3, ss=(&w54); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #283: @28 = (@27/@12) */
  for (i=0, rr=w28, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #284: @29 = (@13/@12) */
  for (i=0, rr=w29, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #285: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) *rr++ = (- *cs++ );
  /* #286: @54 = dot(@29, @27) */
  w54 = casadi_dot(4, w29, w27);
  /* #287: @54 = (@54/@12) */
  w54 /= w12;
  /* #288: @29 = (@54*@11) */
  for (i=0, rr=w29, cs=w11; i<4; ++i) (*rr++)  = (w54*(*cs++));
  /* #289: @28 = (@28+@29) */
  for (i=0, rr=w28, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #290: {@54, @72, @53, @64} = vertsplit(@28) */
  w54 = w28[0];
  w72 = w28[1];
  w53 = w28[2];
  w64 = w28[3];
  /* #291: @55 = (@55+@54) */
  w55 += w54;
  /* #292: (@1[3] = @55) */
  for (rr=w1+3, ss=(&w55); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #293: @56 = (@56+@72) */
  w56 += w72;
  /* #294: (@1[4] = @56) */
  for (rr=w1+4, ss=(&w56); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #295: @57 = (@57+@53) */
  w57 += w53;
  /* #296: (@1[5] = @57) */
  for (rr=w1+5, ss=(&w57); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #297: @58 = (@58+@64) */
  w58 += w64;
  /* #298: (@1[6] = @58) */
  for (rr=w1+6, ss=(&w58); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #299: (@1[7] = @59) */
  for (rr=w1+7, ss=(&w59); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #300: (@1[8] = @60) */
  for (rr=w1+8, ss=(&w60); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #301: (@1[9] = @61) */
  for (rr=w1+9, ss=(&w61); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #302: @35 = zeros(4x4) */
  casadi_clear(w35, 16);
  /* #303: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #304: @77 = @32' */
  for (i=0, rr=w77, cs=w32; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #305: {NULL, @36} = horzsplit(@77) */
  casadi_copy(w77+28, 16, w36);
  /* #306: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<16; ++i) *rr++ = (- *cs++ );
  /* #307: @35 = mac(@31,@36,@35) */
  for (i=0, rr=w35; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w31+j, tt=w36+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #308: @61 = 0 */
  w61 = 0.;
  /* #309: (@35[15] = @61) */
  for (rr=w35+15, ss=(&w61); rr!=w35+16; rr+=1) *rr = *ss++;
  /* #310: @61 = 0 */
  w61 = 0.;
  /* #311: (@35[11] = @61) */
  for (rr=w35+11, ss=(&w61); rr!=w35+12; rr+=1) *rr = *ss++;
  /* #312: @61 = 0 */
  w61 = 0.;
  /* #313: (@35[7] = @61) */
  for (rr=w35+7, ss=(&w61); rr!=w35+8; rr+=1) *rr = *ss++;
  /* #314: @61 = 0 */
  w61 = 0.;
  /* #315: (@35[3] = @61) */
  for (rr=w35+3, ss=(&w61); rr!=w35+4; rr+=1) *rr = *ss++;
  /* #316: @61 = 0 */
  w61 = 0.;
  /* #317: (@35[14] = @61) */
  for (rr=w35+14, ss=(&w61); rr!=w35+15; rr+=1) *rr = *ss++;
  /* #318: @61 = 0 */
  w61 = 0.;
  /* #319: (@35[10] = @61) */
  for (rr=w35+10, ss=(&w61); rr!=w35+11; rr+=1) *rr = *ss++;
  /* #320: @61 = 0 */
  w61 = 0.;
  /* #321: (@35[6] = @61) */
  for (rr=w35+6, ss=(&w61); rr!=w35+7; rr+=1) *rr = *ss++;
  /* #322: @61 = 0 */
  w61 = 0.;
  /* #323: (@35[2] = @61) */
  for (rr=w35+2, ss=(&w61); rr!=w35+3; rr+=1) *rr = *ss++;
  /* #324: @61 = 0 */
  w61 = 0.;
  /* #325: (@35[13] = @61) */
  for (rr=w35+13, ss=(&w61); rr!=w35+14; rr+=1) *rr = *ss++;
  /* #326: @61 = 0 */
  w61 = 0.;
  /* #327: (@35[9] = @61) */
  for (rr=w35+9, ss=(&w61); rr!=w35+10; rr+=1) *rr = *ss++;
  /* #328: @61 = 0 */
  w61 = 0.;
  /* #329: (@35[5] = @61) */
  for (rr=w35+5, ss=(&w61); rr!=w35+6; rr+=1) *rr = *ss++;
  /* #330: @61 = @35[1] */
  for (rr=(&w61), ss=w35+1; ss!=w35+2; ss+=1) *rr++ = *ss;
  /* #331: @61 = (@22*@61) */
  w61  = (w22*w61);
  /* #332: @62 = (@62+@61) */
  w62 += w61;
  /* #333: @61 = 0 */
  w61 = 0.;
  /* #334: (@35[1] = @61) */
  for (rr=w35+1, ss=(&w61); rr!=w35+2; rr+=1) *rr = *ss++;
  /* #335: @61 = 0 */
  w61 = 0.;
  /* #336: (@35[12] = @61) */
  for (rr=w35+12, ss=(&w61); rr!=w35+13; rr+=1) *rr = *ss++;
  /* #337: @61 = 0 */
  w61 = 0.;
  /* #338: (@35[8] = @61) */
  for (rr=w35+8, ss=(&w61); rr!=w35+9; rr+=1) *rr = *ss++;
  /* #339: @61 = @35[4] */
  for (rr=(&w61), ss=w35+4; ss!=w35+5; ss+=1) *rr++ = *ss;
  /* #340: @61 = (@21*@61) */
  w61  = (w21*w61);
  /* #341: @62 = (@62+@61) */
  w62 += w61;
  /* #342: @77 = @33' */
  for (i=0, rr=w77, cs=w33; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #343: {NULL, @35, NULL} = horzsplit(@77) */
  casadi_copy(w77+12, 16, w35);
  /* #344: @35 = (@20*@35) */
  for (i=0, rr=w35, cs=w35; i<16; ++i) (*rr++)  = (w20*(*cs++));
  /* #345: @31 = @35' */
  for (i=0, rr=w31, cs=w35; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #346: {@28, @29, @27, @78} = horzsplit(@31) */
  casadi_copy(w31, 4, w28);
  casadi_copy(w31+4, 4, w29);
  casadi_copy(w31+8, 4, w27);
  casadi_copy(w31+12, 4, w78);
  /* #347: @78 = @78' */
  /* #348: {@61, NULL, NULL, NULL} = horzsplit(@78) */
  w61 = w78[0];
  /* #349: @62 = (@62+@61) */
  w62 += w61;
  /* #350: @27 = @27' */
  /* #351: {NULL, @61, NULL, NULL} = horzsplit(@27) */
  w61 = w27[1];
  /* #352: @62 = (@62-@61) */
  w62 -= w61;
  /* #353: @29 = @29' */
  /* #354: {NULL, NULL, @61, NULL} = horzsplit(@29) */
  w61 = w29[2];
  /* #355: @62 = (@62+@61) */
  w62 += w61;
  /* #356: @28 = @28' */
  /* #357: {NULL, NULL, NULL, @61} = horzsplit(@28) */
  w61 = w28[3];
  /* #358: @62 = (@62-@61) */
  w62 -= w61;
  /* #359: (@1[10] = @62) */
  for (rr=w1+10, ss=(&w62); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #360: @1 = @1' */
  /* #361: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*11; k<11; ++k) *rr += ss[k*1]**tt++;
  /* #362: @62 = 0 */
  w62 = 0.;
  /* #363: @28 = zeros(1x4) */
  casadi_clear(w28, 4);
  /* #364: @1 = zeros(11x1) */
  casadi_clear(w1, 11);
  /* #365: @51 = zeros(11x1) */
  casadi_clear(w51, 11);
  /* #366: @70 = dense(@16) */
  casadi_densify(w16, casadi_s4, w70, 0);
  /* #367: @51 = mac(@38,@70,@51) */
  for (i=0, rr=w51; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w38+j, tt=w70+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #368: {@61, @60, @59, @58, @64, @57, @53, @56, @72, @55, @54} = vertsplit(@51) */
  w61 = w51[0];
  w60 = w51[1];
  w59 = w51[2];
  w58 = w51[3];
  w64 = w51[4];
  w57 = w51[5];
  w53 = w51[6];
  w56 = w51[7];
  w72 = w51[8];
  w55 = w51[9];
  w54 = w51[10];
  /* #369: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #370: @49 = (@49/@48) */
  w49 /= w48;
  /* #371: @24 = 0 */
  w24 = 0.;
  /* #372: @51 = @2; (@51[2] = @24) */
  casadi_copy(w2, 11, w51);
  for (rr=w51+2, ss=(&w24); rr!=w51+3; rr+=1) *rr = *ss++;
  /* #373: @24 = @51[1] */
  for (rr=(&w24), ss=w51+1; ss!=w51+2; ss+=1) *rr++ = *ss;
  /* #374: @49 = (@49*@24) */
  w49 *= w24;
  /* #375: @49 = (-@49) */
  w49 = (- w49 );
  /* #376: @50 = (@50/@48) */
  w50 /= w48;
  /* #377: @52 = @2[2] */
  for (rr=(&w52), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #378: @50 = (@50*@52) */
  w50 *= w52;
  /* #379: @49 = (@49-@50) */
  w49 -= w50;
  /* #380: @40 = (@40/@48) */
  w40 /= w48;
  /* #381: @50 = 0 */
  w50 = 0.;
  /* #382: (@51[1] = @50) */
  for (rr=w51+1, ss=(&w50); rr!=w51+2; rr+=1) *rr = *ss++;
  /* #383: @50 = @51[0] */
  for (rr=(&w50), ss=w51+0; ss!=w51+1; ss+=1) *rr++ = *ss;
  /* #384: @40 = (@40*@50) */
  w40 *= w50;
  /* #385: @49 = (@49-@40) */
  w49 -= w40;
  /* #386: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #387: @40 = (2.*@41) */
  w40 = (2.* w41 );
  /* #388: @49 = (@49/@40) */
  w49 /= w40;
  /* #389: @39 = (@39*@49) */
  w39 *= w49;
  /* #390: @50 = (@50/@48) */
  w50 /= w48;
  /* #391: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #392: @39 = (@39+@50) */
  w39 += w50;
  /* #393: @61 = (@61+@39) */
  w61 += w39;
  /* #394: (@1[0] = @61) */
  for (rr=w1+0, ss=(&w61); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #395: @24 = (@24/@48) */
  w24 /= w48;
  /* #396: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #397: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #398: @44 = (@44*@49) */
  w44 *= w49;
  /* #399: @24 = (@24+@44) */
  w24 += w44;
  /* #400: @60 = (@60+@24) */
  w60 += w24;
  /* #401: (@1[1] = @60) */
  for (rr=w1+1, ss=(&w60); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #402: @52 = (@52/@48) */
  w52 /= w48;
  /* #403: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #404: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #405: @47 = (@47*@49) */
  w47 *= w49;
  /* #406: @52 = (@52+@47) */
  w52 += w47;
  /* #407: @59 = (@59+@52) */
  w59 += w52;
  /* #408: (@1[2] = @59) */
  for (rr=w1+2, ss=(&w59); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #409: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #410: @74 = zeros(11x11) */
  casadi_clear(w74, 121);
  /* #411: @51 = @69' */
  casadi_copy(w69, 11, w51);
  /* #412: @74 = mac(@70,@51,@74) */
  for (i=0, rr=w74; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w70+j, tt=w51+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #413: @65 = @74' */
  for (i=0, rr=w65, cs=w74; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #414: {@17, @77, @33} = horzsplit(@65) */
  casadi_copy(w65, 33, w17);
  casadi_copy(w65+33, 44, w77);
  casadi_copy(w65+77, 44, w33);
  /* #415: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #416: {NULL, @5, NULL} = horzsplit(@18) */
  casadi_copy(w18+21, 9, w5);
  /* #417: @59 = dot(@6, @5) */
  w59 = casadi_dot(9, w6, w5);
  /* #418: @59 = (2.*@59) */
  w59 = (2.* w59 );
  /* #419: (@29[0] += @59) */
  for (rr=w29+0, ss=(&w59); rr!=w29+1; rr+=1) *rr += *ss++;
  /* #420: @75 = (@14*@5) */
  for (i=0, rr=w75, cs=w5; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #421: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #422: @76 = @15' */
  for (i=0, rr=w76, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #423: @4 = mac(@76,@5,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #424: @75 = (@75+@4) */
  for (i=0, rr=w75, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #425: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #426: @76 = @6' */
  for (i=0, rr=w76, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #427: @4 = mac(@5,@76,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w76+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #428: @4 = (2.*@4) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #429: @75 = (@75+@4) */
  for (i=0, rr=w75, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #430: @59 = @75[5] */
  for (rr=(&w59), ss=w75+5; ss!=w75+6; ss+=1) *rr++ = *ss;
  /* #431: (@29[1] += @59) */
  for (rr=w29+1, ss=(&w59); rr!=w29+2; rr+=1) *rr += *ss++;
  /* #432: @59 = 0 */
  w59 = 0.;
  /* #433: (@75[5] = @59) */
  for (rr=w75+5, ss=(&w59); rr!=w75+6; rr+=1) *rr = *ss++;
  /* #434: @59 = @75[2] */
  for (rr=(&w59), ss=w75+2; ss!=w75+3; ss+=1) *rr++ = *ss;
  /* #435: @59 = (-@59) */
  w59 = (- w59 );
  /* #436: (@29[2] += @59) */
  for (rr=w29+2, ss=(&w59); rr!=w29+3; rr+=1) *rr += *ss++;
  /* #437: @59 = 0 */
  w59 = 0.;
  /* #438: (@75[2] = @59) */
  for (rr=w75+2, ss=(&w59); rr!=w75+3; rr+=1) *rr = *ss++;
  /* #439: @59 = @75[1] */
  for (rr=(&w59), ss=w75+1; ss!=w75+2; ss+=1) *rr++ = *ss;
  /* #440: (@29[3] += @59) */
  for (rr=w29+3, ss=(&w59); rr!=w29+4; rr+=1) *rr += *ss++;
  /* #441: @59 = 0 */
  w59 = 0.;
  /* #442: (@75[1] = @59) */
  for (rr=w75+1, ss=(&w59); rr!=w75+2; rr+=1) *rr = *ss++;
  /* #443: @59 = @75[7] */
  for (rr=(&w59), ss=w75+7; ss!=w75+8; ss+=1) *rr++ = *ss;
  /* #444: @59 = (-@59) */
  w59 = (- w59 );
  /* #445: (@29[1] += @59) */
  for (rr=w29+1, ss=(&w59); rr!=w29+2; rr+=1) *rr += *ss++;
  /* #446: @59 = 0 */
  w59 = 0.;
  /* #447: (@75[7] = @59) */
  for (rr=w75+7, ss=(&w59); rr!=w75+8; rr+=1) *rr = *ss++;
  /* #448: @59 = @75[6] */
  for (rr=(&w59), ss=w75+6; ss!=w75+7; ss+=1) *rr++ = *ss;
  /* #449: (@29[2] += @59) */
  for (rr=w29+2, ss=(&w59); rr!=w29+3; rr+=1) *rr += *ss++;
  /* #450: @59 = 0 */
  w59 = 0.;
  /* #451: (@75[6] = @59) */
  for (rr=w75+6, ss=(&w59); rr!=w75+7; rr+=1) *rr = *ss++;
  /* #452: @59 = @75[3] */
  for (rr=(&w59), ss=w75+3; ss!=w75+4; ss+=1) *rr++ = *ss;
  /* #453: @59 = (-@59) */
  w59 = (- w59 );
  /* #454: (@29[3] += @59) */
  for (rr=w29+3, ss=(&w59); rr!=w29+4; rr+=1) *rr += *ss++;
  /* #455: @27 = (@29/@12) */
  for (i=0, rr=w27, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #456: @78 = (@13/@12) */
  for (i=0, rr=w78, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #457: @78 = (-@78) */
  for (i=0, rr=w78, cs=w78; i<4; ++i) *rr++ = (- *cs++ );
  /* #458: @59 = dot(@78, @29) */
  w59 = casadi_dot(4, w78, w29);
  /* #459: @59 = (@59/@12) */
  w59 /= w12;
  /* #460: @78 = (@59*@11) */
  for (i=0, rr=w78, cs=w11; i<4; ++i) (*rr++)  = (w59*(*cs++));
  /* #461: @27 = (@27+@78) */
  for (i=0, rr=w27, cs=w78; i<4; ++i) (*rr++) += (*cs++);
  /* #462: {@59, @52, @47, @49} = vertsplit(@27) */
  w59 = w27[0];
  w52 = w27[1];
  w47 = w27[2];
  w49 = w27[3];
  /* #463: @58 = (@58+@59) */
  w58 += w59;
  /* #464: (@1[3] = @58) */
  for (rr=w1+3, ss=(&w58); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #465: @64 = (@64+@52) */
  w64 += w52;
  /* #466: (@1[4] = @64) */
  for (rr=w1+4, ss=(&w64); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #467: @57 = (@57+@47) */
  w57 += w47;
  /* #468: (@1[5] = @57) */
  for (rr=w1+5, ss=(&w57); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #469: @53 = (@53+@49) */
  w53 += w49;
  /* #470: (@1[6] = @53) */
  for (rr=w1+6, ss=(&w53); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #471: (@1[7] = @56) */
  for (rr=w1+7, ss=(&w56); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #472: (@1[8] = @72) */
  for (rr=w1+8, ss=(&w72); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #473: (@1[9] = @55) */
  for (rr=w1+9, ss=(&w55); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #474: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #475: @35 = @30' */
  for (i=0, rr=w35, cs=w30; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #476: @32 = @33' */
  for (i=0, rr=w32, cs=w33; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #477: {NULL, @36} = horzsplit(@32) */
  casadi_copy(w32+28, 16, w36);
  /* #478: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<16; ++i) *rr++ = (- *cs++ );
  /* #479: @31 = mac(@35,@36,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #480: @55 = 0 */
  w55 = 0.;
  /* #481: (@31[15] = @55) */
  for (rr=w31+15, ss=(&w55); rr!=w31+16; rr+=1) *rr = *ss++;
  /* #482: @55 = 0 */
  w55 = 0.;
  /* #483: (@31[11] = @55) */
  for (rr=w31+11, ss=(&w55); rr!=w31+12; rr+=1) *rr = *ss++;
  /* #484: @55 = 0 */
  w55 = 0.;
  /* #485: (@31[7] = @55) */
  for (rr=w31+7, ss=(&w55); rr!=w31+8; rr+=1) *rr = *ss++;
  /* #486: @55 = 0 */
  w55 = 0.;
  /* #487: (@31[3] = @55) */
  for (rr=w31+3, ss=(&w55); rr!=w31+4; rr+=1) *rr = *ss++;
  /* #488: @55 = 0 */
  w55 = 0.;
  /* #489: (@31[14] = @55) */
  for (rr=w31+14, ss=(&w55); rr!=w31+15; rr+=1) *rr = *ss++;
  /* #490: @55 = 0 */
  w55 = 0.;
  /* #491: (@31[10] = @55) */
  for (rr=w31+10, ss=(&w55); rr!=w31+11; rr+=1) *rr = *ss++;
  /* #492: @55 = 0 */
  w55 = 0.;
  /* #493: (@31[6] = @55) */
  for (rr=w31+6, ss=(&w55); rr!=w31+7; rr+=1) *rr = *ss++;
  /* #494: @55 = 0 */
  w55 = 0.;
  /* #495: (@31[2] = @55) */
  for (rr=w31+2, ss=(&w55); rr!=w31+3; rr+=1) *rr = *ss++;
  /* #496: @55 = 0 */
  w55 = 0.;
  /* #497: (@31[13] = @55) */
  for (rr=w31+13, ss=(&w55); rr!=w31+14; rr+=1) *rr = *ss++;
  /* #498: @55 = 0 */
  w55 = 0.;
  /* #499: (@31[9] = @55) */
  for (rr=w31+9, ss=(&w55); rr!=w31+10; rr+=1) *rr = *ss++;
  /* #500: @55 = 0 */
  w55 = 0.;
  /* #501: (@31[5] = @55) */
  for (rr=w31+5, ss=(&w55); rr!=w31+6; rr+=1) *rr = *ss++;
  /* #502: @55 = @31[1] */
  for (rr=(&w55), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #503: @55 = (@22*@55) */
  w55  = (w22*w55);
  /* #504: @54 = (@54+@55) */
  w54 += w55;
  /* #505: @55 = 0 */
  w55 = 0.;
  /* #506: (@31[1] = @55) */
  for (rr=w31+1, ss=(&w55); rr!=w31+2; rr+=1) *rr = *ss++;
  /* #507: @55 = 0 */
  w55 = 0.;
  /* #508: (@31[12] = @55) */
  for (rr=w31+12, ss=(&w55); rr!=w31+13; rr+=1) *rr = *ss++;
  /* #509: @55 = 0 */
  w55 = 0.;
  /* #510: (@31[8] = @55) */
  for (rr=w31+8, ss=(&w55); rr!=w31+9; rr+=1) *rr = *ss++;
  /* #511: @55 = @31[4] */
  for (rr=(&w55), ss=w31+4; ss!=w31+5; ss+=1) *rr++ = *ss;
  /* #512: @55 = (@21*@55) */
  w55  = (w21*w55);
  /* #513: @54 = (@54+@55) */
  w54 += w55;
  /* #514: @32 = @77' */
  for (i=0, rr=w32, cs=w77; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #515: {NULL, @31, NULL} = horzsplit(@32) */
  casadi_copy(w32+12, 16, w31);
  /* #516: @31 = (@20*@31) */
  for (i=0, rr=w31, cs=w31; i<16; ++i) (*rr++)  = (w20*(*cs++));
  /* #517: @35 = @31' */
  for (i=0, rr=w35, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #518: {@27, @78, @29, @79} = horzsplit(@35) */
  casadi_copy(w35, 4, w27);
  casadi_copy(w35+4, 4, w78);
  casadi_copy(w35+8, 4, w29);
  casadi_copy(w35+12, 4, w79);
  /* #519: @79 = @79' */
  /* #520: {@55, NULL, NULL, NULL} = horzsplit(@79) */
  w55 = w79[0];
  /* #521: @54 = (@54+@55) */
  w54 += w55;
  /* #522: @29 = @29' */
  /* #523: {NULL, @55, NULL, NULL} = horzsplit(@29) */
  w55 = w29[1];
  /* #524: @54 = (@54-@55) */
  w54 -= w55;
  /* #525: @78 = @78' */
  /* #526: {NULL, NULL, @55, NULL} = horzsplit(@78) */
  w55 = w78[2];
  /* #527: @54 = (@54+@55) */
  w54 += w55;
  /* #528: @27 = @27' */
  /* #529: {NULL, NULL, NULL, @55} = horzsplit(@27) */
  w55 = w27[3];
  /* #530: @54 = (@54-@55) */
  w54 -= w55;
  /* #531: (@1[10] = @54) */
  for (rr=w1+10, ss=(&w54); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #532: @1 = @1' */
  /* #533: @32 = zeros(4x11) */
  casadi_clear(w32, 44);
  /* #534: @70 = zeros(11x1) */
  casadi_clear(w70, 11);
  /* #535: @54 = ones(4x1,1nz) */
  w54 = 1.;
  /* #536: {@55, NULL, NULL, NULL} = vertsplit(@54) */
  w55 = w54;
  /* #537: @80 = 00 */
  /* #538: @81 = 00 */
  /* #539: @82 = 00 */
  /* #540: @54 = vertcat(@55, @80, @81, @82) */
  rr=(&w54);
  *rr++ = w55;
  /* #541: @70 = mac(@37,@54,@70) */
  casadi_mtimes(w37, casadi_s7, (&w54), casadi_s6, w70, casadi_s5, w, 0);
  /* #542: (@32[:44:4] = @70) */
  for (rr=w32+0, ss=w70; rr!=w32+44; rr+=4) *rr = *ss++;
  /* #543: @70 = zeros(11x1) */
  casadi_clear(w70, 11);
  /* #544: @80 = 00 */
  /* #545: @54 = ones(4x1,1nz) */
  w54 = 1.;
  /* #546: {NULL, @55, NULL, NULL} = vertsplit(@54) */
  w55 = w54;
  /* #547: @81 = 00 */
  /* #548: @82 = 00 */
  /* #549: @54 = vertcat(@80, @55, @81, @82) */
  rr=(&w54);
  *rr++ = w55;
  /* #550: @70 = mac(@37,@54,@70) */
  casadi_mtimes(w37, casadi_s7, (&w54), casadi_s8, w70, casadi_s5, w, 0);
  /* #551: (@32[1:45:4] = @70) */
  for (rr=w32+1, ss=w70; rr!=w32+45; rr+=4) *rr = *ss++;
  /* #552: @70 = zeros(11x1) */
  casadi_clear(w70, 11);
  /* #553: @80 = 00 */
  /* #554: @81 = 00 */
  /* #555: @54 = ones(4x1,1nz) */
  w54 = 1.;
  /* #556: {NULL, NULL, @55, NULL} = vertsplit(@54) */
  w55 = w54;
  /* #557: @82 = 00 */
  /* #558: @54 = vertcat(@80, @81, @55, @82) */
  rr=(&w54);
  *rr++ = w55;
  /* #559: @70 = mac(@37,@54,@70) */
  casadi_mtimes(w37, casadi_s7, (&w54), casadi_s9, w70, casadi_s5, w, 0);
  /* #560: (@32[2:46:4] = @70) */
  for (rr=w32+2, ss=w70; rr!=w32+46; rr+=4) *rr = *ss++;
  /* #561: @70 = zeros(11x1) */
  casadi_clear(w70, 11);
  /* #562: @80 = 00 */
  /* #563: @81 = 00 */
  /* #564: @82 = 00 */
  /* #565: @54 = ones(4x1,1nz) */
  w54 = 1.;
  /* #566: {NULL, NULL, NULL, @55} = vertsplit(@54) */
  w55 = w54;
  /* #567: @54 = vertcat(@80, @81, @82, @55) */
  rr=(&w54);
  *rr++ = w55;
  /* #568: @70 = mac(@37,@54,@70) */
  casadi_mtimes(w37, casadi_s7, (&w54), casadi_s10, w70, casadi_s5, w, 0);
  /* #569: (@32[3:47:4] = @70) */
  for (rr=w32+3, ss=w70; rr!=w32+47; rr+=4) *rr = *ss++;
  /* #570: @37 = @32' */
  for (i=0, rr=w37, cs=w32; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #571: @28 = mac(@1,@37,@28) */
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w37+i*11; k<11; ++k) *rr += ss[k*1]**tt++;
  /* #572: @62 = mac(@28,@26,@62) */
  for (i=0, rr=(&w62); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #573: @0 = (@0+@62) */
  w0 += w62;
  /* #574: @62 = 0 */
  w62 = 0.;
  /* #575: @83 = [25, 15] */
  casadi_copy(casadi_c2, 2, w83);
  /* #576: @83 = @83' */
  /* #577: @54 = 0.1 */
  w54 = 1.0000000000000001e-01;
  /* #578: @55 = 0.325 */
  w55 = 3.2500000000000001e-01;
  /* #579: @72 = input[3][21] */
  w72 = arg[3] ? arg[3][21] : 0;
  /* #580: @55 = (@55+@72) */
  w55 += w72;
  /* #581: @54 = (@54+@55) */
  w54 += w55;
  /* #582: @41 = (@41-@54) */
  w41 -= w54;
  /* #583: @54 = 0 */
  w54 = 0.;
  /* #584: @16 = @16' */
  /* #585: @54 = mac(@16,@2,@54) */
  casadi_mtimes(w16, casadi_s12, w2, casadi_s5, (&w54), casadi_s11, w, 0);
  /* #586: @84 = vertcat(@41, @54) */
  rr=w84;
  *rr++ = w41;
  *rr++ = w54;
  /* #587: @62 = mac(@83,@84,@62) */
  for (i=0, rr=(&w62); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w83+j, tt=w84+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #588: @0 = (@0+@62) */
  w0 += w62;
  /* #589: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #590: @0 = 0 */
  w0 = 0.;
  /* #591: @1 = zeros(11x1) */
  casadi_clear(w1, 11);
  /* #592: @70 = zeros(11x1) */
  casadi_clear(w70, 11);
  /* #593: @16 = zeros(11x1,3nz) */
  casadi_clear(w16, 3);
  /* #594: @62 = input[3][22] */
  w62 = arg[3] ? arg[3][22] : 0;
  /* #595: @41 = (@23-@62) */
  w41  = (w23-w62);
  /* #596: @54 = (2.*@41) */
  w54 = (2.* w41 );
  /* #597: @55 = sq(@41) */
  w55 = casadi_sq( w41 );
  /* #598: @56 = input[3][23] */
  w56 = arg[3] ? arg[3][23] : 0;
  /* #599: @53 = (@42-@56) */
  w53  = (w42-w56);
  /* #600: @49 = sq(@53) */
  w49 = casadi_sq( w53 );
  /* #601: @55 = (@55+@49) */
  w55 += w49;
  /* #602: @49 = input[3][24] */
  w49 = arg[3] ? arg[3][24] : 0;
  /* #603: @57 = (@45-@49) */
  w57  = (w45-w49);
  /* #604: @47 = sq(@57) */
  w47 = casadi_sq( w57 );
  /* #605: @55 = (@55+@47) */
  w55 += w47;
  /* #606: @55 = sqrt(@55) */
  w55 = sqrt( w55 );
  /* #607: @47 = (2.*@55) */
  w47 = (2.* w55 );
  /* #608: @54 = (@54/@47) */
  w54 /= w47;
  /* #609: (@16[0] = @54) */
  for (rr=w16+0, ss=(&w54); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #610: @64 = (2.*@53) */
  w64 = (2.* w53 );
  /* #611: @64 = (@64/@47) */
  w64 /= w47;
  /* #612: (@16[1] = @64) */
  for (rr=w16+1, ss=(&w64); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #613: @52 = (2.*@57) */
  w52 = (2.* w57 );
  /* #614: @52 = (@52/@47) */
  w52 /= w47;
  /* #615: (@16[2] = @52) */
  for (rr=w16+2, ss=(&w52); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #616: @51 = dense(@16) */
  casadi_densify(w16, casadi_s4, w51, 0);
  /* #617: @70 = mac(@38,@51,@70) */
  for (i=0, rr=w70; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w38+j, tt=w51+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #618: {@58, @59, @48, @60, @24, @44, @61, @39, @50, @40, @63} = vertsplit(@70) */
  w58 = w70[0];
  w59 = w70[1];
  w48 = w70[2];
  w60 = w70[3];
  w24 = w70[4];
  w44 = w70[5];
  w61 = w70[6];
  w39 = w70[7];
  w50 = w70[8];
  w40 = w70[9];
  w63 = w70[10];
  /* #619: @73 = (2.*@41) */
  w73 = (2.* w41 );
  /* #620: @71 = (@64/@47) */
  w71  = (w64/w47);
  /* #621: @85 = 0 */
  w85 = 0.;
  /* #622: @70 = @2; (@70[2] = @85) */
  casadi_copy(w2, 11, w70);
  for (rr=w70+2, ss=(&w85); rr!=w70+3; rr+=1) *rr = *ss++;
  /* #623: @85 = @70[1] */
  for (rr=(&w85), ss=w70+1; ss!=w70+2; ss+=1) *rr++ = *ss;
  /* #624: @71 = (@71*@85) */
  w71 *= w85;
  /* #625: @71 = (-@71) */
  w71 = (- w71 );
  /* #626: @86 = (@52/@47) */
  w86  = (w52/w47);
  /* #627: @87 = @2[2] */
  for (rr=(&w87), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #628: @86 = (@86*@87) */
  w86 *= w87;
  /* #629: @71 = (@71-@86) */
  w71 -= w86;
  /* #630: @86 = (@54/@47) */
  w86  = (w54/w47);
  /* #631: @88 = 0 */
  w88 = 0.;
  /* #632: (@70[1] = @88) */
  for (rr=w70+1, ss=(&w88); rr!=w70+2; rr+=1) *rr = *ss++;
  /* #633: @88 = @70[0] */
  for (rr=(&w88), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #634: @86 = (@86*@88) */
  w86 *= w88;
  /* #635: @71 = (@71-@86) */
  w71 -= w86;
  /* #636: @71 = (2.*@71) */
  w71 = (2.* w71 );
  /* #637: @86 = (2.*@55) */
  w86 = (2.* w55 );
  /* #638: @71 = (@71/@86) */
  w71 /= w86;
  /* #639: @73 = (@73*@71) */
  w73 *= w71;
  /* #640: @88 = (@88/@47) */
  w88 /= w47;
  /* #641: @88 = (2.*@88) */
  w88 = (2.* w88 );
  /* #642: @73 = (@73+@88) */
  w73 += w88;
  /* #643: @58 = (@58+@73) */
  w58 += w73;
  /* #644: (@1[0] = @58) */
  for (rr=w1+0, ss=(&w58); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #645: @85 = (@85/@47) */
  w85 /= w47;
  /* #646: @85 = (2.*@85) */
  w85 = (2.* w85 );
  /* #647: @58 = (2.*@53) */
  w58 = (2.* w53 );
  /* #648: @58 = (@58*@71) */
  w58 *= w71;
  /* #649: @85 = (@85+@58) */
  w85 += w58;
  /* #650: @59 = (@59+@85) */
  w59 += w85;
  /* #651: (@1[1] = @59) */
  for (rr=w1+1, ss=(&w59); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #652: @87 = (@87/@47) */
  w87 /= w47;
  /* #653: @87 = (2.*@87) */
  w87 = (2.* w87 );
  /* #654: @59 = (2.*@57) */
  w59 = (2.* w57 );
  /* #655: @59 = (@59*@71) */
  w59 *= w71;
  /* #656: @87 = (@87+@59) */
  w87 += w59;
  /* #657: @48 = (@48+@87) */
  w48 += w87;
  /* #658: (@1[2] = @48) */
  for (rr=w1+2, ss=(&w48); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #659: @28 = zeros(4x1) */
  casadi_clear(w28, 4);
  /* #660: @65 = zeros(11x11) */
  casadi_clear(w65, 121);
  /* #661: @70 = @69' */
  casadi_copy(w69, 11, w70);
  /* #662: @65 = mac(@51,@70,@65) */
  for (i=0, rr=w65; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w51+j, tt=w70+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #663: @74 = @65' */
  for (i=0, rr=w74, cs=w65; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #664: {@18, @32, @77} = horzsplit(@74) */
  casadi_copy(w74, 33, w18);
  casadi_copy(w74+33, 44, w32);
  casadi_copy(w74+77, 44, w77);
  /* #665: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #666: {NULL, @75, NULL} = horzsplit(@17) */
  casadi_copy(w17+21, 9, w75);
  /* #667: @48 = dot(@6, @75) */
  w48 = casadi_dot(9, w6, w75);
  /* #668: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #669: (@28[0] += @48) */
  for (rr=w28+0, ss=(&w48); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #670: @4 = (@14*@75) */
  for (i=0, rr=w4, cs=w75; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #671: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #672: @76 = @15' */
  for (i=0, rr=w76, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #673: @5 = mac(@76,@75,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w75+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #674: @4 = (@4+@5) */
  for (i=0, rr=w4, cs=w5; i<9; ++i) (*rr++) += (*cs++);
  /* #675: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #676: @76 = @6' */
  for (i=0, rr=w76, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #677: @5 = mac(@75,@76,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w75+j, tt=w76+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #678: @5 = (2.*@5) */
  for (i=0, rr=w5, cs=w5; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #679: @4 = (@4+@5) */
  for (i=0, rr=w4, cs=w5; i<9; ++i) (*rr++) += (*cs++);
  /* #680: @48 = @4[5] */
  for (rr=(&w48), ss=w4+5; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #681: (@28[1] += @48) */
  for (rr=w28+1, ss=(&w48); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #682: @48 = 0 */
  w48 = 0.;
  /* #683: (@4[5] = @48) */
  for (rr=w4+5, ss=(&w48); rr!=w4+6; rr+=1) *rr = *ss++;
  /* #684: @48 = @4[2] */
  for (rr=(&w48), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #685: @48 = (-@48) */
  w48 = (- w48 );
  /* #686: (@28[2] += @48) */
  for (rr=w28+2, ss=(&w48); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #687: @48 = 0 */
  w48 = 0.;
  /* #688: (@4[2] = @48) */
  for (rr=w4+2, ss=(&w48); rr!=w4+3; rr+=1) *rr = *ss++;
  /* #689: @48 = @4[1] */
  for (rr=(&w48), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #690: (@28[3] += @48) */
  for (rr=w28+3, ss=(&w48); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #691: @48 = 0 */
  w48 = 0.;
  /* #692: (@4[1] = @48) */
  for (rr=w4+1, ss=(&w48); rr!=w4+2; rr+=1) *rr = *ss++;
  /* #693: @48 = @4[7] */
  for (rr=(&w48), ss=w4+7; ss!=w4+8; ss+=1) *rr++ = *ss;
  /* #694: @48 = (-@48) */
  w48 = (- w48 );
  /* #695: (@28[1] += @48) */
  for (rr=w28+1, ss=(&w48); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #696: @48 = 0 */
  w48 = 0.;
  /* #697: (@4[7] = @48) */
  for (rr=w4+7, ss=(&w48); rr!=w4+8; rr+=1) *rr = *ss++;
  /* #698: @48 = @4[6] */
  for (rr=(&w48), ss=w4+6; ss!=w4+7; ss+=1) *rr++ = *ss;
  /* #699: (@28[2] += @48) */
  for (rr=w28+2, ss=(&w48); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #700: @48 = 0 */
  w48 = 0.;
  /* #701: (@4[6] = @48) */
  for (rr=w4+6, ss=(&w48); rr!=w4+7; rr+=1) *rr = *ss++;
  /* #702: @48 = @4[3] */
  for (rr=(&w48), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #703: @48 = (-@48) */
  w48 = (- w48 );
  /* #704: (@28[3] += @48) */
  for (rr=w28+3, ss=(&w48); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #705: @27 = (@28/@12) */
  for (i=0, rr=w27, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #706: @78 = (@13/@12) */
  for (i=0, rr=w78, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #707: @78 = (-@78) */
  for (i=0, rr=w78, cs=w78; i<4; ++i) *rr++ = (- *cs++ );
  /* #708: @48 = dot(@78, @28) */
  w48 = casadi_dot(4, w78, w28);
  /* #709: @48 = (@48/@12) */
  w48 /= w12;
  /* #710: @78 = (@48*@11) */
  for (i=0, rr=w78, cs=w11; i<4; ++i) (*rr++)  = (w48*(*cs++));
  /* #711: @27 = (@27+@78) */
  for (i=0, rr=w27, cs=w78; i<4; ++i) (*rr++) += (*cs++);
  /* #712: {@48, @87, @59, @71} = vertsplit(@27) */
  w48 = w27[0];
  w87 = w27[1];
  w59 = w27[2];
  w71 = w27[3];
  /* #713: @60 = (@60+@48) */
  w60 += w48;
  /* #714: (@1[3] = @60) */
  for (rr=w1+3, ss=(&w60); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #715: @24 = (@24+@87) */
  w24 += w87;
  /* #716: (@1[4] = @24) */
  for (rr=w1+4, ss=(&w24); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #717: @44 = (@44+@59) */
  w44 += w59;
  /* #718: (@1[5] = @44) */
  for (rr=w1+5, ss=(&w44); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #719: @61 = (@61+@71) */
  w61 += w71;
  /* #720: (@1[6] = @61) */
  for (rr=w1+6, ss=(&w61); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #721: (@1[7] = @39) */
  for (rr=w1+7, ss=(&w39); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #722: (@1[8] = @50) */
  for (rr=w1+8, ss=(&w50); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #723: (@1[9] = @40) */
  for (rr=w1+9, ss=(&w40); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #724: @35 = zeros(4x4) */
  casadi_clear(w35, 16);
  /* #725: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #726: @33 = @77' */
  for (i=0, rr=w33, cs=w77; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #727: {NULL, @36} = horzsplit(@33) */
  casadi_copy(w33+28, 16, w36);
  /* #728: @36 = (-@36) */
  for (i=0, rr=w36, cs=w36; i<16; ++i) *rr++ = (- *cs++ );
  /* #729: @35 = mac(@31,@36,@35) */
  for (i=0, rr=w35; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w31+j, tt=w36+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #730: @40 = 0 */
  w40 = 0.;
  /* #731: (@35[15] = @40) */
  for (rr=w35+15, ss=(&w40); rr!=w35+16; rr+=1) *rr = *ss++;
  /* #732: @40 = 0 */
  w40 = 0.;
  /* #733: (@35[11] = @40) */
  for (rr=w35+11, ss=(&w40); rr!=w35+12; rr+=1) *rr = *ss++;
  /* #734: @40 = 0 */
  w40 = 0.;
  /* #735: (@35[7] = @40) */
  for (rr=w35+7, ss=(&w40); rr!=w35+8; rr+=1) *rr = *ss++;
  /* #736: @40 = 0 */
  w40 = 0.;
  /* #737: (@35[3] = @40) */
  for (rr=w35+3, ss=(&w40); rr!=w35+4; rr+=1) *rr = *ss++;
  /* #738: @40 = 0 */
  w40 = 0.;
  /* #739: (@35[14] = @40) */
  for (rr=w35+14, ss=(&w40); rr!=w35+15; rr+=1) *rr = *ss++;
  /* #740: @40 = 0 */
  w40 = 0.;
  /* #741: (@35[10] = @40) */
  for (rr=w35+10, ss=(&w40); rr!=w35+11; rr+=1) *rr = *ss++;
  /* #742: @40 = 0 */
  w40 = 0.;
  /* #743: (@35[6] = @40) */
  for (rr=w35+6, ss=(&w40); rr!=w35+7; rr+=1) *rr = *ss++;
  /* #744: @40 = 0 */
  w40 = 0.;
  /* #745: (@35[2] = @40) */
  for (rr=w35+2, ss=(&w40); rr!=w35+3; rr+=1) *rr = *ss++;
  /* #746: @40 = 0 */
  w40 = 0.;
  /* #747: (@35[13] = @40) */
  for (rr=w35+13, ss=(&w40); rr!=w35+14; rr+=1) *rr = *ss++;
  /* #748: @40 = 0 */
  w40 = 0.;
  /* #749: (@35[9] = @40) */
  for (rr=w35+9, ss=(&w40); rr!=w35+10; rr+=1) *rr = *ss++;
  /* #750: @40 = 0 */
  w40 = 0.;
  /* #751: (@35[5] = @40) */
  for (rr=w35+5, ss=(&w40); rr!=w35+6; rr+=1) *rr = *ss++;
  /* #752: @40 = @35[1] */
  for (rr=(&w40), ss=w35+1; ss!=w35+2; ss+=1) *rr++ = *ss;
  /* #753: @40 = (@22*@40) */
  w40  = (w22*w40);
  /* #754: @63 = (@63+@40) */
  w63 += w40;
  /* #755: @40 = 0 */
  w40 = 0.;
  /* #756: (@35[1] = @40) */
  for (rr=w35+1, ss=(&w40); rr!=w35+2; rr+=1) *rr = *ss++;
  /* #757: @40 = 0 */
  w40 = 0.;
  /* #758: (@35[12] = @40) */
  for (rr=w35+12, ss=(&w40); rr!=w35+13; rr+=1) *rr = *ss++;
  /* #759: @40 = 0 */
  w40 = 0.;
  /* #760: (@35[8] = @40) */
  for (rr=w35+8, ss=(&w40); rr!=w35+9; rr+=1) *rr = *ss++;
  /* #761: @40 = @35[4] */
  for (rr=(&w40), ss=w35+4; ss!=w35+5; ss+=1) *rr++ = *ss;
  /* #762: @40 = (@21*@40) */
  w40  = (w21*w40);
  /* #763: @63 = (@63+@40) */
  w63 += w40;
  /* #764: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #765: {NULL, @35, NULL} = horzsplit(@33) */
  casadi_copy(w33+12, 16, w35);
  /* #766: @35 = (@20*@35) */
  for (i=0, rr=w35, cs=w35; i<16; ++i) (*rr++)  = (w20*(*cs++));
  /* #767: @31 = @35' */
  for (i=0, rr=w31, cs=w35; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #768: {@27, @78, @28, @29} = horzsplit(@31) */
  casadi_copy(w31, 4, w27);
  casadi_copy(w31+4, 4, w78);
  casadi_copy(w31+8, 4, w28);
  casadi_copy(w31+12, 4, w29);
  /* #769: @29 = @29' */
  /* #770: {@40, NULL, NULL, NULL} = horzsplit(@29) */
  w40 = w29[0];
  /* #771: @63 = (@63+@40) */
  w63 += w40;
  /* #772: @28 = @28' */
  /* #773: {NULL, @40, NULL, NULL} = horzsplit(@28) */
  w40 = w28[1];
  /* #774: @63 = (@63-@40) */
  w63 -= w40;
  /* #775: @78 = @78' */
  /* #776: {NULL, NULL, @40, NULL} = horzsplit(@78) */
  w40 = w78[2];
  /* #777: @63 = (@63+@40) */
  w63 += w40;
  /* #778: @27 = @27' */
  /* #779: {NULL, NULL, NULL, @40} = horzsplit(@27) */
  w40 = w27[3];
  /* #780: @63 = (@63-@40) */
  w63 -= w40;
  /* #781: (@1[10] = @63) */
  for (rr=w1+10, ss=(&w63); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #782: @1 = @1' */
  /* #783: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*11; k<11; ++k) *rr += ss[k*1]**tt++;
  /* #784: @63 = 0 */
  w63 = 0.;
  /* #785: @27 = zeros(1x4) */
  casadi_clear(w27, 4);
  /* #786: @1 = zeros(11x1) */
  casadi_clear(w1, 11);
  /* #787: @51 = zeros(11x1) */
  casadi_clear(w51, 11);
  /* #788: @70 = dense(@16) */
  casadi_densify(w16, casadi_s4, w70, 0);
  /* #789: @51 = mac(@38,@70,@51) */
  for (i=0, rr=w51; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w38+j, tt=w70+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #790: {@40, @50, @39, @61, @71, @44, @59, @24, @87, @60, @48} = vertsplit(@51) */
  w40 = w51[0];
  w50 = w51[1];
  w39 = w51[2];
  w61 = w51[3];
  w71 = w51[4];
  w44 = w51[5];
  w59 = w51[6];
  w24 = w51[7];
  w87 = w51[8];
  w60 = w51[9];
  w48 = w51[10];
  /* #791: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #792: @64 = (@64/@47) */
  w64 /= w47;
  /* #793: @85 = 0 */
  w85 = 0.;
  /* #794: @51 = @2; (@51[2] = @85) */
  casadi_copy(w2, 11, w51);
  for (rr=w51+2, ss=(&w85); rr!=w51+3; rr+=1) *rr = *ss++;
  /* #795: @85 = @51[1] */
  for (rr=(&w85), ss=w51+1; ss!=w51+2; ss+=1) *rr++ = *ss;
  /* #796: @64 = (@64*@85) */
  w64 *= w85;
  /* #797: @64 = (-@64) */
  w64 = (- w64 );
  /* #798: @52 = (@52/@47) */
  w52 /= w47;
  /* #799: @58 = @2[2] */
  for (rr=(&w58), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #800: @52 = (@52*@58) */
  w52 *= w58;
  /* #801: @64 = (@64-@52) */
  w64 -= w52;
  /* #802: @54 = (@54/@47) */
  w54 /= w47;
  /* #803: @52 = 0 */
  w52 = 0.;
  /* #804: (@51[1] = @52) */
  for (rr=w51+1, ss=(&w52); rr!=w51+2; rr+=1) *rr = *ss++;
  /* #805: @52 = @51[0] */
  for (rr=(&w52), ss=w51+0; ss!=w51+1; ss+=1) *rr++ = *ss;
  /* #806: @54 = (@54*@52) */
  w54 *= w52;
  /* #807: @64 = (@64-@54) */
  w64 -= w54;
  /* #808: @64 = (2.*@64) */
  w64 = (2.* w64 );
  /* #809: @54 = (2.*@55) */
  w54 = (2.* w55 );
  /* #810: @64 = (@64/@54) */
  w64 /= w54;
  /* #811: @41 = (@41*@64) */
  w41 *= w64;
  /* #812: @52 = (@52/@47) */
  w52 /= w47;
  /* #813: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #814: @41 = (@41+@52) */
  w41 += w52;
  /* #815: @40 = (@40+@41) */
  w40 += w41;
  /* #816: (@1[0] = @40) */
  for (rr=w1+0, ss=(&w40); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #817: @85 = (@85/@47) */
  w85 /= w47;
  /* #818: @85 = (2.*@85) */
  w85 = (2.* w85 );
  /* #819: @53 = (2.*@53) */
  w53 = (2.* w53 );
  /* #820: @53 = (@53*@64) */
  w53 *= w64;
  /* #821: @85 = (@85+@53) */
  w85 += w53;
  /* #822: @50 = (@50+@85) */
  w50 += w85;
  /* #823: (@1[1] = @50) */
  for (rr=w1+1, ss=(&w50); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #824: @58 = (@58/@47) */
  w58 /= w47;
  /* #825: @58 = (2.*@58) */
  w58 = (2.* w58 );
  /* #826: @57 = (2.*@57) */
  w57 = (2.* w57 );
  /* #827: @57 = (@57*@64) */
  w57 *= w64;
  /* #828: @58 = (@58+@57) */
  w58 += w57;
  /* #829: @39 = (@39+@58) */
  w39 += w58;
  /* #830: (@1[2] = @39) */
  for (rr=w1+2, ss=(&w39); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #831: @78 = zeros(4x1) */
  casadi_clear(w78, 4);
  /* #832: @38 = zeros(11x11) */
  casadi_clear(w38, 121);
  /* #833: @69 = @69' */
  /* #834: @38 = mac(@70,@69,@38) */
  for (i=0, rr=w38; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w70+j, tt=w69+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #835: @74 = @38' */
  for (i=0, rr=w74, cs=w38; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #836: {@17, @33, @32} = horzsplit(@74) */
  casadi_copy(w74, 33, w17);
  casadi_copy(w74+33, 44, w33);
  casadi_copy(w74+77, 44, w32);
  /* #837: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #838: {NULL, @4, NULL} = horzsplit(@18) */
  casadi_copy(w18+21, 9, w4);
  /* #839: @39 = dot(@6, @4) */
  w39 = casadi_dot(9, w6, w4);
  /* #840: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #841: (@78[0] += @39) */
  for (rr=w78+0, ss=(&w39); rr!=w78+1; rr+=1) *rr += *ss++;
  /* #842: @5 = (@14*@4) */
  for (i=0, rr=w5, cs=w4; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #843: @75 = zeros(3x3) */
  casadi_clear(w75, 9);
  /* #844: @76 = @15' */
  for (i=0, rr=w76, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #845: @75 = mac(@76,@4,@75) */
  for (i=0, rr=w75; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #846: @5 = (@5+@75) */
  for (i=0, rr=w5, cs=w75; i<9; ++i) (*rr++) += (*cs++);
  /* #847: @75 = zeros(3x3) */
  casadi_clear(w75, 9);
  /* #848: @76 = @6' */
  for (i=0, rr=w76, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #849: @75 = mac(@4,@76,@75) */
  for (i=0, rr=w75; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w76+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #850: @75 = (2.*@75) */
  for (i=0, rr=w75, cs=w75; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #851: @5 = (@5+@75) */
  for (i=0, rr=w5, cs=w75; i<9; ++i) (*rr++) += (*cs++);
  /* #852: @14 = @5[5] */
  for (rr=(&w14), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #853: (@78[1] += @14) */
  for (rr=w78+1, ss=(&w14); rr!=w78+2; rr+=1) *rr += *ss++;
  /* #854: @14 = 0 */
  w14 = 0.;
  /* #855: (@5[5] = @14) */
  for (rr=w5+5, ss=(&w14); rr!=w5+6; rr+=1) *rr = *ss++;
  /* #856: @14 = @5[2] */
  for (rr=(&w14), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #857: @14 = (-@14) */
  w14 = (- w14 );
  /* #858: (@78[2] += @14) */
  for (rr=w78+2, ss=(&w14); rr!=w78+3; rr+=1) *rr += *ss++;
  /* #859: @14 = 0 */
  w14 = 0.;
  /* #860: (@5[2] = @14) */
  for (rr=w5+2, ss=(&w14); rr!=w5+3; rr+=1) *rr = *ss++;
  /* #861: @14 = @5[1] */
  for (rr=(&w14), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #862: (@78[3] += @14) */
  for (rr=w78+3, ss=(&w14); rr!=w78+4; rr+=1) *rr += *ss++;
  /* #863: @14 = 0 */
  w14 = 0.;
  /* #864: (@5[1] = @14) */
  for (rr=w5+1, ss=(&w14); rr!=w5+2; rr+=1) *rr = *ss++;
  /* #865: @14 = @5[7] */
  for (rr=(&w14), ss=w5+7; ss!=w5+8; ss+=1) *rr++ = *ss;
  /* #866: @14 = (-@14) */
  w14 = (- w14 );
  /* #867: (@78[1] += @14) */
  for (rr=w78+1, ss=(&w14); rr!=w78+2; rr+=1) *rr += *ss++;
  /* #868: @14 = 0 */
  w14 = 0.;
  /* #869: (@5[7] = @14) */
  for (rr=w5+7, ss=(&w14); rr!=w5+8; rr+=1) *rr = *ss++;
  /* #870: @14 = @5[6] */
  for (rr=(&w14), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #871: (@78[2] += @14) */
  for (rr=w78+2, ss=(&w14); rr!=w78+3; rr+=1) *rr += *ss++;
  /* #872: @14 = 0 */
  w14 = 0.;
  /* #873: (@5[6] = @14) */
  for (rr=w5+6, ss=(&w14); rr!=w5+7; rr+=1) *rr = *ss++;
  /* #874: @14 = @5[3] */
  for (rr=(&w14), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #875: @14 = (-@14) */
  w14 = (- w14 );
  /* #876: (@78[3] += @14) */
  for (rr=w78+3, ss=(&w14); rr!=w78+4; rr+=1) *rr += *ss++;
  /* #877: @28 = (@78/@12) */
  for (i=0, rr=w28, cr=w78; i<4; ++i) (*rr++)  = ((*cr++)/w12);
  /* #878: @13 = (@13/@12) */
  for (i=0, rr=w13; i<4; ++i) (*rr++) /= w12;
  /* #879: @13 = (-@13) */
  for (i=0, rr=w13, cs=w13; i<4; ++i) *rr++ = (- *cs++ );
  /* #880: @14 = dot(@13, @78) */
  w14 = casadi_dot(4, w13, w78);
  /* #881: @14 = (@14/@12) */
  w14 /= w12;
  /* #882: @11 = (@14*@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #883: @28 = (@28+@11) */
  for (i=0, rr=w28, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #884: {@14, @12, @39, @58} = vertsplit(@28) */
  w14 = w28[0];
  w12 = w28[1];
  w39 = w28[2];
  w58 = w28[3];
  /* #885: @61 = (@61+@14) */
  w61 += w14;
  /* #886: (@1[3] = @61) */
  for (rr=w1+3, ss=(&w61); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #887: @71 = (@71+@12) */
  w71 += w12;
  /* #888: (@1[4] = @71) */
  for (rr=w1+4, ss=(&w71); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #889: @44 = (@44+@39) */
  w44 += w39;
  /* #890: (@1[5] = @44) */
  for (rr=w1+5, ss=(&w44); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #891: @59 = (@59+@58) */
  w59 += w58;
  /* #892: (@1[6] = @59) */
  for (rr=w1+6, ss=(&w59); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #893: (@1[7] = @24) */
  for (rr=w1+7, ss=(&w24); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #894: (@1[8] = @87) */
  for (rr=w1+8, ss=(&w87); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #895: (@1[9] = @60) */
  for (rr=w1+9, ss=(&w60); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #896: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #897: @35 = @30' */
  for (i=0, rr=w35, cs=w30; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #898: @77 = @32' */
  for (i=0, rr=w77, cs=w32; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #899: {NULL, @30} = horzsplit(@77) */
  casadi_copy(w77+28, 16, w30);
  /* #900: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<16; ++i) *rr++ = (- *cs++ );
  /* #901: @31 = mac(@35,@30,@31) */
  for (i=0, rr=w31; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #902: @60 = 0 */
  w60 = 0.;
  /* #903: (@31[15] = @60) */
  for (rr=w31+15, ss=(&w60); rr!=w31+16; rr+=1) *rr = *ss++;
  /* #904: @60 = 0 */
  w60 = 0.;
  /* #905: (@31[11] = @60) */
  for (rr=w31+11, ss=(&w60); rr!=w31+12; rr+=1) *rr = *ss++;
  /* #906: @60 = 0 */
  w60 = 0.;
  /* #907: (@31[7] = @60) */
  for (rr=w31+7, ss=(&w60); rr!=w31+8; rr+=1) *rr = *ss++;
  /* #908: @60 = 0 */
  w60 = 0.;
  /* #909: (@31[3] = @60) */
  for (rr=w31+3, ss=(&w60); rr!=w31+4; rr+=1) *rr = *ss++;
  /* #910: @60 = 0 */
  w60 = 0.;
  /* #911: (@31[14] = @60) */
  for (rr=w31+14, ss=(&w60); rr!=w31+15; rr+=1) *rr = *ss++;
  /* #912: @60 = 0 */
  w60 = 0.;
  /* #913: (@31[10] = @60) */
  for (rr=w31+10, ss=(&w60); rr!=w31+11; rr+=1) *rr = *ss++;
  /* #914: @60 = 0 */
  w60 = 0.;
  /* #915: (@31[6] = @60) */
  for (rr=w31+6, ss=(&w60); rr!=w31+7; rr+=1) *rr = *ss++;
  /* #916: @60 = 0 */
  w60 = 0.;
  /* #917: (@31[2] = @60) */
  for (rr=w31+2, ss=(&w60); rr!=w31+3; rr+=1) *rr = *ss++;
  /* #918: @60 = 0 */
  w60 = 0.;
  /* #919: (@31[13] = @60) */
  for (rr=w31+13, ss=(&w60); rr!=w31+14; rr+=1) *rr = *ss++;
  /* #920: @60 = 0 */
  w60 = 0.;
  /* #921: (@31[9] = @60) */
  for (rr=w31+9, ss=(&w60); rr!=w31+10; rr+=1) *rr = *ss++;
  /* #922: @60 = 0 */
  w60 = 0.;
  /* #923: (@31[5] = @60) */
  for (rr=w31+5, ss=(&w60); rr!=w31+6; rr+=1) *rr = *ss++;
  /* #924: @60 = @31[1] */
  for (rr=(&w60), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #925: @22 = (@22*@60) */
  w22 *= w60;
  /* #926: @48 = (@48+@22) */
  w48 += w22;
  /* #927: @22 = 0 */
  w22 = 0.;
  /* #928: (@31[1] = @22) */
  for (rr=w31+1, ss=(&w22); rr!=w31+2; rr+=1) *rr = *ss++;
  /* #929: @22 = 0 */
  w22 = 0.;
  /* #930: (@31[12] = @22) */
  for (rr=w31+12, ss=(&w22); rr!=w31+13; rr+=1) *rr = *ss++;
  /* #931: @22 = 0 */
  w22 = 0.;
  /* #932: (@31[8] = @22) */
  for (rr=w31+8, ss=(&w22); rr!=w31+9; rr+=1) *rr = *ss++;
  /* #933: @22 = @31[4] */
  for (rr=(&w22), ss=w31+4; ss!=w31+5; ss+=1) *rr++ = *ss;
  /* #934: @21 = (@21*@22) */
  w21 *= w22;
  /* #935: @48 = (@48+@21) */
  w48 += w21;
  /* #936: @77 = @33' */
  for (i=0, rr=w77, cs=w33; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #937: {NULL, @31, NULL} = horzsplit(@77) */
  casadi_copy(w77+12, 16, w31);
  /* #938: @31 = (@20*@31) */
  for (i=0, rr=w31, cs=w31; i<16; ++i) (*rr++)  = (w20*(*cs++));
  /* #939: @35 = @31' */
  for (i=0, rr=w35, cs=w31; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #940: {@28, @11, @13, @78} = horzsplit(@35) */
  casadi_copy(w35, 4, w28);
  casadi_copy(w35+4, 4, w11);
  casadi_copy(w35+8, 4, w13);
  casadi_copy(w35+12, 4, w78);
  /* #941: @78 = @78' */
  /* #942: {@20, NULL, NULL, NULL} = horzsplit(@78) */
  w20 = w78[0];
  /* #943: @48 = (@48+@20) */
  w48 += w20;
  /* #944: @13 = @13' */
  /* #945: {NULL, @20, NULL, NULL} = horzsplit(@13) */
  w20 = w13[1];
  /* #946: @48 = (@48-@20) */
  w48 -= w20;
  /* #947: @11 = @11' */
  /* #948: {NULL, NULL, @20, NULL} = horzsplit(@11) */
  w20 = w11[2];
  /* #949: @48 = (@48+@20) */
  w48 += w20;
  /* #950: @28 = @28' */
  /* #951: {NULL, NULL, NULL, @20} = horzsplit(@28) */
  w20 = w28[3];
  /* #952: @48 = (@48-@20) */
  w48 -= w20;
  /* #953: (@1[10] = @48) */
  for (rr=w1+10, ss=(&w48); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #954: @1 = @1' */
  /* #955: @27 = mac(@1,@37,@27) */
  for (i=0, rr=w27; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w37+i*11; k<11; ++k) *rr += ss[k*1]**tt++;
  /* #956: @63 = mac(@27,@26,@63) */
  for (i=0, rr=(&w63); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #957: @0 = (@0+@63) */
  w0 += w63;
  /* #958: @63 = 0 */
  w63 = 0.;
  /* #959: @83 = [25, 15] */
  casadi_copy(casadi_c2, 2, w83);
  /* #960: @83 = @83' */
  /* #961: @48 = 0.625 */
  w48 = 6.2500000000000000e-01;
  /* #962: @55 = (@55-@48) */
  w55 -= w48;
  /* #963: @48 = 0 */
  w48 = 0.;
  /* #964: @16 = @16' */
  /* #965: @48 = mac(@16,@2,@48) */
  casadi_mtimes(w16, casadi_s12, w2, casadi_s5, (&w48), casadi_s11, w, 0);
  /* #966: @84 = vertcat(@55, @48) */
  rr=w84;
  *rr++ = w55;
  *rr++ = w48;
  /* #967: @63 = mac(@83,@84,@63) */
  for (i=0, rr=(&w63); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w83+j, tt=w84+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #968: @0 = (@0+@63) */
  w0 += w63;
  /* #969: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #970: @0 = 0 */
  w0 = 0.;
  /* #971: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #972: @63 = input[3][0] */
  w63 = arg[3] ? arg[3][0] : 0;
  /* #973: @55 = input[3][1] */
  w55 = arg[3] ? arg[3][1] : 0;
  /* #974: @48 = input[3][2] */
  w48 = arg[3] ? arg[3][2] : 0;
  /* #975: @20 = input[3][3] */
  w20 = arg[3] ? arg[3][3] : 0;
  /* #976: @21 = input[3][4] */
  w21 = arg[3] ? arg[3][4] : 0;
  /* #977: @22 = input[3][5] */
  w22 = arg[3] ? arg[3][5] : 0;
  /* #978: @60 = input[3][6] */
  w60 = arg[3] ? arg[3][6] : 0;
  /* #979: @87 = input[3][7] */
  w87 = arg[3] ? arg[3][7] : 0;
  /* #980: @24 = input[3][8] */
  w24 = arg[3] ? arg[3][8] : 0;
  /* #981: @59 = input[3][9] */
  w59 = arg[3] ? arg[3][9] : 0;
  /* #982: @58 = input[3][10] */
  w58 = arg[3] ? arg[3][10] : 0;
  /* #983: @44 = input[3][11] */
  w44 = arg[3] ? arg[3][11] : 0;
  /* #984: @39 = input[3][12] */
  w39 = arg[3] ? arg[3][12] : 0;
  /* #985: @71 = input[3][13] */
  w71 = arg[3] ? arg[3][13] : 0;
  /* #986: @12 = input[3][14] */
  w12 = arg[3] ? arg[3][14] : 0;
  /* #987: @61 = input[3][15] */
  w61 = arg[3] ? arg[3][15] : 0;
  /* #988: @14 = input[3][16] */
  w14 = arg[3] ? arg[3][16] : 0;
  /* #989: @57 = input[3][17] */
  w57 = arg[3] ? arg[3][17] : 0;
  /* #990: @89 = vertcat(@63, @55, @48, @20, @21, @22, @60, @87, @24, @59, @58, @44, @39, @71, @12, @61, @14, @57, @25, @43, @46, @72, @62, @56, @49) */
  rr=w89;
  *rr++ = w63;
  *rr++ = w55;
  *rr++ = w48;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w60;
  *rr++ = w87;
  *rr++ = w24;
  *rr++ = w59;
  *rr++ = w58;
  *rr++ = w44;
  *rr++ = w39;
  *rr++ = w71;
  *rr++ = w12;
  *rr++ = w61;
  *rr++ = w14;
  *rr++ = w57;
  *rr++ = w25;
  *rr++ = w43;
  *rr++ = w46;
  *rr++ = w72;
  *rr++ = w62;
  *rr++ = w56;
  *rr++ = w49;
  /* #991: @90 = @89[15:18] */
  for (rr=w90, ss=w89+15; ss!=w89+18; ss+=1) *rr++ = *ss;
  /* #992: @63 = 0.5 */
  w63 = 5.0000000000000000e-01;
  /* #993: @91 = @89[:3] */
  for (rr=w91, ss=w89+0; ss!=w89+3; ss+=1) *rr++ = *ss;
  /* #994: @92 = vertcat(@23, @42, @45) */
  rr=w92;
  *rr++ = w23;
  *rr++ = w42;
  *rr++ = w45;
  /* #995: @91 = (@91-@92) */
  for (i=0, rr=w91, cs=w92; i<3; ++i) (*rr++) -= (*cs++);
  /* #996: @23 = dot(@90, @91) */
  w23 = casadi_dot(3, w90, w91);
  /* #997: @92 = (@23*@90) */
  for (i=0, rr=w92, cs=w90; i<3; ++i) (*rr++)  = (w23*(*cs++));
  /* #998: @93 = @92' */
  casadi_copy(w92, 3, w93);
  /* #999: @93 = (@63*@93) */
  for (i=0, rr=w93, cs=w93; i<3; ++i) (*rr++)  = (w63*(*cs++));
  /* #1000: @94 = @93' */
  casadi_copy(w93, 3, w94);
  /* #1001: @95 = @92' */
  casadi_copy(w92, 3, w95);
  /* #1002: @95 = (@63*@95) */
  for (i=0, rr=w95, cs=w95; i<3; ++i) (*rr++)  = (w63*(*cs++));
  /* #1003: @95 = @95' */
  /* #1004: @94 = (@94+@95) */
  for (i=0, rr=w94, cs=w95; i<3; ++i) (*rr++) += (*cs++);
  /* #1005: @63 = dot(@90, @94) */
  w63 = casadi_dot(3, w90, w94);
  /* #1006: @94 = (@63*@90) */
  for (i=0, rr=w94, cs=w90; i<3; ++i) (*rr++)  = (w63*(*cs++));
  /* #1007: @95 = zeros(3x1) */
  casadi_clear(w95, 3);
  /* #1008: @5 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w5);
  /* #1009: @63 = 0 */
  w63 = 0.;
  /* #1010: @96 = @90' */
  casadi_copy(w90, 3, w96);
  /* #1011: @63 = mac(@96,@90,@63) */
  for (i=0, rr=(&w63); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w96+j, tt=w90+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1012: @75 = @63[0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s13, rr=w75, ss=(&w63); cii!=casadi_s13+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #1013: @5 = (@5-@75) */
  for (i=0, rr=w5, cs=w75; i<9; ++i) (*rr++) -= (*cs++);
  /* #1014: @75 = @5' */
  for (i=0, rr=w75, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1015: @63 = 0.5 */
  w63 = 5.0000000000000000e-01;
  /* #1016: @96 = zeros(3x1) */
  casadi_clear(w96, 3);
  /* #1017: @96 = mac(@5,@91,@96) */
  for (i=0, rr=w96; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w91+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1018: @91 = @96' */
  casadi_copy(w96, 3, w91);
  /* #1019: @91 = (@63*@91) */
  for (i=0, rr=w91, cs=w91; i<3; ++i) (*rr++)  = (w63*(*cs++));
  /* #1020: @90 = @91' */
  casadi_copy(w91, 3, w90);
  /* #1021: @97 = @96' */
  casadi_copy(w96, 3, w97);
  /* #1022: @97 = (@63*@97) */
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w63*(*cs++));
  /* #1023: @97 = @97' */
  /* #1024: @90 = (@90+@97) */
  for (i=0, rr=w90, cs=w97; i<3; ++i) (*rr++) += (*cs++);
  /* #1025: @95 = mac(@75,@90,@95) */
  for (i=0, rr=w95; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w75+j, tt=w90+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1026: @94 = (@94+@95) */
  for (i=0, rr=w94, cs=w95; i<3; ++i) (*rr++) += (*cs++);
  /* #1027: @94 = (-@94) */
  for (i=0, rr=w94, cs=w94; i<3; ++i) *rr++ = (- *cs++ );
  /* #1028: @63 = @94[0] */
  for (rr=(&w63), ss=w94+0; ss!=w94+1; ss+=1) *rr++ = *ss;
  /* #1029: (@16[0] = @63) */
  for (rr=w16+0, ss=(&w63); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #1030: @63 = @94[1] */
  for (rr=(&w63), ss=w94+1; ss!=w94+2; ss+=1) *rr++ = *ss;
  /* #1031: (@16[1] = @63) */
  for (rr=w16+1, ss=(&w63); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #1032: @63 = @94[2] */
  for (rr=(&w63), ss=w94+2; ss!=w94+3; ss+=1) *rr++ = *ss;
  /* #1033: (@16[2] = @63) */
  for (rr=w16+2, ss=(&w63); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #1034: @16 = @16' */
  /* #1035: @94 = zeros(3x1) */
  casadi_clear(w94, 3);
  /* #1036: @75 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w75);
  /* #1037: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #1038: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #1039: @27 = vertcat(@7, @8, @9, @10) */
  rr=w27;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #1040: @7 = ||@27||_F */
  w7 = sqrt(casadi_dot(4, w27, w27));
  /* #1041: @27 = (@27/@7) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w7;
  /* #1042: @7 = @27[3] */
  for (rr=(&w7), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #1043: @7 = (-@7) */
  w7 = (- w7 );
  /* #1044: (@4[3] = @7) */
  for (rr=w4+3, ss=(&w7); rr!=w4+4; rr+=1) *rr = *ss++;
  /* #1045: @7 = @27[2] */
  for (rr=(&w7), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #1046: (@4[6] = @7) */
  for (rr=w4+6, ss=(&w7); rr!=w4+7; rr+=1) *rr = *ss++;
  /* #1047: @7 = @27[1] */
  for (rr=(&w7), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #1048: @7 = (-@7) */
  w7 = (- w7 );
  /* #1049: (@4[7] = @7) */
  for (rr=w4+7, ss=(&w7); rr!=w4+8; rr+=1) *rr = *ss++;
  /* #1050: @7 = @27[3] */
  for (rr=(&w7), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #1051: (@4[1] = @7) */
  for (rr=w4+1, ss=(&w7); rr!=w4+2; rr+=1) *rr = *ss++;
  /* #1052: @7 = @27[2] */
  for (rr=(&w7), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #1053: @7 = (-@7) */
  w7 = (- w7 );
  /* #1054: (@4[2] = @7) */
  for (rr=w4+2, ss=(&w7); rr!=w4+3; rr+=1) *rr = *ss++;
  /* #1055: @7 = @27[1] */
  for (rr=(&w7), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #1056: (@4[5] = @7) */
  for (rr=w4+5, ss=(&w7); rr!=w4+6; rr+=1) *rr = *ss++;
  /* #1057: @76 = (2.*@4) */
  for (i=0, rr=w76, cs=w4; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #1058: @5 = mac(@76,@4,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1059: @75 = (@75+@5) */
  for (i=0, rr=w75, cs=w5; i<9; ++i) (*rr++) += (*cs++);
  /* #1060: @7 = @27[0] */
  for (rr=(&w7), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #1061: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #1062: @4 = (@7*@4) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) (*rr++)  = (w7*(*cs++));
  /* #1063: @75 = (@75+@4) */
  for (i=0, rr=w75, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #1064: @95 = vertcat(@66, @67, @68) */
  rr=w95;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w68;
  /* #1065: @94 = mac(@75,@95,@94) */
  for (i=0, rr=w94; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w75+j, tt=w95+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1066: @0 = mac(@16,@94,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w94+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1067: @66 = 0.9 */
  w66 = 9.0000000000000002e-01;
  /* #1068: @67 = 0 */
  w67 = 0.;
  /* #1069: @67 = mac(@91,@96,@67) */
  for (i=0, rr=(&w67); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w91+j, tt=w96+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1070: @68 = 0 */
  w68 = 0.;
  /* #1071: @68 = mac(@93,@92,@68) */
  for (i=0, rr=(&w68); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w93+j, tt=w92+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1072: @67 = (@67+@68) */
  w67 += w68;
  /* #1073: @66 = (@66*@67) */
  w66 *= w67;
  /* #1074: @0 = (@0+@66) */
  w0 += w66;
  /* #1075: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    case 3: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 29;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 986;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
